import { db, Seeder } from '@stacksjs/database'

/**
 * Reactions, pointed at things that exist.
 *
 * `Reaction` seeded nothing at all, on every run, for the same reason
 * `RepositoryOwners` exists: `subject_id` is polymorphic. `subject_type` says
 * `issue`, `issue_comment` or `review_comment` and `subject_id` indexes
 * whichever of those three tables it names, and a factory is handed `faker` and
 * its own row's values - never a database - so there is nothing it can return.
 * It returned `null`, the column is `not null` in both dialects, and every
 * insert failed with "null value in column subject_id violates not-null
 * constraint".
 *
 * A `belongsTo` is the obvious fix and is the wrong one, exactly as it was
 * there: it generates a foreign key, and a foreign key on a polymorphic column
 * forbids two thirds of the values the column exists to hold.
 *
 * ## Why this creates the rows instead of repairing them
 *
 * `RepositoryOwners` repairs: the model pass writes repositories with an
 * invented `owner_id` and this corrects them afterwards. That shape does not
 * work here, because the insert does not survive to be repaired - a wrong id
 * is a row, a null is an error. So `Reaction` declares no `useSeeder` and this
 * is the only thing that writes the table, which is better anyway: there is no
 * window in which a reaction points at nothing.
 *
 * ## The unique index is the other half of the problem
 *
 * `reactions_one_per_person_index` is unique over
 * `(subject_type, subject_id, user_id, content)` - deliberately, because it is
 * what makes reacting idempotent. Eighty rows generated by picking randomly
 * from eight contents would collide, and a seeder that fails on a duplicate key
 * is the failure this file was written to remove. So the combinations are
 * walked rather than drawn, and checked against what is already there.
 *
 * Which also makes it re-runnable. `buddy setup` re-seeds, so this runs against
 * a database that may already hold its own output.
 */

/** The eight in `app/Actions/Markdown/emoji.ts`, which is the interface. */
const CONTENT = ['+1', '-1', 'laugh', 'hooray', 'confused', 'heart', 'rocket', 'eyes'] as const

/** Each `subject_type` and the table it indexes. */
const SUBJECTS = [
  { type: 'issue', table: 'issues' },
  { type: 'issue_comment', table: 'issue_comments' },
  { type: 'review_comment', table: 'review_comments' },
] as const

/** What `Reaction`'s `useSeeder` asked for before it could not deliver any. */
const TARGET = 80

export default class Reactions extends Seeder {
  /** After the model pass, which is what creates the subjects and the users. */
  static order = 11
  static tags = ['reactions']

  async run(): Promise<void> {
    const already = Number((await db.selectFrom('reactions').select(db.fn.countAll().as('n')).executeTakeFirst())?.n ?? 0)
    const wanted = TARGET - already

    // Re-running against a database that already has them is a no-op rather
    // than another eighty.
    if (wanted <= 0)
      return

    const users = (await db.selectFrom('users').select(['id']).orderBy('id').limit(500).execute()).map(row => Number(row.id))

    if (users.length === 0)
      return

    const subjects: { type: string, id: number }[] = []

    for (const subject of SUBJECTS) {
      const rows = await db.selectFrom(subject.table).select(['id']).orderBy('id').limit(500).execute()

      for (const row of rows)
        subjects.push({ type: subject.type, id: Number(row.id) })
    }

    // Nothing to react to. A database whose issues have not been seeded yet is
    // not a failure here.
    if (subjects.length === 0)
      return

    const taken = new Set(
      (await db.selectFrom('reactions').select(['subject_type', 'subject_id', 'user_id', 'content']).execute())
        .map(row => `${row.subject_type}:${row.subject_id}:${row.user_id}:${row.content}`),
    )

    const rows: Record<string, unknown>[] = []

    /*
     * Clustered rather than spread evenly, because that is how reactions
     * actually arrive: a few subjects collect most of them and the rest have
     * none. A uniform one-each would make every issue page look the same and
     * would never exercise the grouped count the issue page runs.
     *
     * The arithmetic is deliberate rather than random - stepping the user and
     * the content by coprime offsets walks distinct combinations instead of
     * hoping not to repeat one, so this cannot fail on its own unique index.
     */
    for (let index = 0; index < subjects.length && rows.length < wanted; index += 1) {
      const subject = subjects[index]!
      const many = (index % 5) + 1

      for (let n = 0; n < many && rows.length < wanted; n += 1) {
        const user = users[(index * 7 + n * 13) % users.length]!
        const content = CONTENT[(index + n * 3) % CONTENT.length]!
        const key = `${subject.type}:${subject.id}:${user}:${content}`

        if (taken.has(key))
          continue

        taken.add(key)

        rows.push({
          subject_type: subject.type,
          subject_id: subject.id,
          user_id: user,
          content,
          // `useUuid` is on the model, and nothing fills it for a direct insert.
          uuid: crypto.randomUUID(),
          // `created_at` is left to its default in both dialects, deliberately:
          // an ISO-8601 string is what MySQL refuses for a `datetime`, and two
          // e2e suites were standing down on exactly that.
        })
      }
    }

    if (rows.length === 0)
      return

    await db.insertInto('reactions').values(rows as any).execute()

    console.error(`[seed] ${rows.length} reaction(s) across ${new Set(rows.map(row => `${row.subject_type}:${row.subject_id}`)).size} subject(s)`)
  }
}
