// Generated by bun-plugin-auto-imports
//
// Name to file, relative to this file. The resolvers read it, and the name
// types are `keyof` over it - so a name that type-checks is a name that
// resolves. Values are paths rather than import thunks on purpose: thunks
// would make every compilation that touches a name resolve every module.
export const listeners = {
  'Console': '../../../app/Listeners/Console.ts',
  'DispatchPullRequestRuns': '../../../app/Listeners/DispatchPullRequestRuns.ts',
  'DispatchSubjectRuns': '../../../app/Listeners/DispatchSubjectRuns.ts',
  'DispatchWebhooks': '../../../app/Listeners/DispatchWebhooks.ts',
  'ExpirePreviews': '../../../app/Listeners/ExpirePreviews.ts',
  'MirrorFailed': '../../../app/Listeners/MirrorFailed.ts',
  'MirrorMetadataFailed': '../../../app/Listeners/MirrorMetadataFailed.ts',
  'MirrorMetadataSynced': '../../../app/Listeners/MirrorMetadataSynced.ts',
  'MirrorSynced': '../../../app/Listeners/MirrorSynced.ts',
  'Notify': '../../../app/Listeners/Notify.ts',
  'RecordActivity': '../../../app/Listeners/RecordActivity.ts',
  'RecordAudit': '../../../app/Listeners/RecordAudit.ts',
  'SyncWorkflows': '../../../app/Listeners/SyncWorkflows.ts',
} as const
