-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflow_notification_rules` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `user_id` bigint not null,
  `workflow` varchar(200) default '*',
  `branch` varchar(200) default '*',
  `job_key` varchar(200) default '',
  `condition` ENUM('failure', 'success', 'recovery', 'always') default 'failure',
  `created_by_id` integer,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `workflow_notification_rules_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`),
  CONSTRAINT `workflow_notification_rules_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `workflow_notification_rules_repository_index` ON `workflow_notification_rules` (`repository_id`);
CREATE UNIQUE INDEX `workflow_notification_rules_unique` ON `workflow_notification_rules` (`repository_id`, `user_id`, `workflow`, `branch`, `job_key`, `condition`);
CREATE UNIQUE INDEX `workflow_notification_rules_uuid_unique` ON `workflow_notification_rules` (`uuid`);
