-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `release_assets` (
  `id` bigint PRIMARY KEY auto_increment,
  `release_id` bigint not null,
  `name` varchar(255) not null,
  `storage_path` varchar(500) not null,
  `content_type` varchar(160) default 'application/octet-stream',
  `size_bytes` integer default 0,
  `checksum` varchar(64),
  `download_count` integer default 0,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `release_assets_release_id_fk` FOREIGN KEY (`release_id`) REFERENCES `releases`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `release_assets_release_name_index` ON `release_assets` (`release_id`, `name`);
