-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `gpg_keys` (
  `id` bigint PRIMARY KEY auto_increment,
  `user_id` bigint not null,
  `key_id` varchar(64) not null,
  `public_key` text not null,
  `emails` text,
  `expires_at` varchar(255),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `gpg_keys_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `gpg_keys_key_id_index` ON `gpg_keys` (`key_id`);
CREATE UNIQUE INDEX `gpg_keys_key_id_unique` ON `gpg_keys` (`key_id`);
