-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `timeline_entries` (
  `id` bigint PRIMARY KEY auto_increment,
  `subject_type` ENUM('issue', 'pull_request') default 'issue',
  `subject_id` integer not null,
  `kind` ENUM('closed', 'reopened', 'renamed', 'labeled', 'unlabeled', 'assigned', 'unassigned', 'milestoned', 'demilestoned', 'locked', 'unlocked', 'referenced', 'mentioned', 'merged'),
  `actor_id` bigint,
  `external_actor` varchar(120),
  `subject_text` varchar(255),
  `previous_text` varchar(255),
  `reference_number` integer,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `timeline_entries_actor_id_fk` FOREIGN KEY (`actor_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `timeline_entries_subject_index` ON `timeline_entries` (`subject_type`, `subject_id`, `created_at`);
CREATE UNIQUE INDEX `timeline_entries_uuid_unique` ON `timeline_entries` (`uuid`);
