-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `push_subscriptions` (
  `id` bigint PRIMARY KEY auto_increment,
  `endpoint` text not null,
  `public_key` varchar(255) not null,
  `auth_secret` varchar(255) not null,
  `user_agent` varchar(500),
  `last_seen_at` datetime,
  `user_id` bigint,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `push_subscriptions_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `push_subscriptions_endpoint_unique` ON `push_subscriptions` (`endpoint`(255));
