-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `repo_collaborators` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `user_id` bigint not null,
  `permission` ENUM('read', 'triage', 'write', 'maintain', 'admin') default 'read',
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `repo_collaborators_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE,
  CONSTRAINT `repo_collaborators_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `repo_collaborators_repo_user_index` ON `repo_collaborators` (`repository_id`, `user_id`);
