-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `team_members` (
  `id` bigint PRIMARY KEY auto_increment,
  `team_id` bigint not null,
  `user_id` bigint not null,
  `role` ENUM('maintainer', 'member') default 'member',
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `team_members_team_id_fk` FOREIGN KEY (`team_id`) REFERENCES `teams`(`id`) ON DELETE CASCADE,
  CONSTRAINT `team_members_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `team_members_team_user_index` ON `team_members` (`team_id`, `user_id`);
