-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `instance_settings` (
  `id` bigint PRIMARY KEY auto_increment,
  `key` varchar(60) not null,
  `value` text,
  `updated_by_id` integer,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `instance_settings_key_unique` ON `instance_settings` (`key`);
