-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `pages_sites` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `enabled` boolean default false,
  `source_branch` varchar(255) default '',
  `domain` varchar(255),
  `visibility` enum('public', 'repository') default 'repository',
  `live_artifact_id` bigint,
  `live_run_id` bigint,
  `live_sha` varchar(64) default '',
  `live_at` datetime,
  `last_error` varchar(500) default '',
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `pages_sites_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE,
  CONSTRAINT `pages_sites_live_artifact_id_fk` FOREIGN KEY (`live_artifact_id`) REFERENCES `workflow_artifacts`(`id`) ON DELETE SET NULL,
  CONSTRAINT `pages_sites_live_run_id_fk` FOREIGN KEY (`live_run_id`) REFERENCES `workflow_runs`(`id`) ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `pages_sites_repository_index` ON `pages_sites` (`repository_id`);
CREATE UNIQUE INDEX `pages_sites_domain_index` ON `pages_sites` (`domain`);
CREATE UNIQUE INDEX `pages_sites_uuid_unique` ON `pages_sites` (`uuid`);
