-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `coverage_files` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `commit_sha` varchar(40) not null,
  `path` text not null,
  `uncovered_lines` text,
  `covered_lines` text,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `coverage_files_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `coverage_files_repo_sha_path_index` ON `coverage_files` (`repository_id`, `commit_sha`, `path`(255));
CREATE INDEX `coverage_files_repo_sha_index` ON `coverage_files` (`repository_id`, `commit_sha`);
