-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `review_drafts` (
  `id` bigint PRIMARY KEY auto_increment,
  `pull_request_id` bigint not null,
  `author_id` bigint not null,
  `path` text not null,
  `side` ENUM('left', 'right') default 'right',
  `from_line` integer not null,
  `to_line` integer not null,
  `body` text not null,
  `repository_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `review_drafts_pull_request_id_fk` FOREIGN KEY (`pull_request_id`) REFERENCES `pull_requests`(`id`) ON DELETE CASCADE,
  CONSTRAINT `review_drafts_author_id_fk` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `review_drafts_repository_index` ON `review_drafts` (`repository_id`);
CREATE UNIQUE INDEX `review_drafts_pr_author_index` ON `review_drafts` (`pull_request_id`, `author_id`);
