-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `pull_request_reviewers` (
  `id` bigint PRIMARY KEY auto_increment,
  `pull_request_id` bigint not null,
  `reviewer_type` ENUM('user', 'team') default 'user',
  `reviewer_id` integer not null,
  `requested_by_id` bigint,
  `from_code_owners` tinyint(1) default 0,
  `responded_at` varchar(255),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `pull_request_reviewers_pull_request_id_fk` FOREIGN KEY (`pull_request_id`) REFERENCES `pull_requests`(`id`),
  CONSTRAINT `pull_request_reviewers_requested_by_id_fk` FOREIGN KEY (`requested_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `pull_request_reviewers_pr_reviewers_pr_index` ON `pull_request_reviewers` (`pull_request_id`);
