-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `repository_labels` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `name` varchar(50) not null,
  `color` varchar(6) not null default 'd4c5f9',
  `description` varchar(255),
  `is_default` tinyint(1) default 0,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `repository_labels_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `repository_labels_repository_name_index` ON `repository_labels` (`repository_id`, `name`);
CREATE UNIQUE INDEX `repository_labels_uuid_unique` ON `repository_labels` (`uuid`);
