-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `managed_tests` (
  `id` bigint PRIMARY KEY auto_increment,
  `test_suite_id` bigint not null,
  `scope` varchar(500) default '',
  `name` varchar(500) not null,
  `state` ENUM('enabled', 'muted', 'skipped') default 'enabled',
  `muted_by_id` integer,
  `muted_at` varchar(40),
  `muted_reason` text,
  `review_at` varchar(40),
  `owner` varchar(200),
  `flaky` tinyint(1) default 0,
  `flaky_reason` varchar(500),
  `flaky_since` varchar(40),
  `repository_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `managed_tests_test_suite_id_fk` FOREIGN KEY (`test_suite_id`) REFERENCES `test_suites`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `managed_tests_repository_index` ON `managed_tests` (`repository_id`);
CREATE UNIQUE INDEX `managed_tests_identity_index` ON `managed_tests` (`test_suite_id`, `scope`(255), `name`);
CREATE INDEX `managed_tests_state_index` ON `managed_tests` (`test_suite_id`, `state`);
CREATE UNIQUE INDEX `managed_tests_uuid_unique` ON `managed_tests` (`uuid`);
