-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `runner_pool_maintainers` (
  `id` bigint PRIMARY KEY auto_increment,
  `runner_pool_id` bigint not null,
  `user_id` bigint not null,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `runner_pool_maintainers_runner_pool_id_fk` FOREIGN KEY (`runner_pool_id`) REFERENCES `runner_pools`(`id`) ON DELETE CASCADE,
  CONSTRAINT `runner_pool_maintainers_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `runner_pool_maintainers_pool_index` ON `runner_pool_maintainers` (`runner_pool_id`);
CREATE INDEX `runner_pool_maintainers_user_index` ON `runner_pool_maintainers` (`user_id`);
