-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `attachments` (
  `id` bigint PRIMARY KEY auto_increment,
  `key` varchar(64) not null,
  `repository_id` bigint not null,
  `uploader_id` bigint,
  `filename` varchar(255) not null,
  `content_type` varchar(100) not null,
  `byte_size` integer not null,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `attachments_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE,
  CONSTRAINT `attachments_uploader_id_fk` FOREIGN KEY (`uploader_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `attachments_key_index` ON `attachments` (`key`);
CREATE INDEX `attachments_repository_index` ON `attachments` (`repository_id`);
CREATE UNIQUE INDEX `attachments_key_unique` ON `attachments` (`key`);
CREATE UNIQUE INDEX `attachments_uuid_unique` ON `attachments` (`uuid`);
