-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `deploy_keys` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `title` varchar(100) not null,
  `key_type` varchar(32) not null,
  `public_key` text not null,
  `fingerprint` varchar(100) not null,
  `can_write` tinyint(1) default 0,
  `last_used_at` varchar(255),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `deploy_keys_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `deploy_keys_fingerprint_index` ON `deploy_keys` (`fingerprint`);
CREATE INDEX `deploy_keys_repository_index` ON `deploy_keys` (`repository_id`);
