-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `instance_keys` (
  `id` bigint PRIMARY KEY auto_increment,
  `purpose` varchar(40) not null default 'oidc',
  `kid` varchar(64) not null,
  `algorithm` varchar(20) default 'RS256',
  `public_jwk` text,
  `sealed_private` text,
  `retired_at` varchar(40),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `instance_keys_kid_index` ON `instance_keys` (`kid`);
CREATE INDEX `instance_keys_purpose_index` ON `instance_keys` (`purpose`, `retired_at`);
