-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `test_suites` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `name` varchar(100) not null,
  `slug` varchar(100) not null,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `test_suites_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `test_suites_repository_index` ON `test_suites` (`repository_id`, `slug`);
CREATE UNIQUE INDEX `test_suites_uuid_unique` ON `test_suites` (`uuid`);
