-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `review_checkpoints` (
  `id` bigint PRIMARY KEY auto_increment,
  `pull_request_id` bigint not null,
  `reviewer_id` bigint not null,
  `head_sha` varchar(40) not null,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `review_checkpoints_pull_request_id_fk` FOREIGN KEY (`pull_request_id`) REFERENCES `pull_requests`(`id`) ON DELETE CASCADE,
  CONSTRAINT `review_checkpoints_reviewer_id_fk` FOREIGN KEY (`reviewer_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `review_checkpoints_pr_user_index` ON `review_checkpoints` (`pull_request_id`, `reviewer_id`);
