-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflow_variables` (
  `id` bigint PRIMARY KEY auto_increment,
  `scope_type` ENUM('instance', 'owner', 'repository') default 'repository',
  `scope_id` integer default 0,
  `key` varchar(200) not null,
  `value` text default (''),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `workflow_variables_scope_index` ON `workflow_variables` (`scope_type`, `scope_id`, `key`);
CREATE UNIQUE INDEX `workflow_variables_uuid_unique` ON `workflow_variables` (`uuid`);
