-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `check_runs` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `head_sha` varchar(40) not null,
  `name` varchar(255) not null,
  `status` ENUM('queued', 'in_progress', 'completed') default 'queued',
  `conclusion` ENUM('success', 'failure', 'neutral', 'cancelled', 'timed_out', 'action_required', 'skipped', 'stale'),
  `details_url` text,
  `summary` text,
  `started_at` varchar(255),
  `completed_at` varchar(255),
  `reporter_id` integer,
  `provider` varchar(100),
  `external_id` varchar(255),
  `idempotency_key` varchar(255),
  `output_title` varchar(255),
  `output_text` text,
  `attempt` integer default 1,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `check_runs_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `check_runs_head_index` ON `check_runs` (`repository_id`, `head_sha`);
CREATE INDEX `check_runs_name_index` ON `check_runs` (`repository_id`, `name`);
CREATE UNIQUE INDEX `check_runs_idempotency_index` ON `check_runs` (`idempotency_key`);
CREATE UNIQUE INDEX `check_runs_uuid_unique` ON `check_runs` (`uuid`);
