-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `notification_schedules` (
  `id` bigint PRIMARY KEY auto_increment,
  `user_id` bigint not null,
  `days` varchar(20) default '1,2,3,4,5',
  `starts_at` integer default 540,
  `ends_at` integer default 1080,
  `timezone` varchar(64) default 'UTC',
  `breaks_through` varchar(500) default '',
  `do_not_disturb_until` varchar(255),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `notification_schedules_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `notification_schedules_user_index` ON `notification_schedules` (`user_id`);
