-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `run_metadata` (
  `id` bigint PRIMARY KEY auto_increment,
  `workflow_run_id` bigint not null,
  `key` varchar(200) not null,
  `value` text,
  `version` integer default 1,
  `updated_by_job_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `run_metadata_workflow_run_id_fk` FOREIGN KEY (`workflow_run_id`) REFERENCES `workflow_runs`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `run_metadata_key_index` ON `run_metadata` (`workflow_run_id`, `key`);
