-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflow_run_events` (
  `id` bigint PRIMARY KEY auto_increment,
  `workflow_run_id` bigint not null,
  `name` varchar(200) not null,
  `payload` text,
  `idempotency_key` varchar(200) not null,
  `actor_id` integer,
  `source` varchar(30) default 'api',
  `delivered_to` integer default 0,
  `repository_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `workflow_run_events_workflow_run_id_fk` FOREIGN KEY (`workflow_run_id`) REFERENCES `workflow_runs`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `workflow_run_events_key_index` ON `workflow_run_events` (`idempotency_key`);
CREATE INDEX `workflow_run_events_run_index` ON `workflow_run_events` (`workflow_run_id`, `name`);
CREATE INDEX `workflow_run_events_repository_index` ON `workflow_run_events` (`repository_id`);
