-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `runners` (
  `id` bigint PRIMARY KEY auto_increment,
  `runner_queue_id` bigint,
  `stop_requested` ENUM('graceful', 'forced'),
  `tags` text,
  `runner_registration_token_id` bigint,
  `name` varchar(200) not null,
  `scope_type` ENUM('instance', 'organization', 'repository') default 'instance',
  `scope_id` integer,
  `token_hash` varchar(64) not null,
  `labels` text,
  `state` ENUM('active', 'disabled') default 'active',
  `version` varchar(60),
  `last_seen_at` varchar(40),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `runners_runner_queue_id_fk` FOREIGN KEY (`runner_queue_id`) REFERENCES `runner_queues`(`id`),
  CONSTRAINT `runners_runner_registration_token_id_fk` FOREIGN KEY (`runner_registration_token_id`) REFERENCES `runner_registration_tokens`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `runners_token_index` ON `runners` (`token_hash`);
CREATE INDEX `runners_scope_index` ON `runners` (`scope_type`, `scope_id`, `state`);
CREATE UNIQUE INDEX `runners_uuid_unique` ON `runners` (`uuid`);
