-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `notification_mutes` (
  `id` bigint PRIMARY KEY auto_increment,
  `user_id` bigint not null,
  `subject_type` ENUM('repository', 'organization', 'issue', 'pull_request'),
  `subject_id` integer not null,
  `expires_at` varchar(255),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `notification_mutes_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `notification_mutes_user_index` ON `notification_mutes` (`user_id`);
CREATE INDEX `notification_mutes_subject_index` ON `notification_mutes` (`subject_type`, `subject_id`);
