-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `check_annotations` (
  `id` bigint PRIMARY KEY auto_increment,
  `check_run_id` bigint not null,
  `path` text not null,
  `start_line` integer not null,
  `end_line` integer not null,
  `side` ENUM('left', 'right') default 'right',
  `level` ENUM('notice', 'warning', 'failure') default 'warning',
  `title` varchar(255),
  `message` text not null,
  `raw_details` text,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `check_annotations_check_run_id_fk` FOREIGN KEY (`check_run_id`) REFERENCES `check_runs`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `check_annotations_run_path_index` ON `check_annotations` (`check_run_id`, `path`(255));
