-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `merge_queue_entries` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `pull_request_id` bigint not null,
  `base_branch` varchar(255) default 'main',
  `state` ENUM('queued', 'testing', 'merged', 'ejected') default 'queued',
  `position` integer default 0,
  `merge_sha` varchar(64) default '',
  `workflow_run_id` integer,
  `reason` text default (''),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `merge_queue_entries_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE,
  CONSTRAINT `merge_queue_entries_pull_request_id_fk` FOREIGN KEY (`pull_request_id`) REFERENCES `pull_requests`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `merge_queue_entries_branch_index` ON `merge_queue_entries` (`repository_id`, `base_branch`, `state`);
CREATE UNIQUE INDEX `merge_queue_entries_pull_unique` ON `merge_queue_entries` (`pull_request_id`);
CREATE UNIQUE INDEX `merge_queue_entries_uuid_unique` ON `merge_queue_entries` (`uuid`);
