-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `git_refs` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `ref` varchar(255) not null,
  `sha` varchar(64) not null,
  `sequence` integer not null default 0,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `git_refs_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `git_refs_unique` ON `git_refs` (`repository_id`, `ref`);
CREATE INDEX `git_refs_repository_index` ON `git_refs` (`repository_id`);
CREATE UNIQUE INDEX `git_refs_uuid_unique` ON `git_refs` (`uuid`);
