-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `issues` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `number` integer not null,
  `title` varchar(255) not null,
  `body` text,
  `author_id` bigint,
  `state` ENUM('open', 'closed') default 'open',
  `state_reason` ENUM('completed', 'not_planned', 'duplicate'),
  `closed_at` varchar(255),
  `closed_by_id` bigint,
  `milestone_id` bigint,
  `locked` tinyint(1) default 0,
  `comments_count` integer default 0,
  `is_pull_request` tinyint(1) default 0,
  `external_author` varchar(120),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `issues_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE,
  CONSTRAINT `issues_author_id_fk` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`),
  CONSTRAINT `issues_closed_by_id_fk` FOREIGN KEY (`closed_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  CONSTRAINT `issues_milestone_id_fk` FOREIGN KEY (`milestone_id`) REFERENCES `milestones`(`id`) ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `issues_repo_number_index` ON `issues` (`repository_id`, `number`);
CREATE INDEX `issues_repo_state_index` ON `issues` (`repository_id`, `state`);
CREATE UNIQUE INDEX `issues_uuid_unique` ON `issues` (`uuid`);
