-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `protected_branches` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `pattern` varchar(255) not null,
  `required_approvals` integer default 0,
  `dismiss_stale_reviews` tinyint(1) default 0,
  `require_conversation_resolution` tinyint(1) default 0,
  `required_checks` text,
  `allow_force_push` tinyint(1) default 0,
  `allow_deletion` tinyint(1) default 0,
  `require_linear_history` tinyint(1) default 0,
  `require_human_approval_for_agents` tinyint(1) default 0,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `protected_branches_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `protected_branches_repo_index` ON `protected_branches` (`repository_id`);
