-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `atproto_auth_requests` (
  `id` bigint PRIMARY KEY auto_increment,
  `state` varchar(120) not null,
  `did` varchar(255) not null,
  `handle` varchar(253),
  `issuer` varchar(255) not null,
  `token_endpoint` varchar(500) not null,
  `verifier` varchar(255) not null,
  `sealed_key` text not null,
  `nonce` varchar(500),
  `user_id` bigint,
  `expires_at` varchar(40) not null,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `atproto_auth_requests_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `atproto_auth_requests_state_index` ON `atproto_auth_requests` (`state`);
CREATE INDEX `atproto_auth_requests_expiry_index` ON `atproto_auth_requests` (`expires_at`);
