-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `issue_comments` (
  `id` bigint PRIMARY KEY auto_increment,
  `commentable_type` ENUM('issue', 'pull_request') default 'issue',
  `commentable_id` integer not null,
  `author_id` bigint,
  `body` text not null,
  `edited_at` varchar(255),
  `edited_by_id` integer,
  `external_author` varchar(120),
  `external_id` varchar(120),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `issue_comments_author_id_fk` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `issue_comments_subject_index` ON `issue_comments` (`commentable_type`, `commentable_id`);
CREATE INDEX `issue_comments_external_index` ON `issue_comments` (`external_id`);
CREATE UNIQUE INDEX `issue_comments_uuid_unique` ON `issue_comments` (`uuid`);
