-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `environment_reviewers` (
  `id` bigint PRIMARY KEY auto_increment,
  `environment_id` bigint not null,
  `user_id` bigint not null,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `environment_reviewers_environment_id_fk` FOREIGN KEY (`environment_id`) REFERENCES `environments`(`id`) ON DELETE CASCADE,
  CONSTRAINT `environment_reviewers_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `environment_reviewers_unique` ON `environment_reviewers` (`environment_id`, `user_id`);
CREATE UNIQUE INDEX `environment_reviewers_uuid_unique` ON `environment_reviewers` (`uuid`);
