-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflow_journal_entries` (
  `id` bigint PRIMARY KEY auto_increment,
  `workflow_run_id` bigint not null,
  `sequence` integer not null,
  `kind` varchar(30) not null default 'step',
  `identity` varchar(64) not null,
  `name` varchar(200),
  `state` varchar(20) not null default 'pending',
  `result` text,
  `error` text,
  `workflow_job_id` integer,
  `wake_at` varchar(255),
  `duration_ms` integer,
  `repository_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `workflow_journal_entries_workflow_run_id_fk` FOREIGN KEY (`workflow_run_id`) REFERENCES `workflow_runs`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `workflow_journal_entries_sequence_index` ON `workflow_journal_entries` (`workflow_run_id`, `sequence`);
CREATE INDEX `workflow_journal_entries_run_index` ON `workflow_journal_entries` (`workflow_run_id`);
