-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `review_comments` (
  `id` bigint PRIMARY KEY auto_increment,
  `review_thread_id` bigint not null,
  `review_id` bigint,
  `author_id` bigint,
  `body` text not null,
  `suggestion` text,
  `edited_at` varchar(255),
  `external_id` integer,
  `external_author` varchar(120),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `review_comments_review_thread_id_fk` FOREIGN KEY (`review_thread_id`) REFERENCES `review_threads`(`id`),
  CONSTRAINT `review_comments_review_id_fk` FOREIGN KEY (`review_id`) REFERENCES `pull_request_reviews`(`id`),
  CONSTRAINT `review_comments_author_id_fk` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `review_comments_thread_index` ON `review_comments` (`review_thread_id`);
CREATE INDEX `review_comments_external_index` ON `review_comments` (`external_id`);
CREATE UNIQUE INDEX `review_comments_uuid_unique` ON `review_comments` (`uuid`);
