-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `runner_queues` (
  `id` bigint PRIMARY KEY auto_increment,
  `runner_pool_id` bigint not null,
  `name` varchar(100) not null,
  `state` ENUM('active', 'paused') default 'active',
  `paused_reason` varchar(500),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `runner_queues_runner_pool_id_fk` FOREIGN KEY (`runner_pool_id`) REFERENCES `runner_pools`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `runner_queues_pool_index` ON `runner_queues` (`runner_pool_id`, `state`);
CREATE INDEX `runner_queues_name_index` ON `runner_queues` (`name`);
CREATE UNIQUE INDEX `runner_queues_uuid_unique` ON `runner_queues` (`uuid`);
