-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `atproto_identities` (
  `id` bigint PRIMARY KEY auto_increment,
  `user_id` bigint not null,
  `did` varchar(255) not null,
  `handle` varchar(253),
  `pds` varchar(255),
  `last_verified_at` varchar(40),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `atproto_identities_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `atproto_identities_did_index` ON `atproto_identities` (`did`);
CREATE INDEX `atproto_identities_user_index` ON `atproto_identities` (`user_id`);
CREATE UNIQUE INDEX `atproto_identities_uuid_unique` ON `atproto_identities` (`uuid`);
