-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflow_version_steps` (
  `id` bigint PRIMARY KEY auto_increment,
  `workflow_version_job_id` bigint not null,
  `position` integer default 0,
  `step_id` varchar(100),
  `name` varchar(200),
  `command` text,
  `uses` varchar(400),
  `inputs` text,
  `env` text,
  `shell` varchar(200),
  `continue_on_error` tinyint(1) default 0,
  `timeout_minutes` integer,
  `working_directory` varchar(400),
  `condition` text,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `workflow_version_steps_workflow_version_job_id_fk` FOREIGN KEY (`workflow_version_job_id`) REFERENCES `workflow_version_jobs`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `workflow_version_steps_job_index` ON `workflow_version_steps` (`workflow_version_job_id`, `position`);
