-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `commit_statuses` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `sha` varchar(64) not null,
  `context` varchar(255) not null,
  `state` ENUM('pending', 'success', 'failure', 'error'),
  `target_url` text,
  `description` varchar(500),
  `creator_id` integer,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `commit_statuses_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `commit_statuses_sha_index` ON `commit_statuses` (`repository_id`, `sha`);
