-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `queue_circuit_state` (
  `id` bigint PRIMARY KEY auto_increment,
  `queue_name` varchar(255) not null,
  `success_count` integer default 0,
  `failure_count` integer default 0,
  `window_start` varchar(32),
  `paused_at` varchar(32),
  `resume_at` varchar(32),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `queue_circuit_state_queue_index` ON `queue_circuit_state` (`queue_name`);
