-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `repositories` (
  `id` bigint PRIMARY KEY auto_increment,
  `owner_type` ENUM('user', 'organization'),
  `owner_id` integer not null,
  `name` varchar(100) not null,
  `description` text,
  `visibility` ENUM('public', 'private', 'internal') default 'public',
  `default_branch` varchar(255) default 'main',
  `disk_path` varchar(512),
  `is_fork` tinyint(1) default 0,
  `parent_id` bigint,
  `is_archived` tinyint(1) default 0,
  `is_template` tinyint(1) default 0,
  `size_kb` integer default 0,
  `stars_count` integer default 0,
  `forks_count` integer default 0,
  `open_issues_count` integer default 0,
  `issue_counter` integer default 0,
  `pushed_at` varchar(255),
  `allow_merge_commit` tinyint(1) default 1,
  `allow_squash_merge` tinyint(1) default 1,
  `allow_rebase_merge` tinyint(1) default 1,
  `default_merge_strategy` ENUM('merge', 'squash', 'rebase') default 'merge',
  `delete_branch_on_merge` tinyint(1) default 0,
  `count_machine_approvals` tinyint(1) default 0,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `repositories_parent_id_fk` FOREIGN KEY (`parent_id`) REFERENCES `repositories`(`id`) ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `repositories_owner_name_index` ON `repositories` (`owner_type`, `owner_id`, `name`);
CREATE INDEX `repositories_pushed_at_index` ON `repositories` (`pushed_at`);
CREATE UNIQUE INDEX `repositories_uuid_unique` ON `repositories` (`uuid`);
