-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `repository_mirrors` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `direction` ENUM('pull', 'push') default 'pull',
  `provider` ENUM('github', 'gitlab', 'git') default 'github',
  `remote_url` varchar(500) not null,
  `remote_owner` varchar(120),
  `remote_name` varchar(120),
  `credential_ref` varchar(200),
  `webhook_secret` varchar(120),
  `interval_seconds` integer default 900,
  `enabled` tinyint(1) default 1,
  `allow_local_pushes` tinyint(1) default 0,
  `last_synced_at` varchar(255),
  `last_sha` varchar(64),
  `last_error` text,
  `failure_count` integer default 0,
  `sync_metadata` tinyint(1) default 0,
  `last_metadata_sync_at` varchar(255),
  `metadata_error` text,
  `metadata_failure_count` integer default 0,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `repository_mirrors_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `repository_mirrors_repository_index` ON `repository_mirrors` (`repository_id`);
CREATE INDEX `repository_mirrors_due_index` ON `repository_mirrors` (`enabled`, `last_synced_at`);
CREATE UNIQUE INDEX `repository_mirrors_uuid_unique` ON `repository_mirrors` (`uuid`);
