-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `git_wal_entries` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `sequence` integer not null,
  `updates` text not null,
  `blob_key` varchar(255),
  `blob_bytes` integer,
  `status` ENUM('pending', 'committed', 'void') not null default 'pending',
  `actor_id` integer,
  `committed_at` varchar(255),
  `reason` text,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `git_wal_entries_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `git_wal_entries_sequence_unique` ON `git_wal_entries` (`repository_id`, `sequence`);
CREATE INDEX `git_wal_entries_status_index` ON `git_wal_entries` (`status`, `created_at`);
CREATE UNIQUE INDEX `git_wal_entries_uuid_unique` ON `git_wal_entries` (`uuid`);
