-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflow_cache_entries` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `scope` varchar(255) not null,
  `cache_key` varchar(64) not null,
  `digest` varchar(64) not null,
  `blob_key` varchar(255),
  `size_bytes` integer not null default 0,
  `last_used_at` varchar(255),
  `restores` integer default 0,
  `workflow_run_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `workflow_cache_entries_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `workflow_cache_entries_key_index` ON `workflow_cache_entries` (`repository_id`, `scope`, `cache_key`);
CREATE INDEX `workflow_cache_entries_used_index` ON `workflow_cache_entries` (`last_used_at`);
CREATE INDEX `workflow_cache_entries_repository_index` ON `workflow_cache_entries` (`repository_id`);
CREATE INDEX `workflow_cache_entries_digest_index` ON `workflow_cache_entries` (`digest`);
