-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `runner_registration_tokens` (
  `id` bigint PRIMARY KEY auto_increment,
  `runner_pool_id` bigint not null,
  `name` varchar(200) not null,
  `token_hash` varchar(64) not null,
  `runner_queue_id` integer,
  `first_used_at` varchar(40),
  `last_used_at` varchar(40),
  `uses` integer default 0,
  `revoked_at` varchar(40),
  `expires_at` varchar(40),
  `created_by_id` integer,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `runner_registration_tokens_runner_pool_id_fk` FOREIGN KEY (`runner_pool_id`) REFERENCES `runner_pools`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `runner_registration_tokens_hash_index` ON `runner_registration_tokens` (`token_hash`);
CREATE INDEX `runner_registration_tokens_pool_index` ON `runner_registration_tokens` (`runner_pool_id`);
CREATE UNIQUE INDEX `runner_registration_tokens_uuid_unique` ON `runner_registration_tokens` (`uuid`);
