-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `access_tokens` (
  `id` bigint PRIMARY KEY auto_increment,
  `user_id` bigint not null,
  `name` varchar(100) not null,
  `prefix` varchar(32) not null,
  `token_hash` varchar(64) not null,
  `selection` ENUM('all', 'organization', 'selected') default 'selected',
  `organization_id` bigint,
  `expires_at` varchar(255) not null,
  `last_used_at` varchar(255),
  `last_used_ip` varchar(45),
  `revoked_at` varchar(255),
  `revoked_by_id` bigint,
  `expiry_warned_days` integer,
  `limit_pull_requests_per_hour` integer,
  `limit_comments_per_hour` integer,
  `limit_reviews_per_hour` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `access_tokens_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`),
  CONSTRAINT `access_tokens_organization_id_fk` FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON DELETE CASCADE,
  CONSTRAINT `access_tokens_revoked_by_id_fk` FOREIGN KEY (`revoked_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `access_tokens_prefix_index` ON `access_tokens` (`prefix`);
CREATE INDEX `access_tokens_user_index` ON `access_tokens` (`user_id`);
CREATE UNIQUE INDEX `access_tokens_prefix_unique` ON `access_tokens` (`prefix`);
