-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `pull_request_reviews` (
  `id` bigint PRIMARY KEY auto_increment,
  `pull_request_id` bigint not null,
  `reviewer_id` bigint,
  `state` ENUM('pending', 'approved', 'changes_requested', 'commented', 'dismissed') default 'pending',
  `body` text,
  `commit_sha` varchar(40),
  `submitted_at` varchar(255),
  `dismissed_reason` text,
  `external_author` varchar(120),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `pull_request_reviews_pull_request_id_fk` FOREIGN KEY (`pull_request_id`) REFERENCES `pull_requests`(`id`),
  CONSTRAINT `pull_request_reviews_reviewer_id_fk` FOREIGN KEY (`reviewer_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `pull_request_reviews_pr_reviews_pr_index` ON `pull_request_reviews` (`pull_request_id`);
CREATE INDEX `pull_request_reviews_pr_reviews_reviewer_index` ON `pull_request_reviews` (`pull_request_id`, `reviewer_id`);
