-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `watches` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `user_id` bigint not null,
  `subscription` ENUM('all', 'participating', 'ignore') default 'participating',
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `watches_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE,
  CONSTRAINT `watches_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `watches_repo_user_index` ON `watches` (`repository_id`, `user_id`);
