-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `review_threads` (
  `id` bigint PRIMARY KEY auto_increment,
  `pull_request_id` bigint not null,
  `path` text not null,
  `line` integer,
  `start_line` integer,
  `side` ENUM('left', 'right') default 'right',
  `original_line` integer,
  `original_commit_sha` varchar(40),
  `resolved` tinyint(1) default 0,
  `resolved_by_id` bigint,
  `outdated` tinyint(1) default 0,
  `external_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `review_threads_pull_request_id_fk` FOREIGN KEY (`pull_request_id`) REFERENCES `pull_requests`(`id`),
  CONSTRAINT `review_threads_resolved_by_id_fk` FOREIGN KEY (`resolved_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `review_threads_pr_index` ON `review_threads` (`pull_request_id`);
CREATE INDEX `review_threads_path_index` ON `review_threads` (`pull_request_id`, `path`(255));
CREATE INDEX `review_threads_external_index` ON `review_threads` (`external_id`);
