-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `milestones` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `title` varchar(255) not null,
  `description` text,
  `due_on` varchar(255),
  `state` ENUM('open', 'closed') default 'open',
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `milestones_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `milestones_repo_index` ON `milestones` (`repository_id`);
