-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflow_steps` (
  `id` bigint PRIMARY KEY auto_increment,
  `workflow_job_id` bigint not null,
  `position` integer default 0,
  `name` varchar(200),
  `command` text,
  `uses` varchar(500),
  `inputs` text,
  `env` text,
  `working_directory` varchar(500),
  `shell` varchar(100),
  `condition` text,
  `step_id` varchar(100),
  `continue_on_error` tinyint(1) default 0,
  `timeout_minutes` integer,
  `state` ENUM('pending', 'running', 'cancelled', 'failed', 'skipped', 'succeeded') default 'pending',
  `attempts` integer default 0,
  `exit_code` integer,
  `started_at` varchar(40),
  `finished_at` varchar(40),
  `outputs` text,
  `error` text,
  `reused_from_attempt` integer,
  `queued_ms` integer,
  `active_ms` integer,
  `repository_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `workflow_steps_workflow_job_id_fk` FOREIGN KEY (`workflow_job_id`) REFERENCES `workflow_jobs`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `workflow_steps_repository_index` ON `workflow_steps` (`repository_id`);
CREATE INDEX `workflow_steps_job_index` ON `workflow_steps` (`workflow_job_id`, `position`);
