-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `ssh_keys` (
  `id` bigint PRIMARY KEY auto_increment,
  `user_id` bigint not null,
  `title` varchar(100) not null,
  `key_type` ENUM('ssh-ed25519', 'ssh-rsa', 'ecdsa-sha2-nistp256'),
  `public_key` text not null,
  `fingerprint` varchar(100) not null,
  `last_used_at` varchar(255),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `ssh_keys_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `ssh_keys_fingerprint_index` ON `ssh_keys` (`fingerprint`);
CREATE UNIQUE INDEX `ssh_keys_fingerprint_unique` ON `ssh_keys` (`fingerprint`);
