-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `repository_languages` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `language` varchar(60) not null,
  `bytes` integer not null,
  `percent` integer,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `repository_languages_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `repository_languages_repo_index` ON `repository_languages` (`repository_id`, `bytes`);
CREATE INDEX `repository_languages_language_index` ON `repository_languages` (`language`, `bytes`);
