-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `reactions` (
  `id` bigint PRIMARY KEY auto_increment,
  `subject_type` ENUM('issue', 'issue_comment', 'review_comment') default 'issue',
  `subject_id` integer not null,
  `user_id` bigint not null,
  `content` ENUM('+1', '-1', 'laugh', 'hooray', 'confused', 'heart', 'rocket', 'eyes') not null,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `reactions_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `reactions_subject_index` ON `reactions` (`subject_type`, `subject_id`);
CREATE UNIQUE INDEX `reactions_one_per_person_index` ON `reactions` (`subject_type`, `subject_id`, `user_id`, `content`);
CREATE UNIQUE INDEX `reactions_uuid_unique` ON `reactions` (`uuid`);
