-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` bigint PRIMARY KEY auto_increment,
  `connection` varchar(100),
  `queue` varchar(100),
  `payload` text,
  `exception` text,
  `failed_at` varchar(255),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `failed_jobs_queue_index` ON `failed_jobs` (`queue`, `failed_at`);
