-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `issue_assignees` (
  `id` bigint PRIMARY KEY auto_increment,
  `issue_id` bigint not null,
  `user_id` bigint not null,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `issue_assignees_issue_id_fk` FOREIGN KEY (`issue_id`) REFERENCES `issues`(`id`),
  CONSTRAINT `issue_assignees_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `issue_assignees_issue_index` ON `issue_assignees` (`issue_id`, `user_id`);
