-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `notification_deliveries` (
  `id` bigint PRIMARY KEY auto_increment,
  `channel` ENUM('email', 'sms', 'chat', 'database', 'push', 'broadcast') not null,
  `recipient` text not null,
  `subject` varchar(255),
  `body` text not null,
  `status` ENUM('pending', 'sent', 'delivered', 'failed', 'skipped') not null default 'pending',
  `error` text,
  `metadata` varchar(255),
  `sent_at` datetime,
  `user_id` bigint,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `notification_deliveries_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4;
