-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `jobs` (
  `id` bigint PRIMARY KEY auto_increment,
  `queue` varchar(255) not null,
  `payload` text not null,
  `attempts` integer,
  `available_at` integer,
  `reserved_at` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime
) DEFAULT CHARSET=utf8mb4;
