-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `deployments` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `environment` varchar(120) not null,
  `head_sha` varchar(64) not null,
  `ref` varchar(255),
  `pull_request_id` bigint,
  `workflow_run_id` bigint,
  `url` varchar(500),
  `state` ENUM('in_progress', 'active', 'failed', 'inactive') default 'in_progress',
  `reason` varchar(500),
  `created_by_id` integer,
  `finished_at` varchar(255),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `deployments_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`),
  CONSTRAINT `deployments_pull_request_id_fk` FOREIGN KEY (`pull_request_id`) REFERENCES `pull_requests`(`id`),
  CONSTRAINT `deployments_workflow_run_id_fk` FOREIGN KEY (`workflow_run_id`) REFERENCES `workflow_runs`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `deployments_repository_index` ON `deployments` (`repository_id`, `environment`);
CREATE INDEX `deployments_pull_request_index` ON `deployments` (`pull_request_id`);
CREATE INDEX `deployments_state_index` ON `deployments` (`state`);
CREATE UNIQUE INDEX `deployments_uuid_unique` ON `deployments` (`uuid`);
