-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `organizations` (
  `id` bigint PRIMARY KEY auto_increment,
  `handle` varchar(39) not null,
  `name` varchar(100),
  `description` text,
  `avatar_url` text,
  `website` text,
  `billing_email` varchar(255),
  `require_two_factor` tinyint(1) default 0,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `organizations_handle_index` ON `organizations` (`handle`);
CREATE UNIQUE INDEX `organizations_handle_unique` ON `organizations` (`handle`);
CREATE UNIQUE INDEX `organizations_uuid_unique` ON `organizations` (`uuid`);
