-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `team_repositories` (
  `id` bigint PRIMARY KEY auto_increment,
  `team_id` bigint not null,
  `repository_id` bigint not null,
  `permission` ENUM('read', 'triage', 'write', 'maintain', 'admin') not null default 'read',
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `team_repositories_team_id_fk` FOREIGN KEY (`team_id`) REFERENCES `teams`(`id`) ON DELETE CASCADE,
  CONSTRAINT `team_repositories_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `team_repositories_team_repo_unique` ON `team_repositories` (`team_id`, `repository_id`);
CREATE INDEX `team_repositories_repository_index` ON `team_repositories` (`repository_id`);
