-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `reviewed_files` (
  `id` bigint PRIMARY KEY auto_increment,
  `pull_request_id` bigint not null,
  `reviewer_id` bigint not null,
  `path` text not null,
  `head_sha` varchar(40),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `reviewed_files_pull_request_id_fk` FOREIGN KEY (`pull_request_id`) REFERENCES `pull_requests`(`id`) ON DELETE CASCADE,
  CONSTRAINT `reviewed_files_reviewer_id_fk` FOREIGN KEY (`reviewer_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `reviewed_files_pr_user_path_index` ON `reviewed_files` (`pull_request_id`, `reviewer_id`, `path`(255));
CREATE INDEX `reviewed_files_pr_user_index` ON `reviewed_files` (`pull_request_id`, `reviewer_id`);
