-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `password_resets` (
  `id` bigint PRIMARY KEY auto_increment,
  `email` varchar(255) not null,
  `token` varchar(255) not null,
  `expires_at` datetime,
  `created_at` datetime
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `password_resets_email_index` ON `password_resets` (`email`);
