-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflow_secrets` (
  `id` bigint PRIMARY KEY auto_increment,
  `scope_type` ENUM('instance', 'pool', 'owner', 'repository', 'environment') default 'repository',
  `scope_id` integer default 0,
  `key` varchar(200) not null,
  `sealed` text not null,
  `updated_by_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `workflow_secrets_scope_index` ON `workflow_secrets` (`scope_type`, `scope_id`, `key`);
CREATE UNIQUE INDEX `workflow_secrets_uuid_unique` ON `workflow_secrets` (`uuid`);
