-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `token_usage_windows` (
  `id` bigint PRIMARY KEY auto_increment,
  `access_token_id` bigint not null,
  `action` varchar(40) not null,
  `window_started_at` varchar(40) not null,
  `used` integer default 0,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `token_usage_windows_access_token_id_fk` FOREIGN KEY (`access_token_id`) REFERENCES `access_tokens`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `token_usage_windows_token_action_unique` ON `token_usage_windows` (`access_token_id`, `action`);
