-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` bigint PRIMARY KEY auto_increment,
  `type` varchar(255) not null,
  `data` text not null,
  `read_at` datetime,
  `user_id` bigint,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `notifications_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `notifications_uuid_unique` ON `notifications` (`uuid`);
