-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `runner_pools` (
  `id` bigint PRIMARY KEY auto_increment,
  `name` varchar(100) not null,
  `slug` varchar(100) not null,
  `require_signed_steps` tinyint(1) default 0,
  `plugins` text,
  `description` text,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `runner_pools_slug_index` ON `runner_pools` (`slug`);
CREATE UNIQUE INDEX `runner_pools_uuid_unique` ON `runner_pools` (`uuid`);
