-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `operations` (
  `id` bigint PRIMARY KEY auto_increment,
  `kind` varchar(60) not null,
  `status` ENUM('queued', 'running', 'succeeded', 'failed', 'cancelled') default 'queued',
  `subject_type` varchar(40),
  `subject_id` integer,
  `actor_id` integer,
  `access_token_id` bigint,
  `idempotency_scope` varchar(120),
  `idempotency_key` varchar(120),
  `started_at` varchar(40),
  `finished_at` varchar(40),
  `result` text,
  `error` text,
  `cancel_requested_at` varchar(40),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `operations_access_token_id_fk` FOREIGN KEY (`access_token_id`) REFERENCES `access_tokens`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `operations_subject_index` ON `operations` (`subject_type`, `subject_id`, `created_at`);
CREATE INDEX `operations_token_index` ON `operations` (`access_token_id`, `created_at`);
CREATE UNIQUE INDEX `operations_idempotency_index` ON `operations` (`idempotency_scope`, `idempotency_key`);
CREATE UNIQUE INDEX `operations_uuid_unique` ON `operations` (`uuid`);
