-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `sso_identities` (
  `id` bigint PRIMARY KEY auto_increment,
  `user_id` bigint not null,
  `issuer` varchar(255) not null,
  `subject` varchar(255) not null,
  `email` varchar(255),
  `groups` text,
  `last_seen_at` varchar(255),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `sso_identities_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `sso_identities_subject_index` ON `sso_identities` (`issuer`, `subject`);
CREATE INDEX `sso_identities_user_index` ON `sso_identities` (`user_id`);
