-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `recovery_codes` (
  `id` bigint PRIMARY KEY auto_increment,
  `user_id` bigint not null,
  `code_hash` varchar(64) not null,
  `used_at` varchar(255),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `recovery_codes_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `recovery_codes_user_index` ON `recovery_codes` (`user_id`, `used_at`);
