-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflows` (
  `id` bigint PRIMARY KEY auto_increment,
  `owner_type` ENUM('user', 'organization'),
  `owner_id` integer not null,
  `repository_id` bigint,
  `path` varchar(400),
  `name` varchar(200) not null,
  `last_scheduled_at` varchar(255),
  `state` ENUM('active', 'disabled', 'removed') default 'active',
  `selector` text,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `workflows_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `workflows_repository_index` ON `workflows` (`repository_id`, `state`);
CREATE INDEX `workflows_owner_index` ON `workflows` (`owner_type`, `owner_id`, `state`);
CREATE UNIQUE INDEX `workflows_uuid_unique` ON `workflows` (`uuid`);
