-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `webhook_deliveries` (
  `id` bigint PRIMARY KEY auto_increment,
  `webhook_id` bigint not null,
  `event` varchar(100) not null,
  `payload` text,
  `request_headers` text,
  `response_status` integer,
  `response_body` text,
  `duration_ms` integer,
  `attempt` integer default 1,
  `error` text,
  `delivered_at` varchar(255),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `webhook_deliveries_webhook_id_fk` FOREIGN KEY (`webhook_id`) REFERENCES `webhooks`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `webhook_deliveries_webhook_index` ON `webhook_deliveries` (`webhook_id`);
CREATE UNIQUE INDEX `webhook_deliveries_uuid_unique` ON `webhook_deliveries` (`uuid`);
