-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `environments` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `name` varchar(120) not null,
  `wait_minutes` integer default 0,
  `require_checks` boolean default false,
  `branches` text default (''),
  `description` varchar(500) default '',
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `environments_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `environments_name_index` ON `environments` (`repository_id`, `name`);
CREATE UNIQUE INDEX `environments_uuid_unique` ON `environments` (`uuid`);
