-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `test_monitors` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `suite` varchar(200) default '',
  `condition` ENUM('flaky', 'fail_rate', 'duration') default 'fail_rate',
  `threshold` decimal(10,2) default 0,
  `window_days` integer default 7,
  `state` ENUM('ok', 'alarm') default 'ok',
  `measurement` decimal(10,2) default 0,
  `changed_at` varchar(255),
  `evaluated_at` varchar(255),
  `enabled` tinyint(1) default 1,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `test_monitors_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `test_monitors_repository_index` ON `test_monitors` (`repository_id`, `enabled`);
CREATE UNIQUE INDEX `test_monitors_uuid_unique` ON `test_monitors` (`uuid`);
