-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `releases` (
  `id` bigint PRIMARY KEY auto_increment,
  `version` varchar(50) not null,
  `type` varchar(255),
  `status` varchar(255) not null,
  `notes` text,
  `downloads` integer,
  `author` varchar(255),
  `repository_id` bigint,
  `user_id` bigint,
  `tag_name` varchar(255),
  `target_sha` varchar(40),
  `name` varchar(255),
  `is_prerelease` tinyint(1) default 0,
  `published_at` datetime,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `releases_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE,
  CONSTRAINT `releases_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `releases_repo_tag_index` ON `releases` (`repository_id`, `tag_name`);
CREATE INDEX `releases_repo_published_index` ON `releases` (`repository_id`, `published_at`);
CREATE UNIQUE INDEX `releases_uuid_unique` ON `releases` (`uuid`);
