-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `repository_lfs_locks` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `lock_id` varchar(64) not null,
  `path` text not null,
  `owner_id` integer not null,
  `owner_name` varchar(120) not null,
  `ref` varchar(255),
  `locked_at` varchar(64) not null,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `repository_lfs_locks_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `repository_lfs_locks_repo_path_index` ON `repository_lfs_locks` (`repository_id`, `path`(255));
CREATE UNIQUE INDEX `repository_lfs_locks_lock_id_index` ON `repository_lfs_locks` (`lock_id`);
CREATE UNIQUE INDEX `repository_lfs_locks_lock_id_unique` ON `repository_lfs_locks` (`lock_id`);
