-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `forge_credentials` (
  `id` bigint PRIMARY KEY auto_increment,
  `user_id` bigint not null,
  `provider` ENUM('github', 'gitlab', 'gitea') default 'github',
  `host` varchar(255) not null default 'github.com',
  `remote_login` varchar(120),
  `sealed` text not null,
  `scopes` varchar(500),
  `last_used_at` varchar(40),
  `last_error` varchar(500),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `forge_credentials_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `forge_credentials_owner_index` ON `forge_credentials` (`user_id`, `provider`, `host`);
CREATE UNIQUE INDEX `forge_credentials_uuid_unique` ON `forge_credentials` (`uuid`);
