-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `org_members` (
  `id` bigint PRIMARY KEY auto_increment,
  `organization_id` bigint not null,
  `user_id` bigint not null,
  `role` ENUM('owner', 'admin', 'member') default 'member',
  `invited_by_id` integer,
  `joined_at` varchar(255),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `org_members_organization_id_fk` FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON DELETE CASCADE,
  CONSTRAINT `org_members_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `org_members_org_user_index` ON `org_members` (`organization_id`, `user_id`);
