-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflow_runs` (
  `id` bigint PRIMARY KEY auto_increment,
  `workflow_version_id` bigint not null,
  `repository_id` bigint not null,
  `number` integer not null default 1,
  `state` ENUM('queued', 'running', 'waiting', 'paused', 'cancelling', 'cancelled', 'failed', 'succeeded') default 'queued',
  `paused_at` varchar(40),
  `paused_by_id` integer,
  `event` varchar(40) not null,
  `event_ref` varchar(400),
  `head_sha` varchar(40),
  `changed_paths` text,
  `definition_sha` varchar(40),
  `concurrency_group` varchar(500),
  `trigger_depth` integer default 0,
  `uploads` integer default 0,
  `dispatch_inputs` text,
  `approval_state` ENUM('not-required', 'required', 'approved', 'rejected') default 'not-required',
  `approved_by` integer,
  `approved_at` varchar(40),
  `trusted` tinyint(1) default 0,
  `actor_id` integer,
  `pull_request_id` integer,
  `attempt` integer default 1,
  `started_at` varchar(40),
  `finished_at` varchar(40),
  `conclusion_reason` text,
  `request_id` varchar(120),
  `redelivery_key` varchar(64),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `workflow_runs_workflow_version_id_fk` FOREIGN KEY (`workflow_version_id`) REFERENCES `workflow_versions`(`id`) ON DELETE CASCADE,
  CONSTRAINT `workflow_runs_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `workflow_runs_repository_index` ON `workflow_runs` (`repository_id`, `id`);
CREATE INDEX `workflow_runs_state_index` ON `workflow_runs` (`state`, `id`);
CREATE UNIQUE INDEX `workflow_runs_redelivery_index` ON `workflow_runs` (`redelivery_key`);
CREATE UNIQUE INDEX `workflow_runs_uuid_unique` ON `workflow_runs` (`uuid`);
