-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `repository_contributors` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `name` varchar(200) not null,
  `email` varchar(200) not null,
  `commits` integer not null default 0,
  `user_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `repository_contributors_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `repository_contributors_repo_index` ON `repository_contributors` (`repository_id`, `commits`);
CREATE UNIQUE INDEX `repository_contributors_repo_email_index` ON `repository_contributors` (`repository_id`, `email`);
CREATE INDEX `repository_contributors_user_index` ON `repository_contributors` (`user_id`);
