-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `webhooks` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `url` text not null,
  `secret` varchar(255),
  `events` text default ('*'),
  `content_type` ENUM('application/json', 'application/x-www-form-urlencoded') default 'application/json',
  `active` tinyint(1) default 1,
  `consecutive_failures` integer default 0,
  `last_success_at` varchar(255),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `webhooks_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `webhooks_repository_index` ON `webhooks` (`repository_id`);
CREATE UNIQUE INDEX `webhooks_uuid_unique` ON `webhooks` (`uuid`);
