-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflow_job_logs` (
  `id` bigint PRIMARY KEY auto_increment,
  `workflow_job_id` bigint not null,
  `attempt` integer default 1,
  `sequence` integer not null,
  `content` text,
  `stream` ENUM('stdout', 'stderr') default 'stdout',
  `events` text,
  `repository_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `workflow_job_logs_workflow_job_id_fk` FOREIGN KEY (`workflow_job_id`) REFERENCES `workflow_jobs`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `workflow_job_logs_repository_index` ON `workflow_job_logs` (`repository_id`);
CREATE INDEX `workflow_job_logs_job_index` ON `workflow_job_logs` (`workflow_job_id`, `attempt`, `sequence`);
CREATE UNIQUE INDEX `workflow_job_logs_sequence_index` ON `workflow_job_logs` (`workflow_job_id`, `attempt`, `sequence`);
