-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `test_executions` (
  `id` bigint PRIMARY KEY auto_increment,
  `test_run_id` bigint not null,
  `managed_test_id` bigint not null,
  `result` ENUM('passed', 'failed', 'skipped') default 'passed',
  `duration_ms` integer default 0,
  `retries` integer default 0,
  `failure_message` text,
  `failure_stack` text,
  `workflow_job_id` integer,
  `tags` text,
  `repository_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `test_executions_test_run_id_fk` FOREIGN KEY (`test_run_id`) REFERENCES `test_runs`(`id`) ON DELETE CASCADE,
  CONSTRAINT `test_executions_managed_test_id_fk` FOREIGN KEY (`managed_test_id`) REFERENCES `managed_tests`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `test_executions_repository_index` ON `test_executions` (`repository_id`);
CREATE INDEX `test_executions_run_index` ON `test_executions` (`test_run_id`);
CREATE INDEX `test_executions_test_index` ON `test_executions` (`managed_test_id`, `id`);
CREATE UNIQUE INDEX `test_executions_uuid_unique` ON `test_executions` (`uuid`);
