-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `audit_events` (
  `id` bigint PRIMARY KEY auto_increment,
  `action` varchar(80) not null,
  `subject_type` varchar(40),
  `subject_id` integer,
  `actor_id` bigint,
  `access_token_id` integer,
  `organization_id` integer,
  `repository_id` integer,
  `external_actor` varchar(120),
  `reason` text,
  `detail` text,
  `user_agent` varchar(255),
  `ip_address` varchar(45),
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `audit_events_actor_id_fk` FOREIGN KEY (`actor_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `audit_events_subject_index` ON `audit_events` (`subject_type`, `subject_id`, `created_at`);
CREATE INDEX `audit_events_actor_index` ON `audit_events` (`actor_id`, `created_at`);
CREATE INDEX `audit_events_organization_index` ON `audit_events` (`organization_id`, `created_at`);
CREATE INDEX `audit_events_repository_index` ON `audit_events` (`repository_id`, `created_at`);
CREATE UNIQUE INDEX `audit_events_uuid_unique` ON `audit_events` (`uuid`);
