-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `notification_subscriptions` (
  `id` bigint PRIMARY KEY auto_increment,
  `user_id` bigint not null,
  `subject_type` ENUM('issue', 'pull_request', 'repository'),
  `subject_id` integer not null,
  `reason` ENUM('review_requested', 'assigned', 'mentioned', 'team_mention', 'author', 'participating', 'watching'),
  `unsubscribed` tinyint(1) default 0,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `notification_subscriptions_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `notification_subscriptions_subject_index` ON `notification_subscriptions` (`subject_type`, `subject_id`);
CREATE INDEX `notification_subscriptions_user_index` ON `notification_subscriptions` (`user_id`);
