-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `pull_requests` (
  `id` bigint PRIMARY KEY auto_increment,
  `repository_id` bigint not null,
  `number` integer not null,
  `title` varchar(255) not null,
  `body` text,
  `author_id` bigint,
  `state` ENUM('open', 'closed', 'merged') default 'open',
  `head_repository_id` integer,
  `head_branch` varchar(255) not null,
  `head_sha` varchar(40),
  `base_branch` varchar(255) not null default 'main',
  `base_sha` varchar(40),
  `merge_commit_sha` varchar(40),
  `merged_at` varchar(255),
  `merged_by_id` bigint,
  `draft` tinyint(1) default 0,
  `mergeable_state` ENUM('unknown', 'clean', 'dirty', 'blocked', 'behind') default 'unknown',
  `stack_parent_id` bigint,
  `additions` integer default 0,
  `deletions` integer default 0,
  `changed_files` integer default 0,
  `closed_at` varchar(255),
  `closed_by_id` integer,
  `mergeable_base_sha` varchar(40),
  `mergeable_head_sha` varchar(40),
  `mergeable_conflicts` text,
  `external_author` varchar(120),
  `auto_merge_strategy` ENUM('merge', 'squash', 'rebase'),
  `auto_merge_by_id` bigint,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `pull_requests_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE,
  CONSTRAINT `pull_requests_author_id_fk` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`),
  CONSTRAINT `pull_requests_merged_by_id_fk` FOREIGN KEY (`merged_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  CONSTRAINT `pull_requests_stack_parent_id_fk` FOREIGN KEY (`stack_parent_id`) REFERENCES `pull_requests`(`id`) ON DELETE SET NULL,
  CONSTRAINT `pull_requests_auto_merge_by_id_fk` FOREIGN KEY (`auto_merge_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `pull_requests_repo_number_index` ON `pull_requests` (`repository_id`, `number`);
CREATE INDEX `pull_requests_repo_state_index` ON `pull_requests` (`repository_id`, `state`);
CREATE INDEX `pull_requests_stack_index` ON `pull_requests` (`stack_parent_id`);
CREATE UNIQUE INDEX `pull_requests_uuid_unique` ON `pull_requests` (`uuid`);
