-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint PRIMARY KEY auto_increment,
  `handle` varchar(39) not null,
  `name` varchar(100),
  `email` varchar(255) not null,
  `password` varchar(255) not null,
  `bio` text,
  `avatar_url` text,
  `location` varchar(100),
  `website` text,
  `is_admin` tinyint(1) default 0,
  `machine_for_organization_id` integer,
  `email_verified_at` varchar(255),
  `github_username` varchar(39),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255)
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `users_handle_index` ON `users` (`handle`);
CREATE UNIQUE INDEX `users_handle_unique` ON `users` (`handle`);
CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);
CREATE UNIQUE INDEX `users_github_username_unique` ON `users` (`github_username`);
CREATE UNIQUE INDEX `users_uuid_unique` ON `users` (`uuid`);
