-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `plugin_policies` (
  `id` bigint PRIMARY KEY auto_increment,
  `scope_type` ENUM('instance', 'user', 'organization', 'pool') not null,
  `scope_id` integer,
  `allowlist` text,
  `require_pinned` tinyint(1) default 0,
  `capabilities` text,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `plugin_policies_scope_index` ON `plugin_policies` (`scope_type`, `scope_id`);
CREATE UNIQUE INDEX `plugin_policies_uuid_unique` ON `plugin_policies` (`uuid`);
