-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `activity_events` (
  `id` bigint PRIMARY KEY auto_increment,
  `actor_id` bigint not null,
  `verb` varchar(64) not null,
  `subject_type` varchar(32) not null,
  `subject_id` integer not null,
  `repository_id` bigint,
  `organization_id` integer,
  `is_public` tinyint(1) not null default 0,
  `detail` text,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  CONSTRAINT `activity_events_actor_id_fk` FOREIGN KEY (`actor_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  CONSTRAINT `activity_events_repository_id_fk` FOREIGN KEY (`repository_id`) REFERENCES `repositories`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `activity_events_actor_index` ON `activity_events` (`actor_id`, `created_at`);
CREATE INDEX `activity_events_repository_index` ON `activity_events` (`repository_id`, `created_at`);
CREATE INDEX `activity_events_subject_index` ON `activity_events` (`subject_type`, `subject_id`);
