-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflow_templates` (
  `id` bigint PRIMARY KEY auto_increment,
  `owner_type` ENUM('user', 'organization') default 'user',
  `owner_id` integer not null,
  `slug` varchar(120) not null,
  `name` varchar(200) not null,
  `description` text default (''),
  `path` varchar(500) default '.github/workflows/ci.yml',
  `source` text not null,
  `created_by_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  `uuid` varchar(255)
) DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX `workflow_templates_slug_index` ON `workflow_templates` (`owner_type`, `owner_id`, `slug`);
CREATE UNIQUE INDEX `workflow_templates_uuid_unique` ON `workflow_templates` (`uuid`);
