-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `deployment_statuses` (
  `id` bigint PRIMARY KEY auto_increment,
  `deployment_id` bigint not null,
  `state` ENUM('queued', 'in_progress', 'active', 'failed', 'inactive', 'rolled_back') not null default 'queued',
  `description` text,
  `url` varchar(500),
  `restored_deployment_id` integer,
  `actor_id` integer,
  `repository_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `deployment_statuses_deployment_id_fk` FOREIGN KEY (`deployment_id`) REFERENCES `deployments`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `deployment_statuses_deployment_index` ON `deployment_statuses` (`deployment_id`, `id`);
CREATE INDEX `deployment_statuses_repository_index` ON `deployment_statuses` (`repository_id`);
