-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `workflow_step_attempts` (
  `id` bigint PRIMARY KEY auto_increment,
  `workflow_step_id` bigint not null,
  `attempt` integer not null default 1,
  `state` ENUM('running', 'cancelled', 'failed', 'succeeded') default 'running',
  `exit_code` integer,
  `runner_id` varchar(200),
  `error` text,
  `started_at` varchar(40),
  `finished_at` varchar(40),
  `repository_id` integer,
  `created_at` datetime not null default (UTC_TIMESTAMP),
  `updated_at` datetime,
  CONSTRAINT `workflow_step_attempts_workflow_step_id_fk` FOREIGN KEY (`workflow_step_id`) REFERENCES `workflow_steps`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `workflow_step_attempts_repository_index` ON `workflow_step_attempts` (`repository_id`);
CREATE INDEX `workflow_step_attempts_step_index` ON `workflow_step_attempts` (`workflow_step_id`, `attempt`);
