-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS `teams` (
  `id` bigint PRIMARY KEY auto_increment,
  `organization_id` bigint not null,
  `name` varchar(100) not null,
  `slug` varchar(100) not null,
  `description` text,
  `parent_team_id` integer,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255),
  CONSTRAINT `teams_organization_id_fk` FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4;
CREATE INDEX `teams_org_slug_index` ON `teams` (`organization_id`, `slug`);
CREATE UNIQUE INDEX `teams_uuid_unique` ON `teams` (`uuid`);
