/* eslint-disable */
// AUTO-GENERATED by `buddy generate:db-types` — do not edit.
// Regenerate after adding/removing a model or changing its attributes.
// See stacksjs/stacks#1923.

declare module '@stacksjs/database' {
  interface DatabaseSchema {
    access_token_permissions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      access_token_id: number
      scope: "contents" | "issues" | "pull_requests" | "webhooks" | "administration" | "checks" | "actions" | "actions_logs" | "fleet" | "members" | "organization_administration" | "billing"
      level: "read" | "write" | "admin"
    }
    access_token_repositories: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      access_token_id: number
      repository_id: number
    }
    access_tokens: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      name: string
      prefix: string
      token_hash: string
      selection: "all" | "organization" | "selected"
      organization_id: number
      expires_at: string
      last_used_at: string
      last_used_ip: string
      revoked_at: string
      revoked_by_id: number
      expiry_warned_days: number
      limit_pull_requests_per_hour: number
      limit_comments_per_hour: number
      limit_reviews_per_hour: number
    }
    activities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      description: string
      subject_type: string
      subject_id: number
      causer: string
      properties: string
      ip_address: string
      user_id: number
    }
    activity_events: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      actor_id: number
      verb: string
      subject_type: string
      subject_id: number
      repository_id: number
      organization_id: number
      is_public: boolean
      detail: string
    }
    analytics_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      category: string
      path: string
      value: number
      currency: string
      properties: string
    }
    atproto_auth_requests: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      state: string
      did: string
      handle: string
      issuer: string
      token_endpoint: string
      verifier: string
      sealed_key: string
      nonce: string
      user_id: number
      expires_at: string
    }
    atproto_identities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      did: string
      handle: string
      pds: string
      last_verified_at: string
    }
    attachments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      key: string
      repository_id: number
      uploader_id: number
      filename: string
      content_type: string
      byte_size: number
    }
    audit_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      action: string
      subject_type: string
      subject_id: number
      actor_id: number
      access_token_id: number
      organization_id: number
      repository_id: number
      external_actor: string
      reason: string
      detail: string
      user_agent: string
      ip_address: string
    }
    authors: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      bio: string
      avatar: string
      user_id: number
    }
    board_columns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: string
      position: number
      card_limit: number
      color: string
    }
    boards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      icon: string
      color: string
      position: number
      archived: boolean
    }
    campaign_sends: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      campaign_id: number
      subscriber_id: number
      email_list_id: number
      status: "queued" | "sent" | "failed" | "bounced" | "complained"
      provider_message_id: string
      error: string
      sent_at: string
      opened_at: string
      clicked_at: string
    }
    campaigns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      type: "email" | "sms" | "push" | "social" | "multi-channel"
      status: "draft" | "scheduled" | "sending" | "sent" | "paused" | "cancelled" | "failed" | "active" | "completed" | "archived"
      subject: string
      template: string
      text: string
      from_name: string
      from_address: string
      email_list_id: number
      scheduled_at: string
      sent_at: string
      audience_size: number
      sent_count: number
      open_rate: number
      click_rate: number
      conversion_rate: number
      budget: number
      spent: number
      currency: string
      start_date: string
      end_date: string
    }
    card_comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      card_id: number
      user_id: number
      body: string
    }
    cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      column_id: number
      board_id: number
      title: string
      description: string
      position: number
      created_by_user_id: number
      due_date: string
      archived: boolean
      board_column_id: number
      user_id: number
    }
    cart_items: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      quantity: number
      unit_price: number
      total_price: number
      tax_rate: number
      tax_amount: number
      discount_percentage: number
      discount_amount: number
      product_name: string
      product_sku: string
      product_image: string
      notes: string
      cart_id: number
    }
    carts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: "active" | "abandoned" | "converted" | "expired"
      total_items: number
      subtotal: number
      tax_amount: number
      discount_amount: number
      total: number
      expires_at: string
      currency: string
      notes: string
      applied_coupon_id: string
      customer_id: number
      coupon_id: number
    }
    categories: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      slug: string
      image_url: string
      is_active: boolean
      parent_category_id: string
      display_order: number
    }
    categorizable_models: {
      // columns
      id: number
      category_id: number
      categorizable_id: number
      categorizable_type: string
      created_at: string
      updated_at: string | null
    }
    check_annotations: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      check_run_id: number
      path: string
      start_line: number
      end_line: number
      side: "left" | "right"
      level: "notice" | "warning" | "failure"
      title: string
      message: string
      raw_details: string
      repository_id: number
    }
    check_runs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      head_sha: string
      name: string
      status: "queued" | "in_progress" | "completed"
      conclusion: "success" | "failure" | "neutral" | "cancelled" | "timed_out" | "action_required" | "skipped" | "stale"
      details_url: string
      summary: string
      started_at: string
      completed_at: string
      reporter_id: number
      provider: string
      external_id: string
      idempotency_key: string
      output_title: string
      output_text: string
      attempt: number
    }
    comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      author_name: string
      author_email: string
      content: string
      body: string
      post_title: string
      status: "pending" | "approved" | "spam" | "trash"
      ip_address: string
      user_agent: string
      is_approved: number
      post_id: number
      user_id: number
    }
    commit_statuses: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      sha: string
      context: string
      state: "pending" | "success" | "failure" | "error"
      target_url: string
      description: string
      creator_id: number
    }
    coupons: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: string
      description: string
      status: "Active" | "Scheduled" | "Expired"
      is_active: boolean
      discount_type: "fixed_amount" | "percentage"
      discount_value: number
      min_order_amount: number
      max_discount_amount: number
      free_product_id: string
      usage_limit: number
      usage_count: number
      start_date: string
      end_date: string
      product_id: number
    }
    coverage_files: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      commit_sha: string
      path: string
      uncovered_lines: string
      covered_lines: string
    }
    customers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      total_spent: number
      last_order: string
      status: "Active" | "Inactive"
      avatar: string
      user_id: number
    }
    delivery_routes: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      driver: string
      vehicle: string
      stops: number
      delivery_time: number
      total_distance: number
      last_active: number
      driver_id: number
    }
    deploy_keys: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      title: string
      key_type: string
      public_key: string
      fingerprint: string
      can_write: boolean
      last_used_at: string
    }
    deployment_statuses: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      deployment_id: number
      state: "queued" | "in_progress" | "active" | "failed" | "inactive" | "rolled_back"
      description: string
      url: string
      restored_deployment_id: number
      actor_id: number
      repository_id: number
    }
    deployments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      environment: string
      head_sha: string
      ref: string
      pull_request_id: number
      workflow_run_id: number
      url: string
      state: "in_progress" | "active" | "failed" | "inactive"
      stages: string
      stage_index: number
      stage_held: boolean
      reason: string
      created_by_id: number
      finished_at: string
    }
    digital_deliveries: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      download_limit: number
      expiry_days: number
      requires_login: boolean
      automatic_delivery: boolean
      status: "active" | "inactive"
    }
    drivers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      phone: string
      vehicle_number: string
      license: string
      status: "active" | "on_delivery" | "on_break"
      user_id: number
    }
    email_list_subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email_list_id: number
      subscriber_id: number
      status: "subscribed" | "unsubscribed" | "pending" | "bounced"
      source: string
      subscribed_at: string
      unsubscribed_at: string
    }
    email_lists: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      description: string
      subscriber_count: number
      active_count: number
      unsubscribed_count: number
      bounced_count: number
      status: "active" | "inactive" | "archived"
      is_public: number
      double_opt_in: number
    }
    environment_reviewers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      environment_id: number
      user_id: number
      repository_id: number
    }
    environments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      name: string
      wait_minutes: number
      branches: string
      require_checks: boolean
      description: string
    }
    errors: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: string
      message: string
      stack: string
      status: number
      additional_info: string
    }
    failed_jobs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      connection: string
      queue: string
      payload: string
      exception: string
      failed_at: string
    }
    forge_credentials: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      user_id: number
      provider: "github" | "gitlab" | "gitea"
      host: string
      remote_login: string
      sealed: string
      scopes: string
      last_used_at: string
      last_error: string
    }
    gift_cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: string
      initial_balance: number
      current_balance: number
      currency: string
      status: string
      purchaser_id: string
      recipient_email: string
      recipient_name: string
      personal_message: string
      is_digital: boolean
      is_reloadable: boolean
      is_active: boolean
      expiry_date: string
      last_used_date: string
      template_id: string
      customer_id: number
    }
    git_refs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      ref: string
      sha: string
      sequence: number
    }
    git_wal_entries: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      sequence: number
      updates: string
      blob_key: string
      blob_bytes: number
      status: "pending" | "committed" | "void"
      actor_id: number
      committed_at: string
      reason: string
    }
    gpg_keys: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      key_id: string
      public_key: string
      emails: string
      expires_at: string
    }
    instance_keys: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      purpose: string
      kid: string
      algorithm: string
      public_jwk: string
      sealed_private: string
      retired_at: string
    }
    instance_settings: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      key: string
      value: string
      updated_by_id: number
    }
    issue_assignees: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      issue_id: number
      user_id: number
      repository_id: number
    }
    issue_comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      commentable_type: "issue" | "pull_request"
      commentable_id: number
      author_id: number
      body: string
      edited_at: string
      edited_by_id: number
      external_author: string
      external_id: string
    }
    issue_labels: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      issue_id: number
      label_id: number
      repository_id: number
    }
    issues: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      number: number
      title: string
      body: string
      author_id: number
      state: "open" | "closed"
      state_reason: "completed" | "not_planned" | "duplicate"
      closed_at: string
      closed_by_id: number
      milestone_id: number
      locked: boolean
      comments_count: number
      is_pull_request: boolean
      external_author: string
    }
    jobs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      queue: string
      payload: string
      attempts: number
      available_at: number
      reserved_at: number
    }
    labels: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: string
      color: string
    }
    license_keys: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      key: string
      template: "Standard License" | "Premium License" | "Enterprise License"
      expiry_date: string
      status: "active" | "inactive" | "unassigned"
      customer_id: number
      product_id: number
      order_id: number
    }
    logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      timestamp: number
      type: "warning" | "error" | "info" | "success"
      source: "file" | "cli" | "system"
      message: string
      project: string
      stacktrace: string
      file: string
    }
    loyalty_points: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      wallet_id: string
      points: number
      source: string
      source_reference_id: string
      description: string
      expiry_date: string
      is_used: boolean
    }
    loyalty_rewards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      points_required: number
      reward_type: string
      discount_percentage: number
      free_product_id: string
      is_active: boolean
      expiry_days: number
      image_url: string
      product_id: number
    }
    mail_preferences: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      mailbox: string
      account_name: string
      signature: string
      display_density: "comfortable" | "default" | "compact"
      theme: "light" | "dark" | "system"
      language: "en" | "fr" | "de" | "es" | "ja"
      default_reply_behavior: "reply" | "replyAll"
      send_and_archive: boolean
      auto_advance: "newer" | "older" | "back"
      desktop_notifications: boolean
      notification_sound: "default" | "subtle" | "none"
      notification_preview: boolean
      filters: string
      blocked_senders: string
      labels: string
      load_remote_images: boolean
      show_external_content: boolean
      vacation_enabled: boolean
      vacation_start_date: string
      vacation_end_date: string
      vacation_subject: string
      vacation_message: string
    }
    managed_tests: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      test_suite_id: number
      scope: string
      name: string
      state: "enabled" | "muted" | "skipped"
      muted_by_id: number
      muted_at: string
      muted_reason: string
      review_at: string
      owner: string
      flaky: boolean
      flaky_reason: string
      flaky_since: string
      repository_id: number
    }
    manufacturers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      manufacturer: string
      description: string
      country: string
      featured: boolean
    }
    merge_queue_entries: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      pull_request_id: number
      base_branch: string
      state: "queued" | "testing" | "merged" | "ejected"
      position: number
      merge_sha: string
      workflow_run_id: number
      reason: string
    }
    milestones: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      title: string
      description: string
      due_on: string
      state: "open" | "closed"
    }
    notification_deliveries: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      channel: "email" | "sms" | "chat" | "database" | "push" | "broadcast"
      recipient: string
      subject: string
      body: string
      status: "pending" | "sent" | "delivered" | "failed" | "skipped"
      error: string
      metadata: string
      sent_at: string
      user_id: number
    }
    notification_event_preferences: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      event: string
      channel: "in_app" | "email" | "push"
      delivery: "off" | "immediate" | "digest"
      user_id: number
    }
    notification_mutes: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      subject_type: "repository" | "organization" | "issue" | "pull_request"
      subject_id: number
      expires_at: string
    }
    notification_preferences: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      channel: string
      enabled: boolean
      category: string
    }
    notification_schedules: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      days: string
      starts_at: number
      ends_at: number
      timezone: string
      breaks_through: string
      do_not_disturb_until: string
    }
    notification_subscriptions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      subject_type: "issue" | "pull_request" | "repository"
      subject_id: number
      reason: "review_requested" | "assigned" | "mentioned" | "team_mention" | "author" | "participating" | "watching"
      unsubscribed: boolean
    }
    notifications: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      data: string
      read_at: string
      user_id: number
    }
    operations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      kind: string
      status: "queued" | "running" | "succeeded" | "failed" | "cancelled"
      subject_type: string
      subject_id: number
      actor_id: number
      access_token_id: number
      idempotency_scope: string
      idempotency_key: string
      started_at: string
      finished_at: string
      result: string
      error: string
      cancel_requested_at: string
    }
    order_idempotency: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      idempotency_key: string
      order_id: number
    }
    order_items: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      quantity: number
      price: number
      special_instructions: string
      order_id: number
      product_id: number
    }
    orders: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: string
      total_amount: number
      currency: string
      tax_amount: number
      discount_amount: number
      delivery_fee: number
      tip_amount: number
      order_type: string
      delivery_address: string
      special_instructions: string
      estimated_delivery_time: string
      applied_coupon_id: string
      customer_id: number
      coupon_id: number
    }
    org_members: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      organization_id: number
      user_id: number
      role: "owner" | "admin" | "member"
      invited_by_id: number
      joined_at: string
    }
    organizations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      handle: string
      name: string
      description: string
      avatar_url: string
      website: string
      billing_email: string
      require_two_factor: boolean
    }
    owner_aliases: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      handle: string
      owner_type: "user" | "organization"
      owner_id: number
    }
    pages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      template: string
      views: number
      published_at: string
      conversions: number
      author_id: number
    }
    pages_sites: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      enabled: boolean
      source_branch: string
      domain: string
      visibility: "public" | "repository"
      live_artifact_id: number
      live_run_id: number
      live_sha: string
      live_at: string
      last_error: string
    }
    password_resets: {
      // columns
      id: number
      email: string
      token: string
      expires_at: string
      created_at: string
    }
    payment_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      last_four: number
      brand: string
      exp_month: number
      exp_year: number
      is_default: boolean
      provider_id: string
      user_id: number
    }
    payment_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      key: string
      unit_price: number
      status: string
      image: string
      provider_id: string
    }
    payment_transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      amount: number
      type: string
      provider_id: string
      user_id: number
      payment_method_id: number
    }
    payments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: number
      method: "cash" | "creditCard" | "debitCard" | "paypal" | "applePay" | "googlePay" | "bankTransfer" | "giftCard"
      status: "pending" | "processing" | "completed" | "failed" | "refunded" | "partiallyRefunded" | "succeeded"
      currency: string
      reference_number: string
      card_last_four: string
      card_brand: string
      billing_email: string
      transaction_id: string
      payment_provider: string
      refund_amount: number
      notes: string
      order_id: number
      customer_id: number
    }
    plugin_policies: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      scope_type: "instance" | "user" | "organization" | "pool"
      scope_id: number
      allowlist: string
      require_pinned: boolean
      capabilities: string
    }
    posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      poster: string
      content: string
      excerpt: string
      views: number
      published_at: string
      status: "published" | "draft" | "archived"
      is_featured: number
      author_id: number
    }
    print_devices: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      mac_address: string
      location: string
      terminal: string
      status: "online" | "offline" | "warning"
      last_ping: number
      print_count: number
    }
    product_units: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      abbreviation: string
      type: string
      description: string
      is_default: boolean
      product_id: number
    }
    product_variants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      variant: string
      type: string
      description: string
      options: string
      status: "active" | "inactive" | "draft"
      product_id: number
    }
    products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      price: number
      image_url: string
      is_available: boolean
      inventory_count: number
      preparation_time: number
      allergens: string
      nutritional_info: string
      category_id: number
      manufacturer_id: number
    }
    protected_branches: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      pattern: string
      required_approvals: number
      dismiss_stale_reviews: boolean
      require_conversation_resolution: boolean
      required_checks: string
      allow_force_push: boolean
      allow_deletion: boolean
      require_linear_history: boolean
      require_human_approval_for_agents: boolean
      require_up_to_date: boolean
      enforce_admins: boolean
      push_restrictions: string
    }
    pull_request_reviewers: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      pull_request_id: number
      reviewer_type: "user" | "team"
      reviewer_id: number
      requested_by_id: number
      from_code_owners: boolean
      responded_at: string
      repository_id: number
    }
    pull_request_reviews: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      pull_request_id: number
      reviewer_id: number
      state: "pending" | "approved" | "changes_requested" | "commented" | "dismissed"
      body: string
      commit_sha: string
      submitted_at: string
      dismissed_reason: string
      external_author: string
      repository_id: number
    }
    pull_requests: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      number: number
      title: string
      body: string
      author_id: number
      state: "open" | "closed" | "merged"
      head_repository_id: number
      head_branch: string
      head_sha: string
      base_branch: string
      base_sha: string
      merge_commit_sha: string
      merged_at: string
      merged_by_id: number
      draft: boolean
      mergeable_state: "unknown" | "clean" | "dirty" | "blocked" | "behind"
      stack_parent_id: number
      additions: number
      deletions: number
      changed_files: number
      closed_at: string
      closed_by_id: number
      mergeable_base_sha: string
      mergeable_head_sha: string
      mergeable_conflicts: string
      external_author: string
      auto_merge_strategy: "merge" | "squash" | "rebase"
      auto_merge_by_id: number
    }
    push_subscriptions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      endpoint: string
      public_key: string
      auth_secret: string
      user_agent: string
      last_seen_at: string
      user_id: number
    }
    query_logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      query: string
      normalized_query: string
      duration: number
      connection: string
      status: "completed" | "failed" | "slow"
      error: string
      executed_at: string
      bindings: string
      trace: string
      model: string
      method: string
      file: string
      line: number
      memory_usage: number
      rows_affected: number
      transaction_id: string
      tags: string
      affected_tables: string
      indexes_used: string
      missing_indexes: string
      explain_plan: string
      optimization_suggestions: string
    }
    queue_circuit_state: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      queue_name: string
      success_count: number
      failure_count: number
      window_start: string
      paused_at: string
      resume_at: string
    }
    reactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      subject_type: "issue" | "issue_comment" | "review_comment"
      subject_id: number
      user_id: number
      content: "+1" | "-1" | "laugh" | "hooray" | "confused" | "heart" | "rocket" | "eyes"
    }
    receipts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      printer: string
      document: string
      timestamp: string
      status: "success" | "failed" | "warning"
      size: number
      pages: number
      duration: number
      metadata: string
      print_device_id: number
    }
    recovery_codes: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      code_hash: string
      used_at: string
    }
    release_assets: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      release_id: number
      name: string
      storage_path: string
      content_type: string
      size_bytes: number
      checksum: string
      download_count: number
      repository_id: number
    }
    releases: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      version: string
      type: string
      status: string
      notes: string
      downloads: number
      author: string
      repository_id: number
      user_id: number
      tag_name: string
      target_sha: string
      name: string
      is_prerelease: boolean
      published_at: string
    }
    repair_attempts: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      workflow_run_id: number
      workflow_job_id: number
      step: string
      state: "attempted" | "proposed" | "refused" | "failed"
      refusal: string
      reason: string
      branch: string
      commit_sha: string
      proposed_by: number
      minutes: number
      cost: number
      tokens: number
      pull_request_id: number
      started_at: string
    }
    repair_settings: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      enabled: boolean
      forbidden_paths: string
      steps: string
      max_attempts: number
      max_minutes: number
      max_cost: number
    }
    repo_collaborators: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      user_id: number
      permission: "read" | "triage" | "write" | "maintain" | "admin"
    }
    repo_topics: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      topic: string
    }
    repositories: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      owner_type: "user" | "organization"
      owner_id: number
      name: string
      description: string
      homepage: string
      visibility: "public" | "private" | "internal"
      default_branch: string
      disk_path: string
      is_fork: boolean
      parent_id: number
      is_archived: boolean
      is_template: boolean
      size_kb: number
      stars_count: number
      forks_count: number
      open_issues_count: number
      issue_counter: number
      pushed_at: string
      allow_merge_commit: boolean
      allow_squash_merge: boolean
      allow_rebase_merge: boolean
      default_merge_strategy: "merge" | "squash" | "rebase"
      delete_branch_on_merge: boolean
      count_machine_approvals: boolean
    }
    repository_contributors: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      name: string
      email: string
      commits: number
      user_id: number
    }
    repository_labels: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      name: string
      color: string
      description: string
      is_default: boolean
    }
    repository_languages: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      language: string
      bytes: number
      percent: number
    }
    repository_lfs_locks: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      lock_id: string
      path: string
      owner_id: number
      owner_name: string
      ref: string
      locked_at: string
    }
    repository_mirrors: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      direction: "pull" | "push"
      provider: "github" | "gitlab" | "git"
      remote_url: string
      remote_owner: string
      remote_name: string
      credential_ref: string
      webhook_secret: string
      interval_seconds: number
      enabled: boolean
      allow_local_pushes: boolean
      write_through: boolean
      last_synced_at: string
      last_sha: string
      last_error: string
      failure_count: number
      sync_metadata: boolean
      last_metadata_sync_at: string
      metadata_error: string
      metadata_failure_count: number
    }
    requests: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      deleted_at: string | null
      method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "HEAD"
      path: string
      status_code: number
      duration_ms: number
      ip_address: string
      memory_usage: number
      user_agent: string
      error_message: string
    }
    review_checkpoints: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      pull_request_id: number
      reviewer_id: number
      head_sha: string
      repository_id: number
    }
    review_comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      review_thread_id: number
      review_id: number
      author_id: number
      body: string
      suggestion: string
      edited_at: string
      external_id: number
      external_author: string
      repository_id: number
    }
    review_drafts: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      pull_request_id: number
      author_id: number
      path: string
      side: "left" | "right"
      from_line: number
      to_line: number
      body: string
      repository_id: number
    }
    review_threads: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      pull_request_id: number
      path: string
      line: number
      start_line: number
      side: "left" | "right"
      original_line: number
      original_commit_sha: string
      resolved: boolean
      resolved_by_id: number
      outdated: boolean
      external_id: number
      repository_id: number
    }
    reviewed_files: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      pull_request_id: number
      reviewer_id: number
      path: string
      head_sha: string
      repository_id: number
    }
    reviews: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      rating: number
      title: string
      content: string
      is_verified_purchase: boolean
      is_approved: boolean
      is_featured: boolean
      helpful_votes: number
      unhelpful_votes: number
      purchase_date: string
      images: string
      product_id: number
      customer_id: number
    }
    run_metadata: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      workflow_run_id: number
      key: string
      value: string
      version: number
      updated_by_job_id: number
      repository_id: number
    }
    runner_pool_maintainers: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      runner_pool_id: number
      user_id: number
    }
    runner_pool_repositories: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      runner_pool_id: number
      repository_id: number
    }
    runner_pools: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      require_signed_steps: boolean
      plugins: string
      description: string
    }
    runner_queues: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      runner_pool_id: number
      name: string
      state: "active" | "paused"
      paused_reason: string
    }
    runner_registration_tokens: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      runner_pool_id: number
      name: string
      token_hash: string
      runner_queue_id: number
      first_used_at: string
      last_used_at: string
      uses: number
      revoked_at: string
      expires_at: string
      created_by_id: number
    }
    runners: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      runner_queue_id: number
      stop_requested: "graceful" | "forced"
      tags: string
      runner_registration_token_id: number
      name: string
      scope_type: "instance" | "organization" | "repository"
      scope_id: number
      token_hash: string
      labels: string
      state: "active" | "disabled"
      version: string
      last_seen_at: string
    }
    shipping_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      base_rate: number
      free_shipping: number
      status: "active" | "inactive" | "draft"
    }
    shipping_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      weight_from: number
      weight_to: number
      rate: number
      shipping_method_id: number
      shipping_zone_id: number
    }
    shipping_zones: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      countries: string
      regions: string
      postal_codes: string
      status: "active" | "inactive" | "draft"
      shipping_method_id: number
    }
    social_posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      content: string
      platform: "twitter" | "facebook" | "instagram" | "linkedin" | "tiktok" | "youtube"
      status: "draft" | "scheduled" | "published" | "failed"
      scheduled_at: string
      published_at: string
      likes: number
      shares: number
      comments: number
      reach: number
      image_url: string
      external_id: string
      user_id: number
    }
    ssh_keys: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      title: string
      key_type: "ssh-ed25519" | "ssh-rsa" | "ecdsa-sha2-nistp256"
      public_key: string
      fingerprint: string
      last_used_at: string
    }
    sso_identities: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      issuer: string
      subject: string
      email: string
      groups: string
      last_seen_at: string
    }
    stars: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      user_id: number
    }
    subscriber_emails: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: string
      source: string
      subscriber_id: number
    }
    subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: string
      status: "subscribed" | "unsubscribed" | "pending" | "bounced"
      source: string
      unsubscribed_at: string
      user_id: number
    }
    subscriptions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      plan: string
      provider_id: string
      provider_status: string
      unit_price: number
      provider_type: string
      provider_price_id: string
      quantity: number
      trial_ends_at: string
      ends_at: string
      last_used_at: string
      user_id: number
    }
    taggable_models: {
      // columns
      id: number
      tag_id: number
      taggable_id: number
      taggable_type: string
      created_at: string
      updated_at: string | null
    }
    tags: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      description: string
      color: string
    }
    tax_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      rate: number
      type: string
      country: string
      region: "North America" | "South America" | "Europe" | "Asia" | "Africa" | "Oceania" | "Antarctica"
      status: "active" | "inactive"
      is_default: boolean
    }
    team_members: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      team_id: number
      user_id: number
      role: "maintainer" | "member"
    }
    team_repositories: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      team_id: number
      repository_id: number
      permission: "read" | "triage" | "write" | "maintain" | "admin"
    }
    teams: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      organization_id: number
      name: string
      slug: string
      description: string
      parent_team_id: number
    }
    test_executions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      test_run_id: number
      managed_test_id: number
      result: "passed" | "failed" | "skipped"
      duration_ms: number
      retries: number
      failure_message: string
      failure_stack: string
      workflow_job_id: number
      tags: string
      repository_id: number
    }
    test_monitors: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      suite: string
      condition: "flaky" | "fail_rate" | "duration"
      threshold: number
      window_days: number
      state: "ok" | "alarm"
      measurement: number
      changed_at: string
      evaluated_at: string
      enabled: boolean
    }
    test_runs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      test_suite_id: number
      head_sha: string
      branch: string
      pull_request_id: number
      workflow_run_id: number
      external_key: string
      source: "junit" | "json"
      passed: number
      failed: number
      skipped: number
      muted_failures: number
      duration_ms: number
      repository_id: number
    }
    test_suites: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      name: string
      slug: string
    }
    timeline_entries: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      subject_type: "issue" | "pull_request"
      subject_id: number
      kind: "closed" | "reopened" | "renamed" | "labeled" | "unlabeled" | "assigned" | "unassigned" | "milestoned" | "demilestoned" | "locked" | "unlocked" | "referenced" | "mentioned" | "merged"
      actor_id: number
      external_actor: string
      subject_text: string
      previous_text: string
      reference_number: number
    }
    token_usage_windows: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      access_token_id: number
      action: string
      window_started_at: string
      used: number
    }
    transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: number
      status: string
      payment_method: string
      payment_details: string
      transaction_reference: string
      loyalty_points_earned: number
      loyalty_points_redeemed: number
      order_id: number
    }
    users: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email_verified_at: string
      password_changed_at: string | null
      two_factor_secret: string | null
      two_factor_enabled: boolean | null
      two_factor_last_used_step: number | null
      stripe_id: string | null
      handle: string
      name: string
      email: string
      password: string
      bio: string
      avatar_url: string
      location: string
      website: string
      is_admin: boolean
      machine_for_organization_id: number
      github_username: string
    }
    waitlist_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      quantity: number
      notification_preference: "sms" | "email" | "both"
      source: string
      notes: string
      status: "waiting" | "purchased" | "notified" | "cancelled"
      notified_at: string
      purchased_at: string
      cancelled_at: string
      product_id: number
      customer_id: number
    }
    waitlist_restaurants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      party_size: number
      check_in_time: string
      table_preference: "indoor" | "bar" | "booth" | "no_preference"
      status: "waiting" | "seated" | "cancelled" | "no_show"
      quoted_wait_time: number
      actual_wait_time: number
      queue_position: number
      seated_at: string
      no_show_at: string
      cancelled_at: string
      customer_id: number
    }
    watches: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      user_id: number
      subscription: "all" | "participating" | "ignore"
    }
    webhook_deliveries: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      webhook_id: number
      event: string
      payload: string
      request_headers: string
      response_status: number
      response_body: string
      duration_ms: number
      attempt: number
      error: string
      delivered_at: string
      repository_id: number
    }
    webhooks: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      url: string
      secret: string
      events: string
      content_type: "application/json" | "application/x-www-form-urlencoded"
      active: boolean
      consecutive_failures: number
      last_success_at: string
    }
    websockets: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: "disconnection" | "error" | "success"
      socket: string
      details: string
      time: number
    }
    workflow_artifacts: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      workflow_run_id: number
      workflow_job_id: number
      name: string
      digest: string
      blob_key: string
      size_bytes: number
      content_type: string
      expires_at: string
      runner_id: string
      repository_id: number
    }
    workflow_cache_entries: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      repository_id: number
      scope: string
      cache_key: string
      label: string
      digest: string
      blob_key: string
      size_bytes: number
      last_used_at: string
      restores: number
      workflow_run_id: number
    }
    workflow_job_logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      workflow_job_id: number
      attempt: number
      sequence: number
      content: string
      stream: "stdout" | "stderr"
      events: string
      repository_id: number
    }
    workflow_jobs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      workflow_run_id: number
      job_id: string
      name: string
      position: number
      state: "blocked" | "queued" | "running" | "cancelling" | "cancelled" | "failed" | "skipped" | "succeeded" | "paused" | "sleeping"
      condition: string
      condition_reason: string
      matrix_values: string
      concurrency_group: string
      outputs: string
      kind: "command" | "wait" | "block" | "trigger" | "await"
      wake_at: string
      settings: string
      priority: number
      group_label: string
      approved_by_id: number
      approved_at: string
      attempt: number
      cache_lookups: number
      cache_hits: number
      resume_from_step: number
      uploaded_by_job_id: number
      upload_depth: number
      triggered_run_id: number
      orchestrator: boolean
      fail_fast: boolean
      max_parallel: number
      timeout_minutes: number
      continue_on_error: boolean
      needs: string
      runs_on: string
      runner_id: string
      lease_expires_at: string
      job_token_hash: string
      parallel_index: number
      parallel_total: number
      notified_at: string
      queued_at: string
      started_at: string
      finished_at: string
      repository_id: number
    }
    workflow_journal_entries: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      workflow_run_id: number
      sequence: number
      kind: string
      identity: string
      name: string
      state: string
      result: string
      error: string
      workflow_job_id: number
      wake_at: string
      duration_ms: number
      repository_id: number
    }
    workflow_notification_rules: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      repository_id: number
      user_id: number
      workflow: string
      branch: string
      job_key: string
      condition: "failure" | "success" | "recovery" | "always"
      created_by_id: number
    }
    workflow_run_events: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      workflow_run_id: number
      name: string
      payload: string
      idempotency_key: string
      actor_id: number
      source: string
      delivered_to: number
      repository_id: number
    }
    workflow_runs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      workflow_version_id: number
      repository_id: number
      number: number
      state: "queued" | "running" | "waiting" | "paused" | "cancelling" | "cancelled" | "failed" | "succeeded"
      paused_at: string
      paused_by_id: number
      event: string
      event_ref: string
      head_sha: string
      changed_paths: string
      definition_sha: string
      concurrency_group: string
      trigger_depth: number
      uploads: number
      dispatch_inputs: string
      approval_state: "not-required" | "required" | "approved" | "rejected"
      approved_by: number
      approved_at: string
      trusted: boolean
      actor_id: number
      pull_request_id: number
      attempt: number
      started_at: string
      finished_at: string
      conclusion_reason: string
      request_id: string
      redelivery_key: string
    }
    workflow_secrets: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      scope_type: "instance" | "pool" | "owner" | "repository" | "environment"
      scope_id: number
      key: string
      sealed: string
      updated_by_id: number
    }
    workflow_step_attempts: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      workflow_step_id: number
      attempt: number
      state: "running" | "cancelled" | "failed" | "succeeded"
      exit_code: number
      runner_id: string
      error: string
      started_at: string
      finished_at: string
      repository_id: number
    }
    workflow_steps: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      workflow_job_id: number
      position: number
      name: string
      command: string
      uses: string
      inputs: string
      env: string
      working_directory: string
      shell: string
      condition: string
      step_id: string
      continue_on_error: boolean
      timeout_minutes: number
      state: "pending" | "running" | "cancelled" | "failed" | "skipped" | "succeeded"
      attempts: number
      exit_code: number
      started_at: string
      finished_at: string
      outputs: string
      error: string
      reused_from_attempt: number
      queued_ms: number
      active_ms: number
      repository_id: number
    }
    workflow_templates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      owner_type: "user" | "organization"
      owner_id: number
      slug: string
      name: string
      description: string
      path: string
      source: string
      created_by_id: number
    }
    workflow_variables: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      scope_type: "instance" | "owner" | "repository"
      scope_id: number
      key: string
      value: string
    }
    workflow_version_jobs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      workflow_version_id: number
      job_id: string
      position: number
      name: string
      runs_on: string
      needs: string
      condition: string
      matrix: string
      continue_on_error: boolean
      kind: "command" | "wait" | "block" | "trigger" | "await"
      settings: string
      if_changed: string
      priority: number
      group_label: string
      fail_fast: boolean
      max_parallel: number
      env: string
      permissions: string
      concurrency_group: string
      job_cancel_in_progress: boolean
      default_shell: string
      default_working_directory: string
      uses: string
      call_with: string
      call_secrets: string
      outputs: string
      timeout_minutes: number
      repository_id: number
    }
    workflow_version_steps: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      workflow_version_job_id: number
      position: number
      step_id: string
      name: string
      command: string
      uses: string
      inputs: string
      env: string
      shell: string
      continue_on_error: boolean
      timeout_minutes: number
      working_directory: string
      condition: string
      repository_id: number
    }
    workflow_versions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      workflow_id: number
      source_sha: string
      source_path: string
      content_digest: string
      on_push: boolean
      on_pull_request: boolean
      on_pull_request_target: boolean
      on_dispatch: boolean
      reusable: boolean
      push_branches: string
      push_tags: string
      push_paths: string
      push_branches_ignore: string
      push_tags_ignore: string
      push_paths_ignore: string
      pull_request_types: string
      pull_request_branches_ignore: string
      pull_request_paths_ignore: string
      pull_request_branches: string
      pull_request_paths: string
      concurrency_group: string
      cancel_in_progress: boolean
      intermediate: "run" | "skip" | "cancel"
      dispatch_inputs: string
      env: string
      permissions: string
      default_shell: string
      default_working_directory: string
      on_issues: boolean
      issue_types: string
      on_issue_comment: boolean
      issue_comment_types: string
      on_release: boolean
      release_types: string
      on_repository_dispatch: boolean
      repository_dispatch_types: string
      on_workflow_run: boolean
      workflow_run_workflows: string
      workflow_run_types: string
      workflow_run_branches: string
      call_inputs: string
      call_outputs: string
      call_secrets: string
      warnings: string
      schedules: string
      unsupported_events: string
      repository_id: number
    }
    workflows: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      owner_type: "user" | "organization"
      owner_id: number
      repository_id: number
      path: string
      name: string
      last_scheduled_at: string
      state: "active" | "disabled" | "removed"
      selector: string
    }
  }
}

export {}
