-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_journal_entries" (
  "id" BIGSERIAL PRIMARY KEY,
  "workflow_run_id" bigint not null REFERENCES "workflow_runs"("id") ON DELETE CASCADE,
  "sequence" integer not null,
  "kind" varchar(30) not null default 'step',
  "identity" varchar(64) not null,
  "name" varchar(200),
  "state" varchar(20) not null default 'pending',
  "result" text,
  "error" text,
  "workflow_job_id" integer,
  "wake_at" varchar(255),
  "duration_ms" integer,
  "repository_id" integer,
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_journal_entries_sequence_index" ON "workflow_journal_entries" ("workflow_run_id", "sequence");
CREATE INDEX IF NOT EXISTS "workflow_journal_entries_run_index" ON "workflow_journal_entries" ("workflow_run_id");
