-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "notifications" ALTER COLUMN "data" DROP DEFAULT;
ALTER TABLE "notifications" ALTER COLUMN "data" TYPE text USING "data"::text;
ALTER TABLE "notifications" ALTER COLUMN "data" SET NOT NULL;
