-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_runs" (
  "id" BIGSERIAL PRIMARY KEY,
  "workflow_version_id" bigint not null REFERENCES "workflow_versions"("id") ON DELETE CASCADE,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "number" integer not null default 1,
  "state" "workflow_runs_state_type" default 'queued',
  "event" varchar(40) not null,
  "event_ref" varchar(400),
  "head_sha" varchar(40),
  "definition_sha" varchar(40),
  "trusted" boolean default false,
  "actor_id" integer,
  "pull_request_id" integer,
  "started_at" varchar(40),
  "finished_at" varchar(40),
  "conclusion_reason" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "workflow_runs_repository_index" ON "workflow_runs" ("repository_id", "id");
CREATE INDEX IF NOT EXISTS "workflow_runs_state_index" ON "workflow_runs" ("state", "id");
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_runs_dedupe_index" ON "workflow_runs" ("workflow_version_id", "event_ref", "head_sha", "event");
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_runs_uuid_unique" ON "workflow_runs" ("uuid");
