-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "workflow_runs_approval_state_type" AS ENUM ('not-required', 'required', 'approved', 'rejected'); EXCEPTION WHEN duplicate_object THEN null; END $stacks$;
ALTER TYPE "workflow_runs_approval_state_type" ADD VALUE IF NOT EXISTS 'not-required';
ALTER TYPE "workflow_runs_approval_state_type" ADD VALUE IF NOT EXISTS 'required';
ALTER TYPE "workflow_runs_approval_state_type" ADD VALUE IF NOT EXISTS 'approved';
ALTER TYPE "workflow_runs_approval_state_type" ADD VALUE IF NOT EXISTS 'rejected';
