-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "review_drafts" (
  "id" BIGSERIAL PRIMARY KEY,
  "pull_request_id" bigint not null REFERENCES "pull_requests"("id") ON DELETE CASCADE,
  "author_id" bigint not null REFERENCES "users"("id") ON DELETE CASCADE,
  "path" text not null,
  "side" "review_drafts_side_type" default 'right',
  "from_line" integer not null,
  "to_line" integer not null,
  "body" text not null,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "review_drafts_pr_author_index" ON "review_drafts" ("pull_request_id", "author_id");
