-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "team_repositories_permission_type" AS ENUM ('read', 'triage', 'write', 'maintain', 'admin');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "team_repositories_permission_type" ADD VALUE IF NOT EXISTS 'read';
ALTER TYPE "team_repositories_permission_type" ADD VALUE IF NOT EXISTS 'triage';
ALTER TYPE "team_repositories_permission_type" ADD VALUE IF NOT EXISTS 'write';
ALTER TYPE "team_repositories_permission_type" ADD VALUE IF NOT EXISTS 'maintain';
ALTER TYPE "team_repositories_permission_type" ADD VALUE IF NOT EXISTS 'admin';
