-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "plugin_policies" (
  "id" BIGSERIAL PRIMARY KEY,
  "scope_type" "plugin_policies_scope_type_type" not null,
  "scope_id" integer,
  "allowlist" text,
  "require_pinned" boolean default false,
  "capabilities" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "plugin_policies_scope_index" ON "plugin_policies" ("scope_type", "scope_id");
CREATE UNIQUE INDEX IF NOT EXISTS "plugin_policies_uuid_unique" ON "plugin_policies" ("uuid");
