-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_job_logs" (
  "id" BIGSERIAL PRIMARY KEY,
  "workflow_job_id" bigint not null REFERENCES "workflow_jobs"("id") ON DELETE CASCADE,
  "sequence" integer not null,
  "content" text,
  "stream" "workflow_job_logs_stream_type" default 'stdout',
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "workflow_job_logs_job_index" ON "workflow_job_logs" ("workflow_job_id", "sequence");
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_job_logs_sequence_index" ON "workflow_job_logs" ("workflow_job_id", "sequence");
