-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "forge_credentials" (
  "id" BIGSERIAL PRIMARY KEY,
  "user_id" bigint not null REFERENCES "users"("id"),
  "provider" "forge_credentials_provider_type" default 'github',
  "host" varchar(255) not null default 'github.com',
  "remote_login" varchar(120),
  "sealed" text not null,
  "scopes" varchar(500),
  "last_used_at" varchar(40),
  "last_error" varchar(500),
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "forge_credentials_owner_index" ON "forge_credentials" ("user_id", "provider", "host");
CREATE UNIQUE INDEX IF NOT EXISTS "forge_credentials_uuid_unique" ON "forge_credentials" ("uuid");
