-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_run_events" (
  "id" BIGSERIAL PRIMARY KEY,
  "workflow_run_id" bigint not null REFERENCES "workflow_runs"("id") ON DELETE CASCADE,
  "name" varchar(200) not null,
  "payload" text,
  "idempotency_key" varchar(200) not null,
  "actor_id" integer,
  "source" varchar(30) default 'api',
  "delivered_to" integer default 0,
  "repository_id" integer,
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_run_events_key_index" ON "workflow_run_events" ("idempotency_key");
CREATE INDEX IF NOT EXISTS "workflow_run_events_run_index" ON "workflow_run_events" ("workflow_run_id", "name");
CREATE INDEX IF NOT EXISTS "workflow_run_events_repository_index" ON "workflow_run_events" ("repository_id");
