-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "notification_deliveries_status_type" AS ENUM ('pending', 'sent', 'delivered', 'failed', 'skipped');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "notification_deliveries_status_type" ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE "notification_deliveries_status_type" ADD VALUE IF NOT EXISTS 'sent';
ALTER TYPE "notification_deliveries_status_type" ADD VALUE IF NOT EXISTS 'delivered';
ALTER TYPE "notification_deliveries_status_type" ADD VALUE IF NOT EXISTS 'failed';
ALTER TYPE "notification_deliveries_status_type" ADD VALUE IF NOT EXISTS 'skipped';
ALTER TABLE "notification_deliveries" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "notification_deliveries" ALTER COLUMN "status" TYPE "notification_deliveries_status_type" USING "status"::"notification_deliveries_status_type";
ALTER TABLE "notification_deliveries" ALTER COLUMN "status" SET NOT NULL;
ALTER TABLE "notification_deliveries" ALTER COLUMN "status" SET default 'pending';
