-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_version_steps" (
  "id" BIGSERIAL PRIMARY KEY,
  "workflow_version_job_id" bigint not null REFERENCES "workflow_version_jobs"("id") ON DELETE CASCADE,
  "position" integer default 0,
  "step_id" varchar(100),
  "name" varchar(200),
  "command" text,
  "uses" varchar(400),
  "inputs" text,
  "working_directory" varchar(400),
  "condition" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "workflow_version_steps_job_index" ON "workflow_version_steps" ("workflow_version_job_id", "position");
