-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "on_issues" boolean default false;
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "issue_types" varchar(500);
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "on_issue_comment" boolean default false;
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "issue_comment_types" varchar(500);
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "on_release" boolean default false;
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "release_types" varchar(500);
