-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_steps" (
  "id" BIGSERIAL PRIMARY KEY,
  "workflow_job_id" bigint not null REFERENCES "workflow_jobs"("id") ON DELETE CASCADE,
  "position" integer default 0,
  "name" varchar(200),
  "state" "workflow_steps_state_type" default 'pending',
  "attempts" integer default 0,
  "exit_code" integer,
  "started_at" varchar(40),
  "finished_at" varchar(40),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "workflow_steps_job_index" ON "workflow_steps" ("workflow_job_id", "position");
