-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "run_metadata" (
  "id" BIGSERIAL PRIMARY KEY,
  "workflow_run_id" bigint not null REFERENCES "workflow_runs"("id") ON DELETE CASCADE,
  "key" varchar(200) not null,
  "value" text,
  "version" integer default 1,
  "updated_by_job_id" integer,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "run_metadata_key_index" ON "run_metadata" ("workflow_run_id", "key");
