-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_artifacts" (
  "id" BIGSERIAL PRIMARY KEY,
  "workflow_run_id" bigint not null REFERENCES "workflow_runs"("id") ON DELETE CASCADE,
  "workflow_job_id" integer,
  "name" varchar(200) not null,
  "digest" varchar(64) not null,
  "size_bytes" integer not null,
  "content_type" varchar(150),
  "expires_at" varchar(255),
  "runner_id" varchar(100),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "workflow_artifacts_run_index" ON "workflow_artifacts" ("workflow_run_id");
CREATE INDEX IF NOT EXISTS "workflow_artifacts_expiry_index" ON "workflow_artifacts" ("expires_at");
CREATE INDEX IF NOT EXISTS "workflow_artifacts_digest_index" ON "workflow_artifacts" ("digest");
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_artifacts_name_index" ON "workflow_artifacts" ("workflow_run_id", "name");
