-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "recovery_codes" (
  "id" BIGSERIAL PRIMARY KEY,
  "user_id" bigint not null REFERENCES "users"("id") ON DELETE CASCADE,
  "code_hash" varchar(64) not null,
  "used_at" varchar(255),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "recovery_codes_user_index" ON "recovery_codes" ("user_id", "used_at");
