-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "workflow_notification_rules" DROP CONSTRAINT IF EXISTS "workflow_notification_rules_repository_id_fk";
ALTER TABLE "workflow_notification_rules" DROP CONSTRAINT IF EXISTS "workflow_notification_rules_repository_id_fkey";
ALTER TABLE "workflow_notification_rules" ADD CONSTRAINT "workflow_notification_rules_repository_id_fk" FOREIGN KEY ("repository_id") REFERENCES "repositories"("id") ON DELETE CASCADE;
