-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "forge_credentials_provider_type" AS ENUM ('github', 'gitlab', 'gitea'); EXCEPTION WHEN duplicate_object THEN null; END $stacks$;
ALTER TYPE "forge_credentials_provider_type" ADD VALUE IF NOT EXISTS 'github';
ALTER TYPE "forge_credentials_provider_type" ADD VALUE IF NOT EXISTS 'gitlab';
ALTER TYPE "forge_credentials_provider_type" ADD VALUE IF NOT EXISTS 'gitea';
