-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "team_members" DROP CONSTRAINT IF EXISTS "team_members_team_id_fk";
ALTER TABLE "team_members" DROP CONSTRAINT IF EXISTS "team_members_team_id_fkey";
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE;
ALTER TABLE "team_members" DROP CONSTRAINT IF EXISTS "team_members_user_id_fk";
ALTER TABLE "team_members" DROP CONSTRAINT IF EXISTS "team_members_user_id_fkey";
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;
