-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_versions" (
  "id" BIGSERIAL PRIMARY KEY,
  "workflow_id" bigint not null REFERENCES "workflows"("id") ON DELETE CASCADE,
  "source_sha" varchar(40),
  "source_path" varchar(400),
  "content_digest" varchar(64) not null,
  "on_push" boolean default false,
  "on_pull_request" boolean default false,
  "on_pull_request_target" boolean default false,
  "on_dispatch" boolean default false,
  "reusable" boolean default false,
  "push_branches" text,
  "push_tags" text,
  "push_paths" text,
  "pull_request_branches" text,
  "pull_request_paths" text,
  "schedules" text,
  "unsupported_events" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_versions_digest_index" ON "workflow_versions" ("workflow_id", "content_digest");
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_versions_uuid_unique" ON "workflow_versions" ("uuid");
