-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "managed_tests_state_type" AS ENUM ('enabled', 'muted', 'skipped'); EXCEPTION WHEN duplicate_object THEN null; END $stacks$;
ALTER TYPE "managed_tests_state_type" ADD VALUE IF NOT EXISTS 'enabled';
ALTER TYPE "managed_tests_state_type" ADD VALUE IF NOT EXISTS 'muted';
ALTER TYPE "managed_tests_state_type" ADD VALUE IF NOT EXISTS 'skipped';
DO $stacks$ BEGIN CREATE TYPE "test_runs_source_type" AS ENUM ('junit', 'json'); EXCEPTION WHEN duplicate_object THEN null; END $stacks$;
ALTER TYPE "test_runs_source_type" ADD VALUE IF NOT EXISTS 'junit';
ALTER TYPE "test_runs_source_type" ADD VALUE IF NOT EXISTS 'json';
DO $stacks$ BEGIN CREATE TYPE "test_executions_result_type" AS ENUM ('passed', 'failed', 'skipped'); EXCEPTION WHEN duplicate_object THEN null; END $stacks$;
ALTER TYPE "test_executions_result_type" ADD VALUE IF NOT EXISTS 'passed';
ALTER TYPE "test_executions_result_type" ADD VALUE IF NOT EXISTS 'failed';
ALTER TYPE "test_executions_result_type" ADD VALUE IF NOT EXISTS 'skipped';
