-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "runners" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(200) not null,
  "scope_type" "runners_scope_type_type" default 'instance',
  "scope_id" integer,
  "token_hash" varchar(64) not null,
  "labels" text,
  "state" "runners_state_type" default 'active',
  "version" varchar(60),
  "last_seen_at" varchar(40),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "runners_token_index" ON "runners" ("token_hash");
CREATE INDEX IF NOT EXISTS "runners_scope_index" ON "runners" ("scope_type", "scope_id", "state");
CREATE UNIQUE INDEX IF NOT EXISTS "runners_uuid_unique" ON "runners" ("uuid");
