-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_variables" (
  "id" BIGSERIAL PRIMARY KEY,
  "scope_type" "workflow_variables_scope_type_type" default 'repository',
  "scope_id" integer default 0,
  "key" varchar(200) not null,
  "value" text default '',
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_variables_scope_index" ON "workflow_variables" ("scope_type", "scope_id", "key");
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_variables_uuid_unique" ON "workflow_variables" ("uuid");
