-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "workflow_templates_owner_type_type" AS ENUM ('user', 'organization');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "workflow_templates_owner_type_type" ADD VALUE IF NOT EXISTS 'user';
ALTER TYPE "workflow_templates_owner_type_type" ADD VALUE IF NOT EXISTS 'organization';
