-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "deploy_keys" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "title" varchar(100) not null,
  "key_type" varchar(32) not null,
  "public_key" text not null,
  "fingerprint" varchar(100) not null,
  "can_write" boolean default false,
  "last_used_at" varchar(255),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "deploy_keys_fingerprint_index" ON "deploy_keys" ("fingerprint");
CREATE INDEX IF NOT EXISTS "deploy_keys_repository_index" ON "deploy_keys" ("repository_id");
