-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_runs" ADD COLUMN IF NOT EXISTS "paused_at" varchar(40);
ALTER TABLE "workflow_runs" ADD COLUMN IF NOT EXISTS "paused_by_id" integer;
