-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "review_threads" (
  "id" BIGSERIAL PRIMARY KEY,
  "pull_request_id" bigint not null REFERENCES "pull_requests"("id"),
  "path" text not null,
  "line" integer,
  "start_line" integer,
  "side" "review_threads_side_type" default 'right',
  "original_line" integer,
  "original_commit_sha" varchar(40),
  "resolved" boolean default false,
  "resolved_by_id" bigint REFERENCES "users"("id") ON DELETE SET NULL,
  "outdated" boolean default false,
  "external_id" integer,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "review_threads_pr_index" ON "review_threads" ("pull_request_id");
CREATE INDEX IF NOT EXISTS "review_threads_path_index" ON "review_threads" ("pull_request_id", "path");
CREATE INDEX IF NOT EXISTS "review_threads_external_index" ON "review_threads" ("external_id");
