-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "matrix" text;
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "fail_fast" boolean default true;
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "max_parallel" integer;
