-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "access_token_permissions_scope_type" AS ENUM ('contents', 'issues', 'pull_requests', 'webhooks', 'administration', 'checks', 'actions', 'actions_logs', 'fleet', 'members', 'organization_administration', 'billing');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'contents';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'issues';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'pull_requests';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'webhooks';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'administration';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'checks';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'actions';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'actions_logs';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'fleet';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'members';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'organization_administration';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'billing';
