-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "git_wal_entries" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id"),
  "sequence" integer not null,
  "updates" text not null,
  "blob_key" varchar(255),
  "blob_bytes" integer,
  "status" "git_wal_entries_status_type" not null default 'pending',
  "actor_id" integer,
  "committed_at" varchar(255),
  "reason" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "git_wal_entries_sequence_unique" ON "git_wal_entries" ("repository_id", "sequence");
CREATE INDEX IF NOT EXISTS "git_wal_entries_status_index" ON "git_wal_entries" ("status", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "git_wal_entries_uuid_unique" ON "git_wal_entries" ("uuid");
