-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "kind" "workflow_jobs_kind_type" default 'command';
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "settings" text;
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "group_label" varchar(200);
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "approved_by_id" integer;
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "approved_at" varchar(40);
