-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "deployments" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id"),
  "environment" varchar(120) not null,
  "head_sha" varchar(64) not null,
  "ref" varchar(255),
  "pull_request_id" bigint REFERENCES "pull_requests"("id"),
  "workflow_run_id" bigint REFERENCES "workflow_runs"("id"),
  "url" varchar(500),
  "state" "deployments_state_type" default 'in_progress',
  "reason" varchar(500),
  "created_by_id" integer,
  "finished_at" varchar(255),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "deployments_repository_index" ON "deployments" ("repository_id", "environment");
CREATE INDEX IF NOT EXISTS "deployments_pull_request_index" ON "deployments" ("pull_request_id");
CREATE INDEX IF NOT EXISTS "deployments_state_index" ON "deployments" ("state");
CREATE UNIQUE INDEX IF NOT EXISTS "deployments_uuid_unique" ON "deployments" ("uuid");
