-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "runner_pool_maintainers" (
  "id" BIGSERIAL PRIMARY KEY,
  "runner_pool_id" bigint not null REFERENCES "runner_pools"("id") ON DELETE CASCADE,
  "user_id" bigint not null REFERENCES "users"("id") ON DELETE CASCADE,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "runner_pool_maintainers_pool_index" ON "runner_pool_maintainers" ("runner_pool_id");
CREATE INDEX IF NOT EXISTS "runner_pool_maintainers_user_index" ON "runner_pool_maintainers" ("user_id");
