-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "workflows_state_type" AS ENUM ('active', 'disabled', 'removed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "workflows_state_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "workflows_state_type" ADD VALUE IF NOT EXISTS 'disabled';
ALTER TYPE "workflows_state_type" ADD VALUE IF NOT EXISTS 'removed';
ALTER TABLE "workflows" ALTER COLUMN "state" DROP DEFAULT;
ALTER TABLE "workflows" ALTER COLUMN "state" TYPE "workflows_state_type" USING "state"::"workflows_state_type";
ALTER TABLE "workflows" ALTER COLUMN "state" DROP NOT NULL;
ALTER TABLE "workflows" ALTER COLUMN "state" SET default 'active';
