-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "test_monitors" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "suite" varchar(200) default '',
  "condition" "test_monitors_condition_type" default 'fail_rate',
  "threshold" decimal(10,2) default 0,
  "window_days" integer default 7,
  "state" "test_monitors_state_type" default 'ok',
  "measurement" decimal(10,2) default 0,
  "changed_at" varchar(255),
  "evaluated_at" varchar(255),
  "enabled" boolean default true,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "test_monitors_repository_index" ON "test_monitors" ("repository_id", "enabled");
CREATE UNIQUE INDEX IF NOT EXISTS "test_monitors_uuid_unique" ON "test_monitors" ("uuid");
