-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "cache_lookups" integer default 0;
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "cache_hits" integer default 0;
