-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "notification_event_preferences" (
  "id" BIGSERIAL PRIMARY KEY,
  "event" varchar(64) not null,
  "channel" "notification_event_preferences_channel_type" not null,
  "delivery" "notification_event_preferences_delivery_type" not null default 'immediate',
  "user_id" bigint REFERENCES "users"("id") ON DELETE CASCADE,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
