-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "org_members" (
  "id" BIGSERIAL PRIMARY KEY,
  "organization_id" bigint not null REFERENCES "organizations"("id") ON DELETE CASCADE,
  "user_id" bigint not null REFERENCES "users"("id") ON DELETE CASCADE,
  "role" "org_members_role_type" default 'member',
  "invited_by_id" integer,
  "joined_at" varchar(255),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "org_members_org_user_index" ON "org_members" ("organization_id", "user_id");
