-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "instance_keys" (
  "id" BIGSERIAL PRIMARY KEY,
  "purpose" varchar(40) not null default 'oidc',
  "kid" varchar(64) not null,
  "algorithm" varchar(20) default 'RS256',
  "public_jwk" text,
  "sealed_private" text,
  "retired_at" varchar(40),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "instance_keys_kid_index" ON "instance_keys" ("kid");
CREATE INDEX IF NOT EXISTS "instance_keys_purpose_index" ON "instance_keys" ("purpose", "retired_at");
