DO $stacks$ BEGIN CREATE TYPE "digital_deliveries_status_type" AS ENUM ('active', 'inactive');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "email_lists_status_type" AS ENUM ('active', 'inactive', 'archived');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "campaigns_type_type" AS ENUM ('email', 'sms', 'push', 'social', 'multi-channel');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "campaigns_status_type" AS ENUM ('draft', 'scheduled', 'sending', 'sent', 'paused', 'cancelled', 'failed', 'active', 'completed', 'archived');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "logs_type_type" AS ENUM ('warning', 'error', 'info', 'success');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "logs_source_type" AS ENUM ('file', 'cli', 'system');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "mail_preferences_display_density_type" AS ENUM ('comfortable', 'default', 'compact');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "mail_preferences_theme_type" AS ENUM ('light', 'dark', 'system');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "mail_preferences_language_type" AS ENUM ('en', 'fr', 'de', 'es', 'ja');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "mail_preferences_default_reply_behavior_type" AS ENUM ('reply', 'replyAll');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "mail_preferences_auto_advance_type" AS ENUM ('newer', 'older', 'back');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "mail_preferences_notification_sound_type" AS ENUM ('default', 'subtle', 'none');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "print_devices_status_type" AS ENUM ('online', 'offline', 'warning');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "coupons_status_type" AS ENUM ('Active', 'Scheduled', 'Expired');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "coupons_discount_type_type" AS ENUM ('fixed_amount', 'percentage');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "product_variants_status_type" AS ENUM ('active', 'inactive', 'draft');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "query_logs_status_type" AS ENUM ('completed', 'failed', 'slow');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "receipts_status_type" AS ENUM ('success', 'failed', 'warning');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "repositories_owner_type_type" AS ENUM ('user', 'organization');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "repositories_visibility_type" AS ENUM ('public', 'private', 'internal');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "milestones_state_type" AS ENUM ('open', 'closed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "requests_method_type" AS ENUM ('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "shipping_methods_status_type" AS ENUM ('active', 'inactive', 'draft');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "shipping_zones_status_type" AS ENUM ('active', 'inactive', 'draft');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "tax_rates_region_type" AS ENUM ('North America', 'South America', 'Europe', 'Asia', 'Africa', 'Oceania', 'Antarctica');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "tax_rates_status_type" AS ENUM ('active', 'inactive');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "customers_status_type" AS ENUM ('Active', 'Inactive');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "carts_status_type" AS ENUM ('active', 'abandoned', 'converted', 'expired');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "drivers_status_type" AS ENUM ('active', 'on_delivery', 'on_break');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "issues_state_type" AS ENUM ('open', 'closed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "issues_state_reason_type" AS ENUM ('completed', 'not_planned', 'duplicate');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "issue_comments_commentable_type_type" AS ENUM ('issue', 'pull_request');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "notification_deliveries_channel_type" AS ENUM ('email', 'sms', 'chat', 'database', 'push', 'broadcast');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "notification_deliveries_status_type" AS ENUM ('pending', 'sent', 'delivered', 'failed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "license_keys_template_type" AS ENUM ('Standard License', 'Premium License', 'Enterprise License');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "license_keys_status_type" AS ENUM ('active', 'inactive', 'unassigned');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "org_members_role_type" AS ENUM ('owner', 'admin', 'member');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "payments_method_type" AS ENUM ('cash', 'creditCard', 'debitCard', 'paypal', 'applePay', 'googlePay', 'bankTransfer', 'giftCard');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "payments_status_type" AS ENUM ('pending', 'processing', 'completed', 'failed', 'refunded', 'partiallyRefunded', 'succeeded');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "posts_status_type" AS ENUM ('published', 'draft', 'archived');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "comments_status_type" AS ENUM ('pending', 'approved', 'spam', 'trash');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "pull_requests_state_type" AS ENUM ('open', 'closed', 'merged');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "pull_requests_mergeable_state_type" AS ENUM ('unknown', 'clean', 'dirty', 'blocked', 'behind');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "pull_request_reviews_state_type" AS ENUM ('pending', 'approved', 'changes_requested', 'commented', 'dismissed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "pull_request_reviewers_reviewer_type_type" AS ENUM ('user', 'team');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "repo_collaborators_permission_type" AS ENUM ('read', 'triage', 'write', 'maintain', 'admin');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "review_threads_side_type" AS ENUM ('left', 'right');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "social_posts_platform_type" AS ENUM ('twitter', 'facebook', 'instagram', 'linkedin', 'tiktok', 'youtube');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "social_posts_status_type" AS ENUM ('draft', 'scheduled', 'published', 'failed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "ssh_keys_key_type_type" AS ENUM ('ssh-ed25519', 'ssh-rsa', 'ecdsa-sha2-nistp256');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "subscribers_status_type" AS ENUM ('subscribed', 'unsubscribed', 'pending', 'bounced');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "campaign_sends_status_type" AS ENUM ('queued', 'sent', 'failed', 'bounced', 'complained');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "email_list_subscribers_status_type" AS ENUM ('subscribed', 'unsubscribed', 'pending', 'bounced');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "team_members_role_type" AS ENUM ('maintainer', 'member');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "waitlist_products_notification_preference_type" AS ENUM ('sms', 'email', 'both');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "waitlist_products_status_type" AS ENUM ('waiting', 'purchased', 'notified', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "waitlist_restaurants_table_preference_type" AS ENUM ('indoor', 'bar', 'booth', 'no_preference');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "waitlist_restaurants_status_type" AS ENUM ('waiting', 'seated', 'cancelled', 'no_show');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "watches_subscription_type" AS ENUM ('all', 'participating', 'ignore');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
DO $stacks$ BEGIN CREATE TYPE "websockets_type_type" AS ENUM ('disconnection', 'error', 'success');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
