-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "git_refs" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "ref" varchar(255) not null,
  "sha" varchar(64) not null,
  "sequence" integer not null default 0,
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "git_refs_unique" ON "git_refs" ("repository_id", "ref");
CREATE INDEX IF NOT EXISTS "git_refs_repository_index" ON "git_refs" ("repository_id");
CREATE UNIQUE INDEX IF NOT EXISTS "git_refs_uuid_unique" ON "git_refs" ("uuid");
