-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_version_steps" ADD COLUMN IF NOT EXISTS "shell" varchar(200);
ALTER TABLE "workflow_version_steps" ADD COLUMN IF NOT EXISTS "continue_on_error" boolean default false;
