-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_step_attempts" (
  "id" BIGSERIAL PRIMARY KEY,
  "workflow_step_id" bigint not null REFERENCES "workflow_steps"("id") ON DELETE CASCADE,
  "attempt" integer not null default 1,
  "state" "workflow_step_attempts_state_type" default 'running',
  "exit_code" integer,
  "runner_id" varchar(200),
  "error" text,
  "started_at" varchar(40),
  "finished_at" varchar(40),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "workflow_step_attempts_step_index" ON "workflow_step_attempts" ("workflow_step_id", "attempt");
