-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_templates" (
  "id" BIGSERIAL PRIMARY KEY,
  "owner_type" "workflow_templates_owner_type_type" default 'user',
  "owner_id" integer not null,
  "slug" varchar(120) not null,
  "name" varchar(200) not null,
  "description" text default '',
  "path" varchar(500) default '.github/workflows/ci.yml',
  "source" text not null,
  "created_by_id" integer,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_templates_slug_index" ON "workflow_templates" ("owner_type", "owner_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_templates_uuid_unique" ON "workflow_templates" ("uuid");
