-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "repair_attempts_state_type" AS ENUM ('attempted', 'proposed', 'refused', 'failed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "repair_attempts_state_type" ADD VALUE IF NOT EXISTS 'attempted';
ALTER TYPE "repair_attempts_state_type" ADD VALUE IF NOT EXISTS 'proposed';
ALTER TYPE "repair_attempts_state_type" ADD VALUE IF NOT EXISTS 'refused';
ALTER TYPE "repair_attempts_state_type" ADD VALUE IF NOT EXISTS 'failed';
