-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "releases" (
  "id" BIGSERIAL PRIMARY KEY,
  "version" varchar(50) not null,
  "type" varchar(255),
  "status" varchar(255) not null,
  "notes" text,
  "downloads" integer,
  "author" varchar(255),
  "repository_id" bigint REFERENCES "repositories"("id") ON DELETE CASCADE,
  "user_id" bigint REFERENCES "users"("id"),
  "tag_name" varchar(255),
  "target_sha" varchar(40),
  "name" varchar(255),
  "is_prerelease" boolean default false,
  "published_at" timestamp,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "releases_repo_tag_index" ON "releases" ("repository_id", "tag_name");
CREATE INDEX IF NOT EXISTS "releases_repo_published_index" ON "releases" ("repository_id", "published_at");
CREATE UNIQUE INDEX IF NOT EXISTS "releases_uuid_unique" ON "releases" ("uuid");
