-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_runs" ADD COLUMN IF NOT EXISTS "approval_state" "workflow_runs_approval_state_type" default 'not-required';
ALTER TABLE "workflow_runs" ADD COLUMN IF NOT EXISTS "approved_by" integer;
ALTER TABLE "workflow_runs" ADD COLUMN IF NOT EXISTS "approved_at" varchar(40);
