-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "test_suites" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "name" varchar(100) not null,
  "slug" varchar(100) not null,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "test_suites_repository_index" ON "test_suites" ("repository_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "test_suites_uuid_unique" ON "test_suites" ("uuid");
