-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sso_identities" (
  "id" BIGSERIAL PRIMARY KEY,
  "user_id" bigint not null REFERENCES "users"("id") ON DELETE CASCADE,
  "issuer" varchar(255) not null,
  "subject" varchar(255) not null,
  "email" varchar(255),
  "groups" text,
  "last_seen_at" varchar(255),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "sso_identities_subject_index" ON "sso_identities" ("issuer", "subject");
CREATE INDEX IF NOT EXISTS "sso_identities_user_index" ON "sso_identities" ("user_id");
