CREATE TYPE "digital_deliveries_status_type" AS ENUM ('active', 'inactive');
CREATE TYPE "email_lists_status_type" AS ENUM ('active', 'inactive', 'archived');
CREATE TYPE "campaigns_type_type" AS ENUM ('email', 'sms', 'push', 'social', 'multi-channel');
CREATE TYPE "campaigns_status_type" AS ENUM ('draft', 'scheduled', 'sending', 'sent', 'paused', 'cancelled', 'failed', 'active', 'completed', 'archived');
CREATE TYPE "logs_type_type" AS ENUM ('warning', 'error', 'info', 'success');
CREATE TYPE "logs_source_type" AS ENUM ('file', 'cli', 'system');
CREATE TYPE "mail_preferences_display_density_type" AS ENUM ('comfortable', 'default', 'compact');
CREATE TYPE "mail_preferences_theme_type" AS ENUM ('light', 'dark', 'system');
CREATE TYPE "mail_preferences_language_type" AS ENUM ('en', 'fr', 'de', 'es', 'ja');
CREATE TYPE "mail_preferences_default_reply_behavior_type" AS ENUM ('reply', 'replyAll');
CREATE TYPE "mail_preferences_auto_advance_type" AS ENUM ('newer', 'older', 'back');
CREATE TYPE "mail_preferences_notification_sound_type" AS ENUM ('default', 'subtle', 'none');
CREATE TYPE "print_devices_status_type" AS ENUM ('online', 'offline', 'warning');
CREATE TYPE "coupons_status_type" AS ENUM ('Active', 'Scheduled', 'Expired');
CREATE TYPE "coupons_discount_type_type" AS ENUM ('fixed_amount', 'percentage');
CREATE TYPE "product_variants_status_type" AS ENUM ('active', 'inactive', 'draft');
CREATE TYPE "query_logs_status_type" AS ENUM ('completed', 'failed', 'slow');
CREATE TYPE "receipts_status_type" AS ENUM ('success', 'failed', 'warning');
CREATE TYPE "repositories_owner_type_type" AS ENUM ('user', 'organization');
CREATE TYPE "repositories_visibility_type" AS ENUM ('public', 'private', 'internal');
CREATE TYPE "check_runs_status_type" AS ENUM ('queued', 'in_progress', 'completed');
CREATE TYPE "check_runs_conclusion_type" AS ENUM ('success', 'failure', 'neutral', 'cancelled', 'timed_out', 'action_required', 'skipped', 'stale');
CREATE TYPE "milestones_state_type" AS ENUM ('open', 'closed');
CREATE TYPE "repository_mirrors_direction_type" AS ENUM ('pull', 'push');
CREATE TYPE "repository_mirrors_provider_type" AS ENUM ('github', 'gitlab', 'git');
CREATE TYPE "requests_method_type" AS ENUM ('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD');
CREATE TYPE "shipping_methods_status_type" AS ENUM ('active', 'inactive', 'draft');
CREATE TYPE "shipping_zones_status_type" AS ENUM ('active', 'inactive', 'draft');
CREATE TYPE "tax_rates_region_type" AS ENUM ('North America', 'South America', 'Europe', 'Asia', 'Africa', 'Oceania', 'Antarctica');
CREATE TYPE "tax_rates_status_type" AS ENUM ('active', 'inactive');
CREATE TYPE "access_tokens_selection_type" AS ENUM ('all', 'organization', 'selected');
CREATE TYPE "access_token_permissions_scope_type" AS ENUM ('contents', 'issues', 'pull_requests', 'webhooks', 'administration', 'members', 'organization_administration', 'billing');
CREATE TYPE "access_token_permissions_level_type" AS ENUM ('read', 'write', 'admin');
CREATE TYPE "customers_status_type" AS ENUM ('Active', 'Inactive');
CREATE TYPE "carts_status_type" AS ENUM ('active', 'abandoned', 'converted', 'expired');
CREATE TYPE "drivers_status_type" AS ENUM ('active', 'on_delivery', 'on_break');
CREATE TYPE "issues_state_type" AS ENUM ('open', 'closed');
CREATE TYPE "issues_state_reason_type" AS ENUM ('completed', 'not_planned', 'duplicate');
CREATE TYPE "issue_comments_commentable_type_type" AS ENUM ('issue', 'pull_request');
CREATE TYPE "notification_deliveries_channel_type" AS ENUM ('email', 'sms', 'chat', 'database', 'push', 'broadcast');
CREATE TYPE "notification_deliveries_status_type" AS ENUM ('pending', 'sent', 'delivered', 'failed');
CREATE TYPE "notification_mutes_subject_type_type" AS ENUM ('repository', 'organization', 'issue', 'pull_request');
CREATE TYPE "notification_subscriptions_subject_type_type" AS ENUM ('issue', 'pull_request', 'repository');
CREATE TYPE "notification_subscriptions_reason_type" AS ENUM ('review_requested', 'assigned', 'mentioned', 'team_mention', 'author', 'participating', 'watching');
CREATE TYPE "license_keys_template_type" AS ENUM ('Standard License', 'Premium License', 'Enterprise License');
CREATE TYPE "license_keys_status_type" AS ENUM ('active', 'inactive', 'unassigned');
CREATE TYPE "org_members_role_type" AS ENUM ('owner', 'admin', 'member');
CREATE TYPE "payments_method_type" AS ENUM ('cash', 'creditCard', 'debitCard', 'paypal', 'applePay', 'googlePay', 'bankTransfer', 'giftCard');
CREATE TYPE "payments_status_type" AS ENUM ('pending', 'processing', 'completed', 'failed', 'refunded', 'partiallyRefunded', 'succeeded');
CREATE TYPE "posts_status_type" AS ENUM ('published', 'draft', 'archived');
CREATE TYPE "comments_status_type" AS ENUM ('pending', 'approved', 'spam', 'trash');
CREATE TYPE "pull_requests_state_type" AS ENUM ('open', 'closed', 'merged');
CREATE TYPE "pull_requests_mergeable_state_type" AS ENUM ('unknown', 'clean', 'dirty', 'blocked', 'behind');
CREATE TYPE "pull_request_reviews_state_type" AS ENUM ('pending', 'approved', 'changes_requested', 'commented', 'dismissed');
CREATE TYPE "pull_request_reviewers_reviewer_type_type" AS ENUM ('user', 'team');
CREATE TYPE "repo_collaborators_permission_type" AS ENUM ('read', 'triage', 'write', 'maintain', 'admin');
CREATE TYPE "review_threads_side_type" AS ENUM ('left', 'right');
CREATE TYPE "social_posts_platform_type" AS ENUM ('twitter', 'facebook', 'instagram', 'linkedin', 'tiktok', 'youtube');
CREATE TYPE "social_posts_status_type" AS ENUM ('draft', 'scheduled', 'published', 'failed');
CREATE TYPE "ssh_keys_key_type_type" AS ENUM ('ssh-ed25519', 'ssh-rsa', 'ecdsa-sha2-nistp256');
CREATE TYPE "subscribers_status_type" AS ENUM ('subscribed', 'unsubscribed', 'pending', 'bounced');
CREATE TYPE "campaign_sends_status_type" AS ENUM ('queued', 'sent', 'failed', 'bounced', 'complained');
CREATE TYPE "email_list_subscribers_status_type" AS ENUM ('subscribed', 'unsubscribed', 'pending', 'bounced');
CREATE TYPE "team_members_role_type" AS ENUM ('maintainer', 'member');
CREATE TYPE "timeline_entries_subject_type_type" AS ENUM ('issue', 'pull_request');
CREATE TYPE "timeline_entries_kind_type" AS ENUM ('closed', 'reopened', 'renamed', 'labeled', 'unlabeled', 'assigned', 'unassigned', 'milestoned', 'demilestoned', 'locked', 'unlocked', 'referenced', 'merged');
CREATE TYPE "waitlist_products_notification_preference_type" AS ENUM ('sms', 'email', 'both');
CREATE TYPE "waitlist_products_status_type" AS ENUM ('waiting', 'purchased', 'notified', 'cancelled');
CREATE TYPE "waitlist_restaurants_table_preference_type" AS ENUM ('indoor', 'bar', 'booth', 'no_preference');
CREATE TYPE "waitlist_restaurants_status_type" AS ENUM ('waiting', 'seated', 'cancelled', 'no_show');
CREATE TYPE "watches_subscription_type" AS ENUM ('all', 'participating', 'ignore');
CREATE TYPE "webhooks_content_type_type" AS ENUM ('application/json', 'application/x-www-form-urlencoded');
CREATE TYPE "websockets_type_type" AS ENUM ('disconnection', 'error', 'success');
