-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "merge_queue_entries" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "pull_request_id" bigint not null REFERENCES "pull_requests"("id") ON DELETE CASCADE,
  "base_branch" varchar(255) default 'main',
  "state" "merge_queue_entries_state_type" default 'queued',
  "position" integer default 0,
  "merge_sha" varchar(64) default '',
  "workflow_run_id" integer,
  "reason" text default '',
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "merge_queue_entries_branch_index" ON "merge_queue_entries" ("repository_id", "base_branch", "state");
CREATE UNIQUE INDEX IF NOT EXISTS "merge_queue_entries_pull_unique" ON "merge_queue_entries" ("pull_request_id");
CREATE UNIQUE INDEX IF NOT EXISTS "merge_queue_entries_uuid_unique" ON "merge_queue_entries" ("uuid");
