-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "test_monitors_condition_type" AS ENUM ('flaky', 'fail_rate', 'duration'); EXCEPTION WHEN duplicate_object THEN null; END $stacks$;
ALTER TYPE "test_monitors_condition_type" ADD VALUE IF NOT EXISTS 'flaky';
ALTER TYPE "test_monitors_condition_type" ADD VALUE IF NOT EXISTS 'fail_rate';
ALTER TYPE "test_monitors_condition_type" ADD VALUE IF NOT EXISTS 'duration';
DO $stacks$ BEGIN CREATE TYPE "test_monitors_state_type" AS ENUM ('ok', 'alarm'); EXCEPTION WHEN duplicate_object THEN null; END $stacks$;
ALTER TYPE "test_monitors_state_type" ADD VALUE IF NOT EXISTS 'ok';
ALTER TYPE "test_monitors_state_type" ADD VALUE IF NOT EXISTS 'alarm';
