-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "commit_statuses" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id"),
  "sha" varchar(64) not null,
  "context" varchar(255) not null,
  "state" "commit_statuses_state_type",
  "target_url" text,
  "description" varchar(500),
  "creator_id" integer,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "commit_statuses_sha_index" ON "commit_statuses" ("repository_id", "sha");
