-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "workflow_variables_scope_type_type" AS ENUM ('instance', 'owner', 'repository'); EXCEPTION WHEN duplicate_object THEN null; END $stacks$;
ALTER TYPE "workflow_variables_scope_type_type" ADD VALUE IF NOT EXISTS 'instance';
ALTER TYPE "workflow_variables_scope_type_type" ADD VALUE IF NOT EXISTS 'owner';
ALTER TYPE "workflow_variables_scope_type_type" ADD VALUE IF NOT EXISTS 'repository';
