-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "issue_comments" (
  "id" BIGSERIAL PRIMARY KEY,
  "commentable_type" "issue_comments_commentable_type_type" default 'issue',
  "commentable_id" integer not null,
  "author_id" bigint REFERENCES "users"("id"),
  "body" text not null,
  "edited_at" varchar(255),
  "edited_by_id" integer,
  "external_author" varchar(120),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "issue_comments_subject_index" ON "issue_comments" ("commentable_type", "commentable_id");
CREATE UNIQUE INDEX IF NOT EXISTS "issue_comments_uuid_unique" ON "issue_comments" ("uuid");
