-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "test_executions" (
  "id" BIGSERIAL PRIMARY KEY,
  "test_run_id" bigint not null REFERENCES "test_runs"("id") ON DELETE CASCADE,
  "managed_test_id" bigint not null REFERENCES "managed_tests"("id") ON DELETE CASCADE,
  "result" "test_executions_result_type" default 'passed',
  "duration_ms" integer default 0,
  "retries" integer default 0,
  "failure_message" text,
  "failure_stack" text,
  "workflow_job_id" integer,
  "tags" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "test_executions_run_index" ON "test_executions" ("test_run_id");
CREATE INDEX IF NOT EXISTS "test_executions_test_index" ON "test_executions" ("managed_test_id", "id");
CREATE UNIQUE INDEX IF NOT EXISTS "test_executions_uuid_unique" ON "test_executions" ("uuid");
