-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "runner_pool_repositories" (
  "id" BIGSERIAL PRIMARY KEY,
  "runner_pool_id" bigint not null REFERENCES "runner_pools"("id") ON DELETE CASCADE,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "runner_pool_repositories_pool_index" ON "runner_pool_repositories" ("runner_pool_id");
CREATE INDEX IF NOT EXISTS "runner_pool_repositories_repository_index" ON "runner_pool_repositories" ("repository_id");
