-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "deployment_statuses" (
  "id" BIGSERIAL PRIMARY KEY,
  "deployment_id" bigint not null REFERENCES "deployments"("id") ON DELETE CASCADE,
  "state" "deployment_statuses_state_type" not null default 'queued',
  "description" text,
  "url" varchar(500),
  "restored_deployment_id" integer,
  "actor_id" integer,
  "repository_id" integer,
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "deployment_statuses_deployment_index" ON "deployment_statuses" ("deployment_id", "id");
CREATE INDEX IF NOT EXISTS "deployment_statuses_repository_index" ON "deployment_statuses" ("repository_id");
