-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "team_repositories" (
  "id" BIGSERIAL PRIMARY KEY,
  "team_id" bigint not null REFERENCES "teams"("id") ON DELETE CASCADE,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "permission" "team_repositories_permission_type" not null default 'read',
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "team_repositories_team_repo_unique" ON "team_repositories" ("team_id", "repository_id");
CREATE INDEX IF NOT EXISTS "team_repositories_repository_index" ON "team_repositories" ("repository_id");
