-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "on_repository_dispatch" boolean default false;
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "repository_dispatch_types" varchar(500);
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "on_workflow_run" boolean default false;
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "workflow_run_workflows" text;
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "workflow_run_types" varchar(200);
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "workflow_run_branches" text;
