-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "push_subscriptions" (
  "id" BIGSERIAL PRIMARY KEY,
  "endpoint" text not null,
  "public_key" varchar(255) not null,
  "auth_secret" varchar(255) not null,
  "user_agent" varchar(500),
  "last_seen_at" timestamp,
  "user_id" bigint REFERENCES "users"("id") ON DELETE CASCADE,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "push_subscriptions_endpoint_unique" ON "push_subscriptions" ("endpoint");
