-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "reviewed_files" (
  "id" BIGSERIAL PRIMARY KEY,
  "pull_request_id" bigint not null REFERENCES "pull_requests"("id") ON DELETE CASCADE,
  "reviewer_id" bigint not null REFERENCES "users"("id") ON DELETE CASCADE,
  "path" text not null,
  "head_sha" varchar(40),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "reviewed_files_pr_user_path_index" ON "reviewed_files" ("pull_request_id", "reviewer_id", "path");
CREATE INDEX IF NOT EXISTS "reviewed_files_pr_user_index" ON "reviewed_files" ("pull_request_id", "reviewer_id");
