-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "workflow_secrets_scope_type_type" AS ENUM ('instance', 'pool', 'owner', 'repository', 'environment');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "workflow_secrets_scope_type_type" ADD VALUE IF NOT EXISTS 'instance';
ALTER TYPE "workflow_secrets_scope_type_type" ADD VALUE IF NOT EXISTS 'pool';
ALTER TYPE "workflow_secrets_scope_type_type" ADD VALUE IF NOT EXISTS 'owner';
ALTER TYPE "workflow_secrets_scope_type_type" ADD VALUE IF NOT EXISTS 'repository';
ALTER TYPE "workflow_secrets_scope_type_type" ADD VALUE IF NOT EXISTS 'environment';
ALTER TABLE "workflow_secrets" ALTER COLUMN "scope_type" DROP DEFAULT;
ALTER TABLE "workflow_secrets" ALTER COLUMN "scope_type" TYPE "workflow_secrets_scope_type_type" USING "scope_type"::"workflow_secrets_scope_type_type";
ALTER TABLE "workflow_secrets" ALTER COLUMN "scope_type" DROP NOT NULL;
ALTER TABLE "workflow_secrets" ALTER COLUMN "scope_type" SET default 'repository';
