-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_runs_redelivery_index" ON "workflow_runs" ("workflow_version_id", "event_ref", "head_sha", "event") WHERE event NOT IN ('workflow_dispatch', 'schedule');
