-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "call_inputs" text;
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "call_outputs" text;
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "call_secrets" text;
