-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "audit_events" ADD COLUMN IF NOT EXISTS "organization_id" integer;
ALTER TABLE "audit_events" ADD COLUMN IF NOT EXISTS "repository_id" integer;
ALTER TABLE "audit_events" ADD COLUMN IF NOT EXISTS "user_agent" varchar(255);
