-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "activity_events" (
  "id" BIGSERIAL PRIMARY KEY,
  "actor_id" bigint not null REFERENCES "users"("id") ON DELETE CASCADE,
  "verb" varchar(64) not null,
  "subject_type" varchar(32) not null,
  "subject_id" integer not null,
  "repository_id" bigint REFERENCES "repositories"("id") ON DELETE CASCADE,
  "organization_id" integer,
  "is_public" boolean not null default false,
  "detail" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "activity_events_actor_index" ON "activity_events" ("actor_id", "created_at");
CREATE INDEX IF NOT EXISTS "activity_events_repository_index" ON "activity_events" ("repository_id", "created_at");
CREATE INDEX IF NOT EXISTS "activity_events_subject_index" ON "activity_events" ("subject_type", "subject_id");
