-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "repo_topics" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "topic" varchar(50) not null,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "repo_topics_repo_topic_index" ON "repo_topics" ("repository_id", "topic");
CREATE INDEX IF NOT EXISTS "repo_topics_topic_index" ON "repo_topics" ("topic");
