-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "workflows_owner_type_type" AS ENUM ('user', 'organization');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "workflows_owner_type_type" ADD VALUE IF NOT EXISTS 'user';
ALTER TYPE "workflows_owner_type_type" ADD VALUE IF NOT EXISTS 'organization';
DO $stacks$ BEGIN CREATE TYPE "workflows_state_type" AS ENUM ('active', 'disabled');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "workflows_state_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "workflows_state_type" ADD VALUE IF NOT EXISTS 'disabled';
