-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "command" text;
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "uses" varchar(500);
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "inputs" text;
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "env" text;
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "working_directory" varchar(500);
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "shell" varchar(100);
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "condition" text;
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "step_id" varchar(100);
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "continue_on_error" boolean default false;
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "timeout_minutes" integer;
