-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "check_annotations" (
  "id" BIGSERIAL PRIMARY KEY,
  "check_run_id" bigint not null REFERENCES "check_runs"("id") ON DELETE CASCADE,
  "path" text not null,
  "start_line" integer not null,
  "end_line" integer not null,
  "side" "check_annotations_side_type" default 'right',
  "level" "check_annotations_level_type" default 'warning',
  "title" varchar(255),
  "message" text not null,
  "raw_details" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "check_annotations_run_path_index" ON "check_annotations" ("check_run_id", "path");
