-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "runners_stop_requested_type" AS ENUM ('graceful', 'forced'); EXCEPTION WHEN duplicate_object THEN null; END $stacks$;
ALTER TYPE "runners_stop_requested_type" ADD VALUE IF NOT EXISTS 'graceful';
ALTER TYPE "runners_stop_requested_type" ADD VALUE IF NOT EXISTS 'forced';
