-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "protected_branches" ADD COLUMN IF NOT EXISTS "require_up_to_date" boolean default false;
ALTER TABLE "protected_branches" ADD COLUMN IF NOT EXISTS "enforce_admins" boolean default true;
ALTER TABLE "protected_branches" ADD COLUMN IF NOT EXISTS "push_restrictions" text;
