-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "webhooks" ALTER COLUMN "events" DROP DEFAULT;
ALTER TABLE "webhooks" ALTER COLUMN "events" TYPE text USING "events"::text;
ALTER TABLE "webhooks" ALTER COLUMN "events" DROP NOT NULL;
ALTER TABLE "webhooks" ALTER COLUMN "events" SET default '*';
