-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_version_jobs" (
  "id" BIGSERIAL PRIMARY KEY,
  "workflow_version_id" bigint not null REFERENCES "workflow_versions"("id") ON DELETE CASCADE,
  "job_id" varchar(100) not null,
  "position" integer default 0,
  "name" varchar(200),
  "runs_on" varchar(500),
  "needs" text,
  "condition" text,
  "timeout_minutes" integer,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "workflow_version_jobs_version_index" ON "workflow_version_jobs" ("workflow_version_id", "position");
