-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "push_branches_ignore" text;
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "push_tags_ignore" text;
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "push_paths_ignore" text;
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "pull_request_branches_ignore" text;
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "pull_request_paths_ignore" text;
