-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "environment_reviewers" (
  "id" BIGSERIAL PRIMARY KEY,
  "environment_id" bigint not null REFERENCES "environments"("id") ON DELETE CASCADE,
  "user_id" bigint not null REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "environment_reviewers_unique" ON "environment_reviewers" ("environment_id", "user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "environment_reviewers_uuid_unique" ON "environment_reviewers" ("uuid");
