-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "runner_registration_tokens" (
  "id" BIGSERIAL PRIMARY KEY,
  "runner_pool_id" bigint not null REFERENCES "runner_pools"("id") ON DELETE CASCADE,
  "name" varchar(200) not null,
  "token_hash" varchar(64) not null,
  "runner_queue_id" integer,
  "first_used_at" varchar(40),
  "last_used_at" varchar(40),
  "uses" integer default 0,
  "revoked_at" varchar(40),
  "expires_at" varchar(40),
  "created_by_id" integer,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "runner_registration_tokens_hash_index" ON "runner_registration_tokens" ("token_hash");
CREATE INDEX IF NOT EXISTS "runner_registration_tokens_pool_index" ON "runner_registration_tokens" ("runner_pool_id");
CREATE UNIQUE INDEX IF NOT EXISTS "runner_registration_tokens_uuid_unique" ON "runner_registration_tokens" ("uuid");
