-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "runners_scope_type_type" AS ENUM ('instance', 'organization', 'repository');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "runners_scope_type_type" ADD VALUE IF NOT EXISTS 'instance';
ALTER TYPE "runners_scope_type_type" ADD VALUE IF NOT EXISTS 'organization';
ALTER TYPE "runners_scope_type_type" ADD VALUE IF NOT EXISTS 'repository';
DO $stacks$ BEGIN CREATE TYPE "runners_state_type" AS ENUM ('active', 'disabled');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "runners_state_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "runners_state_type" ADD VALUE IF NOT EXISTS 'disabled';
