-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "uploaded_by_job_id" integer;
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "upload_depth" integer default 0;
