DO $stacks$ BEGIN CREATE TYPE "digital_deliveries_status_type" AS ENUM ('active', 'inactive');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "digital_deliveries_status_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "digital_deliveries_status_type" ADD VALUE IF NOT EXISTS 'inactive';
DO $stacks$ BEGIN CREATE TYPE "email_lists_status_type" AS ENUM ('active', 'inactive', 'archived');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "email_lists_status_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "email_lists_status_type" ADD VALUE IF NOT EXISTS 'inactive';
ALTER TYPE "email_lists_status_type" ADD VALUE IF NOT EXISTS 'archived';
DO $stacks$ BEGIN CREATE TYPE "campaigns_type_type" AS ENUM ('email', 'sms', 'push', 'social', 'multi-channel');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "campaigns_type_type" ADD VALUE IF NOT EXISTS 'email';
ALTER TYPE "campaigns_type_type" ADD VALUE IF NOT EXISTS 'sms';
ALTER TYPE "campaigns_type_type" ADD VALUE IF NOT EXISTS 'push';
ALTER TYPE "campaigns_type_type" ADD VALUE IF NOT EXISTS 'social';
ALTER TYPE "campaigns_type_type" ADD VALUE IF NOT EXISTS 'multi-channel';
DO $stacks$ BEGIN CREATE TYPE "campaigns_status_type" AS ENUM ('draft', 'scheduled', 'sending', 'sent', 'paused', 'cancelled', 'failed', 'active', 'completed', 'archived');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "campaigns_status_type" ADD VALUE IF NOT EXISTS 'draft';
ALTER TYPE "campaigns_status_type" ADD VALUE IF NOT EXISTS 'scheduled';
ALTER TYPE "campaigns_status_type" ADD VALUE IF NOT EXISTS 'sending';
ALTER TYPE "campaigns_status_type" ADD VALUE IF NOT EXISTS 'sent';
ALTER TYPE "campaigns_status_type" ADD VALUE IF NOT EXISTS 'paused';
ALTER TYPE "campaigns_status_type" ADD VALUE IF NOT EXISTS 'cancelled';
ALTER TYPE "campaigns_status_type" ADD VALUE IF NOT EXISTS 'failed';
ALTER TYPE "campaigns_status_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "campaigns_status_type" ADD VALUE IF NOT EXISTS 'completed';
ALTER TYPE "campaigns_status_type" ADD VALUE IF NOT EXISTS 'archived';
DO $stacks$ BEGIN CREATE TYPE "logs_type_type" AS ENUM ('warning', 'error', 'info', 'success');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "logs_type_type" ADD VALUE IF NOT EXISTS 'warning';
ALTER TYPE "logs_type_type" ADD VALUE IF NOT EXISTS 'error';
ALTER TYPE "logs_type_type" ADD VALUE IF NOT EXISTS 'info';
ALTER TYPE "logs_type_type" ADD VALUE IF NOT EXISTS 'success';
DO $stacks$ BEGIN CREATE TYPE "logs_source_type" AS ENUM ('file', 'cli', 'system');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "logs_source_type" ADD VALUE IF NOT EXISTS 'file';
ALTER TYPE "logs_source_type" ADD VALUE IF NOT EXISTS 'cli';
ALTER TYPE "logs_source_type" ADD VALUE IF NOT EXISTS 'system';
DO $stacks$ BEGIN CREATE TYPE "mail_preferences_display_density_type" AS ENUM ('comfortable', 'default', 'compact');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "mail_preferences_display_density_type" ADD VALUE IF NOT EXISTS 'comfortable';
ALTER TYPE "mail_preferences_display_density_type" ADD VALUE IF NOT EXISTS 'default';
ALTER TYPE "mail_preferences_display_density_type" ADD VALUE IF NOT EXISTS 'compact';
DO $stacks$ BEGIN CREATE TYPE "mail_preferences_theme_type" AS ENUM ('light', 'dark', 'system');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "mail_preferences_theme_type" ADD VALUE IF NOT EXISTS 'light';
ALTER TYPE "mail_preferences_theme_type" ADD VALUE IF NOT EXISTS 'dark';
ALTER TYPE "mail_preferences_theme_type" ADD VALUE IF NOT EXISTS 'system';
DO $stacks$ BEGIN CREATE TYPE "mail_preferences_language_type" AS ENUM ('en', 'fr', 'de', 'es', 'ja');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "mail_preferences_language_type" ADD VALUE IF NOT EXISTS 'en';
ALTER TYPE "mail_preferences_language_type" ADD VALUE IF NOT EXISTS 'fr';
ALTER TYPE "mail_preferences_language_type" ADD VALUE IF NOT EXISTS 'de';
ALTER TYPE "mail_preferences_language_type" ADD VALUE IF NOT EXISTS 'es';
ALTER TYPE "mail_preferences_language_type" ADD VALUE IF NOT EXISTS 'ja';
DO $stacks$ BEGIN CREATE TYPE "mail_preferences_default_reply_behavior_type" AS ENUM ('reply', 'replyAll');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "mail_preferences_default_reply_behavior_type" ADD VALUE IF NOT EXISTS 'reply';
ALTER TYPE "mail_preferences_default_reply_behavior_type" ADD VALUE IF NOT EXISTS 'replyAll';
DO $stacks$ BEGIN CREATE TYPE "mail_preferences_auto_advance_type" AS ENUM ('newer', 'older', 'back');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "mail_preferences_auto_advance_type" ADD VALUE IF NOT EXISTS 'newer';
ALTER TYPE "mail_preferences_auto_advance_type" ADD VALUE IF NOT EXISTS 'older';
ALTER TYPE "mail_preferences_auto_advance_type" ADD VALUE IF NOT EXISTS 'back';
DO $stacks$ BEGIN CREATE TYPE "mail_preferences_notification_sound_type" AS ENUM ('default', 'subtle', 'none');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "mail_preferences_notification_sound_type" ADD VALUE IF NOT EXISTS 'default';
ALTER TYPE "mail_preferences_notification_sound_type" ADD VALUE IF NOT EXISTS 'subtle';
ALTER TYPE "mail_preferences_notification_sound_type" ADD VALUE IF NOT EXISTS 'none';
DO $stacks$ BEGIN CREATE TYPE "print_devices_status_type" AS ENUM ('online', 'offline', 'warning');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "print_devices_status_type" ADD VALUE IF NOT EXISTS 'online';
ALTER TYPE "print_devices_status_type" ADD VALUE IF NOT EXISTS 'offline';
ALTER TYPE "print_devices_status_type" ADD VALUE IF NOT EXISTS 'warning';
DO $stacks$ BEGIN CREATE TYPE "coupons_status_type" AS ENUM ('Active', 'Scheduled', 'Expired');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "coupons_status_type" ADD VALUE IF NOT EXISTS 'Active';
ALTER TYPE "coupons_status_type" ADD VALUE IF NOT EXISTS 'Scheduled';
ALTER TYPE "coupons_status_type" ADD VALUE IF NOT EXISTS 'Expired';
DO $stacks$ BEGIN CREATE TYPE "coupons_discount_type_type" AS ENUM ('fixed_amount', 'percentage');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "coupons_discount_type_type" ADD VALUE IF NOT EXISTS 'fixed_amount';
ALTER TYPE "coupons_discount_type_type" ADD VALUE IF NOT EXISTS 'percentage';
DO $stacks$ BEGIN CREATE TYPE "product_variants_status_type" AS ENUM ('active', 'inactive', 'draft');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "product_variants_status_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "product_variants_status_type" ADD VALUE IF NOT EXISTS 'inactive';
ALTER TYPE "product_variants_status_type" ADD VALUE IF NOT EXISTS 'draft';
DO $stacks$ BEGIN CREATE TYPE "query_logs_status_type" AS ENUM ('completed', 'failed', 'slow');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "query_logs_status_type" ADD VALUE IF NOT EXISTS 'completed';
ALTER TYPE "query_logs_status_type" ADD VALUE IF NOT EXISTS 'failed';
ALTER TYPE "query_logs_status_type" ADD VALUE IF NOT EXISTS 'slow';
DO $stacks$ BEGIN CREATE TYPE "receipts_status_type" AS ENUM ('success', 'failed', 'warning');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "receipts_status_type" ADD VALUE IF NOT EXISTS 'success';
ALTER TYPE "receipts_status_type" ADD VALUE IF NOT EXISTS 'failed';
ALTER TYPE "receipts_status_type" ADD VALUE IF NOT EXISTS 'warning';
DO $stacks$ BEGIN CREATE TYPE "repositories_owner_type_type" AS ENUM ('user', 'organization');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "repositories_owner_type_type" ADD VALUE IF NOT EXISTS 'user';
ALTER TYPE "repositories_owner_type_type" ADD VALUE IF NOT EXISTS 'organization';
DO $stacks$ BEGIN CREATE TYPE "repositories_visibility_type" AS ENUM ('public', 'private', 'internal');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "repositories_visibility_type" ADD VALUE IF NOT EXISTS 'public';
ALTER TYPE "repositories_visibility_type" ADD VALUE IF NOT EXISTS 'private';
ALTER TYPE "repositories_visibility_type" ADD VALUE IF NOT EXISTS 'internal';
DO $stacks$ BEGIN CREATE TYPE "check_runs_status_type" AS ENUM ('queued', 'in_progress', 'completed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "check_runs_status_type" ADD VALUE IF NOT EXISTS 'queued';
ALTER TYPE "check_runs_status_type" ADD VALUE IF NOT EXISTS 'in_progress';
ALTER TYPE "check_runs_status_type" ADD VALUE IF NOT EXISTS 'completed';
DO $stacks$ BEGIN CREATE TYPE "check_runs_conclusion_type" AS ENUM ('success', 'failure', 'neutral', 'cancelled', 'timed_out', 'action_required', 'skipped', 'stale');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "check_runs_conclusion_type" ADD VALUE IF NOT EXISTS 'success';
ALTER TYPE "check_runs_conclusion_type" ADD VALUE IF NOT EXISTS 'failure';
ALTER TYPE "check_runs_conclusion_type" ADD VALUE IF NOT EXISTS 'neutral';
ALTER TYPE "check_runs_conclusion_type" ADD VALUE IF NOT EXISTS 'cancelled';
ALTER TYPE "check_runs_conclusion_type" ADD VALUE IF NOT EXISTS 'timed_out';
ALTER TYPE "check_runs_conclusion_type" ADD VALUE IF NOT EXISTS 'action_required';
ALTER TYPE "check_runs_conclusion_type" ADD VALUE IF NOT EXISTS 'skipped';
ALTER TYPE "check_runs_conclusion_type" ADD VALUE IF NOT EXISTS 'stale';
DO $stacks$ BEGIN CREATE TYPE "milestones_state_type" AS ENUM ('open', 'closed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "milestones_state_type" ADD VALUE IF NOT EXISTS 'open';
ALTER TYPE "milestones_state_type" ADD VALUE IF NOT EXISTS 'closed';
DO $stacks$ BEGIN CREATE TYPE "repository_mirrors_direction_type" AS ENUM ('pull', 'push');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "repository_mirrors_direction_type" ADD VALUE IF NOT EXISTS 'pull';
ALTER TYPE "repository_mirrors_direction_type" ADD VALUE IF NOT EXISTS 'push';
DO $stacks$ BEGIN CREATE TYPE "repository_mirrors_provider_type" AS ENUM ('github', 'gitlab', 'git');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "repository_mirrors_provider_type" ADD VALUE IF NOT EXISTS 'github';
ALTER TYPE "repository_mirrors_provider_type" ADD VALUE IF NOT EXISTS 'gitlab';
ALTER TYPE "repository_mirrors_provider_type" ADD VALUE IF NOT EXISTS 'git';
DO $stacks$ BEGIN CREATE TYPE "requests_method_type" AS ENUM ('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "requests_method_type" ADD VALUE IF NOT EXISTS 'GET';
ALTER TYPE "requests_method_type" ADD VALUE IF NOT EXISTS 'POST';
ALTER TYPE "requests_method_type" ADD VALUE IF NOT EXISTS 'PUT';
ALTER TYPE "requests_method_type" ADD VALUE IF NOT EXISTS 'PATCH';
ALTER TYPE "requests_method_type" ADD VALUE IF NOT EXISTS 'DELETE';
ALTER TYPE "requests_method_type" ADD VALUE IF NOT EXISTS 'OPTIONS';
ALTER TYPE "requests_method_type" ADD VALUE IF NOT EXISTS 'HEAD';
DO $stacks$ BEGIN CREATE TYPE "shipping_methods_status_type" AS ENUM ('active', 'inactive', 'draft');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "shipping_methods_status_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "shipping_methods_status_type" ADD VALUE IF NOT EXISTS 'inactive';
ALTER TYPE "shipping_methods_status_type" ADD VALUE IF NOT EXISTS 'draft';
DO $stacks$ BEGIN CREATE TYPE "shipping_zones_status_type" AS ENUM ('active', 'inactive', 'draft');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "shipping_zones_status_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "shipping_zones_status_type" ADD VALUE IF NOT EXISTS 'inactive';
ALTER TYPE "shipping_zones_status_type" ADD VALUE IF NOT EXISTS 'draft';
DO $stacks$ BEGIN CREATE TYPE "tax_rates_region_type" AS ENUM ('North America', 'South America', 'Europe', 'Asia', 'Africa', 'Oceania', 'Antarctica');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "tax_rates_region_type" ADD VALUE IF NOT EXISTS 'North America';
ALTER TYPE "tax_rates_region_type" ADD VALUE IF NOT EXISTS 'South America';
ALTER TYPE "tax_rates_region_type" ADD VALUE IF NOT EXISTS 'Europe';
ALTER TYPE "tax_rates_region_type" ADD VALUE IF NOT EXISTS 'Asia';
ALTER TYPE "tax_rates_region_type" ADD VALUE IF NOT EXISTS 'Africa';
ALTER TYPE "tax_rates_region_type" ADD VALUE IF NOT EXISTS 'Oceania';
ALTER TYPE "tax_rates_region_type" ADD VALUE IF NOT EXISTS 'Antarctica';
DO $stacks$ BEGIN CREATE TYPE "tax_rates_status_type" AS ENUM ('active', 'inactive');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "tax_rates_status_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "tax_rates_status_type" ADD VALUE IF NOT EXISTS 'inactive';
DO $stacks$ BEGIN CREATE TYPE "access_tokens_selection_type" AS ENUM ('all', 'organization', 'selected');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "access_tokens_selection_type" ADD VALUE IF NOT EXISTS 'all';
ALTER TYPE "access_tokens_selection_type" ADD VALUE IF NOT EXISTS 'organization';
ALTER TYPE "access_tokens_selection_type" ADD VALUE IF NOT EXISTS 'selected';
DO $stacks$ BEGIN CREATE TYPE "access_token_permissions_scope_type" AS ENUM ('contents', 'issues', 'pull_requests', 'webhooks', 'administration', 'members', 'organization_administration', 'billing');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'contents';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'issues';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'pull_requests';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'webhooks';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'administration';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'members';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'organization_administration';
ALTER TYPE "access_token_permissions_scope_type" ADD VALUE IF NOT EXISTS 'billing';
DO $stacks$ BEGIN CREATE TYPE "access_token_permissions_level_type" AS ENUM ('read', 'write', 'admin');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "access_token_permissions_level_type" ADD VALUE IF NOT EXISTS 'read';
ALTER TYPE "access_token_permissions_level_type" ADD VALUE IF NOT EXISTS 'write';
ALTER TYPE "access_token_permissions_level_type" ADD VALUE IF NOT EXISTS 'admin';
DO $stacks$ BEGIN CREATE TYPE "customers_status_type" AS ENUM ('Active', 'Inactive');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "customers_status_type" ADD VALUE IF NOT EXISTS 'Active';
ALTER TYPE "customers_status_type" ADD VALUE IF NOT EXISTS 'Inactive';
DO $stacks$ BEGIN CREATE TYPE "carts_status_type" AS ENUM ('active', 'abandoned', 'converted', 'expired');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "carts_status_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "carts_status_type" ADD VALUE IF NOT EXISTS 'abandoned';
ALTER TYPE "carts_status_type" ADD VALUE IF NOT EXISTS 'converted';
ALTER TYPE "carts_status_type" ADD VALUE IF NOT EXISTS 'expired';
DO $stacks$ BEGIN CREATE TYPE "drivers_status_type" AS ENUM ('active', 'on_delivery', 'on_break');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "drivers_status_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "drivers_status_type" ADD VALUE IF NOT EXISTS 'on_delivery';
ALTER TYPE "drivers_status_type" ADD VALUE IF NOT EXISTS 'on_break';
DO $stacks$ BEGIN CREATE TYPE "issues_state_type" AS ENUM ('open', 'closed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "issues_state_type" ADD VALUE IF NOT EXISTS 'open';
ALTER TYPE "issues_state_type" ADD VALUE IF NOT EXISTS 'closed';
DO $stacks$ BEGIN CREATE TYPE "issues_state_reason_type" AS ENUM ('completed', 'not_planned', 'duplicate');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "issues_state_reason_type" ADD VALUE IF NOT EXISTS 'completed';
ALTER TYPE "issues_state_reason_type" ADD VALUE IF NOT EXISTS 'not_planned';
ALTER TYPE "issues_state_reason_type" ADD VALUE IF NOT EXISTS 'duplicate';
DO $stacks$ BEGIN CREATE TYPE "issue_comments_commentable_type_type" AS ENUM ('issue', 'pull_request');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "issue_comments_commentable_type_type" ADD VALUE IF NOT EXISTS 'issue';
ALTER TYPE "issue_comments_commentable_type_type" ADD VALUE IF NOT EXISTS 'pull_request';
DO $stacks$ BEGIN CREATE TYPE "notification_deliveries_channel_type" AS ENUM ('email', 'sms', 'chat', 'database', 'push', 'broadcast');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "notification_deliveries_channel_type" ADD VALUE IF NOT EXISTS 'email';
ALTER TYPE "notification_deliveries_channel_type" ADD VALUE IF NOT EXISTS 'sms';
ALTER TYPE "notification_deliveries_channel_type" ADD VALUE IF NOT EXISTS 'chat';
ALTER TYPE "notification_deliveries_channel_type" ADD VALUE IF NOT EXISTS 'database';
ALTER TYPE "notification_deliveries_channel_type" ADD VALUE IF NOT EXISTS 'push';
ALTER TYPE "notification_deliveries_channel_type" ADD VALUE IF NOT EXISTS 'broadcast';
DO $stacks$ BEGIN CREATE TYPE "notification_deliveries_status_type" AS ENUM ('pending', 'sent', 'delivered', 'failed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "notification_deliveries_status_type" ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE "notification_deliveries_status_type" ADD VALUE IF NOT EXISTS 'sent';
ALTER TYPE "notification_deliveries_status_type" ADD VALUE IF NOT EXISTS 'delivered';
ALTER TYPE "notification_deliveries_status_type" ADD VALUE IF NOT EXISTS 'failed';
DO $stacks$ BEGIN CREATE TYPE "notification_mutes_subject_type_type" AS ENUM ('repository', 'organization', 'issue', 'pull_request');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "notification_mutes_subject_type_type" ADD VALUE IF NOT EXISTS 'repository';
ALTER TYPE "notification_mutes_subject_type_type" ADD VALUE IF NOT EXISTS 'organization';
ALTER TYPE "notification_mutes_subject_type_type" ADD VALUE IF NOT EXISTS 'issue';
ALTER TYPE "notification_mutes_subject_type_type" ADD VALUE IF NOT EXISTS 'pull_request';
DO $stacks$ BEGIN CREATE TYPE "notification_subscriptions_subject_type_type" AS ENUM ('issue', 'pull_request', 'repository');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "notification_subscriptions_subject_type_type" ADD VALUE IF NOT EXISTS 'issue';
ALTER TYPE "notification_subscriptions_subject_type_type" ADD VALUE IF NOT EXISTS 'pull_request';
ALTER TYPE "notification_subscriptions_subject_type_type" ADD VALUE IF NOT EXISTS 'repository';
DO $stacks$ BEGIN CREATE TYPE "notification_subscriptions_reason_type" AS ENUM ('review_requested', 'assigned', 'mentioned', 'team_mention', 'author', 'participating', 'watching');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "notification_subscriptions_reason_type" ADD VALUE IF NOT EXISTS 'review_requested';
ALTER TYPE "notification_subscriptions_reason_type" ADD VALUE IF NOT EXISTS 'assigned';
ALTER TYPE "notification_subscriptions_reason_type" ADD VALUE IF NOT EXISTS 'mentioned';
ALTER TYPE "notification_subscriptions_reason_type" ADD VALUE IF NOT EXISTS 'team_mention';
ALTER TYPE "notification_subscriptions_reason_type" ADD VALUE IF NOT EXISTS 'author';
ALTER TYPE "notification_subscriptions_reason_type" ADD VALUE IF NOT EXISTS 'participating';
ALTER TYPE "notification_subscriptions_reason_type" ADD VALUE IF NOT EXISTS 'watching';
DO $stacks$ BEGIN CREATE TYPE "license_keys_template_type" AS ENUM ('Standard License', 'Premium License', 'Enterprise License');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "license_keys_template_type" ADD VALUE IF NOT EXISTS 'Standard License';
ALTER TYPE "license_keys_template_type" ADD VALUE IF NOT EXISTS 'Premium License';
ALTER TYPE "license_keys_template_type" ADD VALUE IF NOT EXISTS 'Enterprise License';
DO $stacks$ BEGIN CREATE TYPE "license_keys_status_type" AS ENUM ('active', 'inactive', 'unassigned');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "license_keys_status_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "license_keys_status_type" ADD VALUE IF NOT EXISTS 'inactive';
ALTER TYPE "license_keys_status_type" ADD VALUE IF NOT EXISTS 'unassigned';
DO $stacks$ BEGIN CREATE TYPE "org_members_role_type" AS ENUM ('owner', 'admin', 'member');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "org_members_role_type" ADD VALUE IF NOT EXISTS 'owner';
ALTER TYPE "org_members_role_type" ADD VALUE IF NOT EXISTS 'admin';
ALTER TYPE "org_members_role_type" ADD VALUE IF NOT EXISTS 'member';
DO $stacks$ BEGIN CREATE TYPE "payments_method_type" AS ENUM ('cash', 'creditCard', 'debitCard', 'paypal', 'applePay', 'googlePay', 'bankTransfer', 'giftCard');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "payments_method_type" ADD VALUE IF NOT EXISTS 'cash';
ALTER TYPE "payments_method_type" ADD VALUE IF NOT EXISTS 'creditCard';
ALTER TYPE "payments_method_type" ADD VALUE IF NOT EXISTS 'debitCard';
ALTER TYPE "payments_method_type" ADD VALUE IF NOT EXISTS 'paypal';
ALTER TYPE "payments_method_type" ADD VALUE IF NOT EXISTS 'applePay';
ALTER TYPE "payments_method_type" ADD VALUE IF NOT EXISTS 'googlePay';
ALTER TYPE "payments_method_type" ADD VALUE IF NOT EXISTS 'bankTransfer';
ALTER TYPE "payments_method_type" ADD VALUE IF NOT EXISTS 'giftCard';
DO $stacks$ BEGIN CREATE TYPE "payments_status_type" AS ENUM ('pending', 'processing', 'completed', 'failed', 'refunded', 'partiallyRefunded', 'succeeded');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "payments_status_type" ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE "payments_status_type" ADD VALUE IF NOT EXISTS 'processing';
ALTER TYPE "payments_status_type" ADD VALUE IF NOT EXISTS 'completed';
ALTER TYPE "payments_status_type" ADD VALUE IF NOT EXISTS 'failed';
ALTER TYPE "payments_status_type" ADD VALUE IF NOT EXISTS 'refunded';
ALTER TYPE "payments_status_type" ADD VALUE IF NOT EXISTS 'partiallyRefunded';
ALTER TYPE "payments_status_type" ADD VALUE IF NOT EXISTS 'succeeded';
DO $stacks$ BEGIN CREATE TYPE "posts_status_type" AS ENUM ('published', 'draft', 'archived');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "posts_status_type" ADD VALUE IF NOT EXISTS 'published';
ALTER TYPE "posts_status_type" ADD VALUE IF NOT EXISTS 'draft';
ALTER TYPE "posts_status_type" ADD VALUE IF NOT EXISTS 'archived';
DO $stacks$ BEGIN CREATE TYPE "comments_status_type" AS ENUM ('pending', 'approved', 'spam', 'trash');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "comments_status_type" ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE "comments_status_type" ADD VALUE IF NOT EXISTS 'approved';
ALTER TYPE "comments_status_type" ADD VALUE IF NOT EXISTS 'spam';
ALTER TYPE "comments_status_type" ADD VALUE IF NOT EXISTS 'trash';
DO $stacks$ BEGIN CREATE TYPE "pull_requests_state_type" AS ENUM ('open', 'closed', 'merged');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "pull_requests_state_type" ADD VALUE IF NOT EXISTS 'open';
ALTER TYPE "pull_requests_state_type" ADD VALUE IF NOT EXISTS 'closed';
ALTER TYPE "pull_requests_state_type" ADD VALUE IF NOT EXISTS 'merged';
DO $stacks$ BEGIN CREATE TYPE "pull_requests_mergeable_state_type" AS ENUM ('unknown', 'clean', 'dirty', 'blocked', 'behind');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "pull_requests_mergeable_state_type" ADD VALUE IF NOT EXISTS 'unknown';
ALTER TYPE "pull_requests_mergeable_state_type" ADD VALUE IF NOT EXISTS 'clean';
ALTER TYPE "pull_requests_mergeable_state_type" ADD VALUE IF NOT EXISTS 'dirty';
ALTER TYPE "pull_requests_mergeable_state_type" ADD VALUE IF NOT EXISTS 'blocked';
ALTER TYPE "pull_requests_mergeable_state_type" ADD VALUE IF NOT EXISTS 'behind';
DO $stacks$ BEGIN CREATE TYPE "pull_request_reviews_state_type" AS ENUM ('pending', 'approved', 'changes_requested', 'commented', 'dismissed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "pull_request_reviews_state_type" ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE "pull_request_reviews_state_type" ADD VALUE IF NOT EXISTS 'approved';
ALTER TYPE "pull_request_reviews_state_type" ADD VALUE IF NOT EXISTS 'changes_requested';
ALTER TYPE "pull_request_reviews_state_type" ADD VALUE IF NOT EXISTS 'commented';
ALTER TYPE "pull_request_reviews_state_type" ADD VALUE IF NOT EXISTS 'dismissed';
DO $stacks$ BEGIN CREATE TYPE "pull_request_reviewers_reviewer_type_type" AS ENUM ('user', 'team');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "pull_request_reviewers_reviewer_type_type" ADD VALUE IF NOT EXISTS 'user';
ALTER TYPE "pull_request_reviewers_reviewer_type_type" ADD VALUE IF NOT EXISTS 'team';
DO $stacks$ BEGIN CREATE TYPE "repo_collaborators_permission_type" AS ENUM ('read', 'triage', 'write', 'maintain', 'admin');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "repo_collaborators_permission_type" ADD VALUE IF NOT EXISTS 'read';
ALTER TYPE "repo_collaborators_permission_type" ADD VALUE IF NOT EXISTS 'triage';
ALTER TYPE "repo_collaborators_permission_type" ADD VALUE IF NOT EXISTS 'write';
ALTER TYPE "repo_collaborators_permission_type" ADD VALUE IF NOT EXISTS 'maintain';
ALTER TYPE "repo_collaborators_permission_type" ADD VALUE IF NOT EXISTS 'admin';
DO $stacks$ BEGIN CREATE TYPE "review_threads_side_type" AS ENUM ('left', 'right');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "review_threads_side_type" ADD VALUE IF NOT EXISTS 'left';
ALTER TYPE "review_threads_side_type" ADD VALUE IF NOT EXISTS 'right';
DO $stacks$ BEGIN CREATE TYPE "social_posts_platform_type" AS ENUM ('twitter', 'facebook', 'instagram', 'linkedin', 'tiktok', 'youtube');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "social_posts_platform_type" ADD VALUE IF NOT EXISTS 'twitter';
ALTER TYPE "social_posts_platform_type" ADD VALUE IF NOT EXISTS 'facebook';
ALTER TYPE "social_posts_platform_type" ADD VALUE IF NOT EXISTS 'instagram';
ALTER TYPE "social_posts_platform_type" ADD VALUE IF NOT EXISTS 'linkedin';
ALTER TYPE "social_posts_platform_type" ADD VALUE IF NOT EXISTS 'tiktok';
ALTER TYPE "social_posts_platform_type" ADD VALUE IF NOT EXISTS 'youtube';
DO $stacks$ BEGIN CREATE TYPE "social_posts_status_type" AS ENUM ('draft', 'scheduled', 'published', 'failed');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "social_posts_status_type" ADD VALUE IF NOT EXISTS 'draft';
ALTER TYPE "social_posts_status_type" ADD VALUE IF NOT EXISTS 'scheduled';
ALTER TYPE "social_posts_status_type" ADD VALUE IF NOT EXISTS 'published';
ALTER TYPE "social_posts_status_type" ADD VALUE IF NOT EXISTS 'failed';
DO $stacks$ BEGIN CREATE TYPE "ssh_keys_key_type_type" AS ENUM ('ssh-ed25519', 'ssh-rsa', 'ecdsa-sha2-nistp256');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "ssh_keys_key_type_type" ADD VALUE IF NOT EXISTS 'ssh-ed25519';
ALTER TYPE "ssh_keys_key_type_type" ADD VALUE IF NOT EXISTS 'ssh-rsa';
ALTER TYPE "ssh_keys_key_type_type" ADD VALUE IF NOT EXISTS 'ecdsa-sha2-nistp256';
DO $stacks$ BEGIN CREATE TYPE "subscribers_status_type" AS ENUM ('subscribed', 'unsubscribed', 'pending', 'bounced');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "subscribers_status_type" ADD VALUE IF NOT EXISTS 'subscribed';
ALTER TYPE "subscribers_status_type" ADD VALUE IF NOT EXISTS 'unsubscribed';
ALTER TYPE "subscribers_status_type" ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE "subscribers_status_type" ADD VALUE IF NOT EXISTS 'bounced';
DO $stacks$ BEGIN CREATE TYPE "campaign_sends_status_type" AS ENUM ('queued', 'sent', 'failed', 'bounced', 'complained');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "campaign_sends_status_type" ADD VALUE IF NOT EXISTS 'queued';
ALTER TYPE "campaign_sends_status_type" ADD VALUE IF NOT EXISTS 'sent';
ALTER TYPE "campaign_sends_status_type" ADD VALUE IF NOT EXISTS 'failed';
ALTER TYPE "campaign_sends_status_type" ADD VALUE IF NOT EXISTS 'bounced';
ALTER TYPE "campaign_sends_status_type" ADD VALUE IF NOT EXISTS 'complained';
DO $stacks$ BEGIN CREATE TYPE "email_list_subscribers_status_type" AS ENUM ('subscribed', 'unsubscribed', 'pending', 'bounced');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "email_list_subscribers_status_type" ADD VALUE IF NOT EXISTS 'subscribed';
ALTER TYPE "email_list_subscribers_status_type" ADD VALUE IF NOT EXISTS 'unsubscribed';
ALTER TYPE "email_list_subscribers_status_type" ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE "email_list_subscribers_status_type" ADD VALUE IF NOT EXISTS 'bounced';
DO $stacks$ BEGIN CREATE TYPE "team_members_role_type" AS ENUM ('maintainer', 'member');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "team_members_role_type" ADD VALUE IF NOT EXISTS 'maintainer';
ALTER TYPE "team_members_role_type" ADD VALUE IF NOT EXISTS 'member';
DO $stacks$ BEGIN CREATE TYPE "timeline_entries_subject_type_type" AS ENUM ('issue', 'pull_request');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "timeline_entries_subject_type_type" ADD VALUE IF NOT EXISTS 'issue';
ALTER TYPE "timeline_entries_subject_type_type" ADD VALUE IF NOT EXISTS 'pull_request';
DO $stacks$ BEGIN CREATE TYPE "timeline_entries_kind_type" AS ENUM ('closed', 'reopened', 'renamed', 'labeled', 'unlabeled', 'assigned', 'unassigned', 'milestoned', 'demilestoned', 'locked', 'unlocked', 'referenced', 'merged');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'closed';
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'reopened';
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'renamed';
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'labeled';
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'unlabeled';
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'assigned';
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'unassigned';
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'milestoned';
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'demilestoned';
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'locked';
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'unlocked';
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'referenced';
ALTER TYPE "timeline_entries_kind_type" ADD VALUE IF NOT EXISTS 'merged';
DO $stacks$ BEGIN CREATE TYPE "waitlist_products_notification_preference_type" AS ENUM ('sms', 'email', 'both');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "waitlist_products_notification_preference_type" ADD VALUE IF NOT EXISTS 'sms';
ALTER TYPE "waitlist_products_notification_preference_type" ADD VALUE IF NOT EXISTS 'email';
ALTER TYPE "waitlist_products_notification_preference_type" ADD VALUE IF NOT EXISTS 'both';
DO $stacks$ BEGIN CREATE TYPE "waitlist_products_status_type" AS ENUM ('waiting', 'purchased', 'notified', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "waitlist_products_status_type" ADD VALUE IF NOT EXISTS 'waiting';
ALTER TYPE "waitlist_products_status_type" ADD VALUE IF NOT EXISTS 'purchased';
ALTER TYPE "waitlist_products_status_type" ADD VALUE IF NOT EXISTS 'notified';
ALTER TYPE "waitlist_products_status_type" ADD VALUE IF NOT EXISTS 'cancelled';
DO $stacks$ BEGIN CREATE TYPE "waitlist_restaurants_table_preference_type" AS ENUM ('indoor', 'bar', 'booth', 'no_preference');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "waitlist_restaurants_table_preference_type" ADD VALUE IF NOT EXISTS 'indoor';
ALTER TYPE "waitlist_restaurants_table_preference_type" ADD VALUE IF NOT EXISTS 'bar';
ALTER TYPE "waitlist_restaurants_table_preference_type" ADD VALUE IF NOT EXISTS 'booth';
ALTER TYPE "waitlist_restaurants_table_preference_type" ADD VALUE IF NOT EXISTS 'no_preference';
DO $stacks$ BEGIN CREATE TYPE "waitlist_restaurants_status_type" AS ENUM ('waiting', 'seated', 'cancelled', 'no_show');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "waitlist_restaurants_status_type" ADD VALUE IF NOT EXISTS 'waiting';
ALTER TYPE "waitlist_restaurants_status_type" ADD VALUE IF NOT EXISTS 'seated';
ALTER TYPE "waitlist_restaurants_status_type" ADD VALUE IF NOT EXISTS 'cancelled';
ALTER TYPE "waitlist_restaurants_status_type" ADD VALUE IF NOT EXISTS 'no_show';
DO $stacks$ BEGIN CREATE TYPE "watches_subscription_type" AS ENUM ('all', 'participating', 'ignore');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "watches_subscription_type" ADD VALUE IF NOT EXISTS 'all';
ALTER TYPE "watches_subscription_type" ADD VALUE IF NOT EXISTS 'participating';
ALTER TYPE "watches_subscription_type" ADD VALUE IF NOT EXISTS 'ignore';
DO $stacks$ BEGIN CREATE TYPE "webhooks_content_type_type" AS ENUM ('application/json', 'application/x-www-form-urlencoded');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "webhooks_content_type_type" ADD VALUE IF NOT EXISTS 'application/json';
ALTER TYPE "webhooks_content_type_type" ADD VALUE IF NOT EXISTS 'application/x-www-form-urlencoded';
DO $stacks$ BEGIN CREATE TYPE "websockets_type_type" AS ENUM ('disconnection', 'error', 'success');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "websockets_type_type" ADD VALUE IF NOT EXISTS 'disconnection';
ALTER TYPE "websockets_type_type" ADD VALUE IF NOT EXISTS 'error';
ALTER TYPE "websockets_type_type" ADD VALUE IF NOT EXISTS 'success';
