ALTER TABLE "releases" ADD COLUMN IF NOT EXISTS "repository_id" integer;
ALTER TABLE "releases" ADD COLUMN IF NOT EXISTS "user_id" integer;
ALTER TABLE "releases" ADD COLUMN IF NOT EXISTS "tag_name" varchar(255);
ALTER TABLE "releases" ADD COLUMN IF NOT EXISTS "target_sha" varchar(40);
ALTER TABLE "releases" ADD COLUMN IF NOT EXISTS "name" varchar(255);
ALTER TABLE "releases" ADD COLUMN IF NOT EXISTS "is_prerelease" boolean default false;
ALTER TABLE "releases" ADD COLUMN IF NOT EXISTS "published_at" timestamp;
ALTER TABLE "releases" DROP CONSTRAINT IF EXISTS "releases_repository_id_fk";
ALTER TABLE "releases" ADD CONSTRAINT "releases_repository_id_fk" FOREIGN KEY ("repository_id") REFERENCES "repositories"("id");
ALTER TABLE "releases" DROP CONSTRAINT IF EXISTS "releases_user_id_fk";
ALTER TABLE "releases" ADD CONSTRAINT "releases_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id");
