-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "audit_events" DROP CONSTRAINT IF EXISTS "audit_events_actor_id_fk";
ALTER TABLE "audit_events" DROP CONSTRAINT IF EXISTS "audit_events_actor_id_fkey";
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_actor_id_fk" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE SET NULL;
