-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "workflow_jobs_kind_type" AS ENUM ('command', 'wait', 'block', 'trigger', 'await');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "workflow_jobs_kind_type" ADD VALUE IF NOT EXISTS 'command';
ALTER TYPE "workflow_jobs_kind_type" ADD VALUE IF NOT EXISTS 'wait';
ALTER TYPE "workflow_jobs_kind_type" ADD VALUE IF NOT EXISTS 'block';
ALTER TYPE "workflow_jobs_kind_type" ADD VALUE IF NOT EXISTS 'trigger';
ALTER TYPE "workflow_jobs_kind_type" ADD VALUE IF NOT EXISTS 'await';
ALTER TABLE "workflow_jobs" ALTER COLUMN "kind" DROP DEFAULT;
ALTER TABLE "workflow_jobs" ALTER COLUMN "kind" TYPE "workflow_jobs_kind_type" USING "kind"::"workflow_jobs_kind_type";
ALTER TABLE "workflow_jobs" ALTER COLUMN "kind" DROP NOT NULL;
ALTER TABLE "workflow_jobs" ALTER COLUMN "kind" SET default 'command';
