-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflows" (
  "id" BIGSERIAL PRIMARY KEY,
  "owner_type" "workflows_owner_type_type",
  "owner_id" integer not null,
  "repository_id" bigint REFERENCES "repositories"("id") ON DELETE CASCADE,
  "path" varchar(400),
  "name" varchar(200) not null,
  "state" "workflows_state_type" default 'active',
  "selector" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "workflows_repository_index" ON "workflows" ("repository_id", "state");
CREATE INDEX IF NOT EXISTS "workflows_owner_index" ON "workflows" ("owner_type", "owner_id", "state");
CREATE UNIQUE INDEX IF NOT EXISTS "workflows_uuid_unique" ON "workflows" ("uuid");
