-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "operations_status_type" AS ENUM ('queued', 'running', 'succeeded', 'failed', 'cancelled'); EXCEPTION WHEN duplicate_object THEN null; END $stacks$;
ALTER TYPE "operations_status_type" ADD VALUE IF NOT EXISTS 'queued';
ALTER TYPE "operations_status_type" ADD VALUE IF NOT EXISTS 'running';
ALTER TYPE "operations_status_type" ADD VALUE IF NOT EXISTS 'succeeded';
ALTER TYPE "operations_status_type" ADD VALUE IF NOT EXISTS 'failed';
ALTER TYPE "operations_status_type" ADD VALUE IF NOT EXISTS 'cancelled';
