-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "managed_tests" (
  "id" BIGSERIAL PRIMARY KEY,
  "test_suite_id" bigint not null REFERENCES "test_suites"("id") ON DELETE CASCADE,
  "scope" varchar(500) default '',
  "name" varchar(500) not null,
  "state" "managed_tests_state_type" default 'enabled',
  "muted_by_id" integer,
  "muted_at" varchar(40),
  "muted_reason" text,
  "review_at" varchar(40),
  "owner" varchar(200),
  "flaky" boolean default false,
  "flaky_reason" varchar(500),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "managed_tests_identity_index" ON "managed_tests" ("test_suite_id", "scope", "name");
CREATE INDEX IF NOT EXISTS "managed_tests_state_index" ON "managed_tests" ("test_suite_id", "state");
CREATE UNIQUE INDEX IF NOT EXISTS "managed_tests_uuid_unique" ON "managed_tests" ("uuid");
