-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "repository_languages" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "language" varchar(60) not null,
  "bytes" integer not null,
  "percent" integer,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "repository_languages_repo_index" ON "repository_languages" ("repository_id", "bytes");
CREATE INDEX IF NOT EXISTS "repository_languages_language_index" ON "repository_languages" ("language", "bytes");
