DO $$ BEGIN CREATE TYPE "notification_deliveries_channel_type" AS ENUM ('email', 'sms', 'chat', 'database', 'push', 'broadcast'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "notification_deliveries_status_type" AS ENUM ('pending', 'sent', 'delivered', 'failed'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DROP INDEX IF EXISTS "activities_activities_uuid_unique";
DROP INDEX IF EXISTS "analytics_events_analytics_events_uuid_unique";
DROP INDEX IF EXISTS "authors_authors_email_name_index";
DROP INDEX IF EXISTS "authors_authors_email_unique";
DROP INDEX IF EXISTS "authors_authors_uuid_unique";
DROP INDEX IF EXISTS "boards_boards_uuid_unique";
DROP INDEX IF EXISTS "board_columns_board_columns_uuid_unique";
DROP INDEX IF EXISTS "campaigns_campaigns_uuid_unique";
DROP INDEX IF EXISTS "campaign_sends_campaign_sends_uuid_unique";
DROP INDEX IF EXISTS "cards_cards_uuid_unique";
DROP INDEX IF EXISTS "card_comments_card_comments_uuid_unique";
DROP INDEX IF EXISTS "carts_carts_uuid_unique";
DROP INDEX IF EXISTS "cart_items_cart_items_uuid_unique";
DROP INDEX IF EXISTS "categories_categories_uuid_unique";
DROP INDEX IF EXISTS "check_runs_check_runs_head_index";
DROP INDEX IF EXISTS "check_runs_check_runs_name_index";
DROP INDEX IF EXISTS "check_runs_check_runs_uuid_unique";
DROP INDEX IF EXISTS "coupons_coupons_code_unique";
DROP INDEX IF EXISTS "coupons_coupons_uuid_unique";
ALTER TABLE "coupons" ALTER COLUMN "is_active" TYPE boolean USING "is_active"::boolean;
ALTER TABLE "coupons" ALTER COLUMN "is_active" SET NOT NULL;
ALTER TABLE "coupons" ALTER COLUMN "is_active" SET default true;
DROP INDEX IF EXISTS "customers_customers_email_unique";
DROP INDEX IF EXISTS "customers_customers_uuid_unique";
DROP INDEX IF EXISTS "delivery_routes_delivery_routes_uuid_unique";
DROP INDEX IF EXISTS "deployments_deployments_uuid_unique";
DROP INDEX IF EXISTS "digital_deliveries_digital_deliveries_uuid_unique";
ALTER TABLE "digital_deliveries" ALTER COLUMN "requires_login" TYPE boolean USING "requires_login"::boolean;
ALTER TABLE "digital_deliveries" ALTER COLUMN "requires_login" DROP NOT NULL;
ALTER TABLE "digital_deliveries" ALTER COLUMN "requires_login" SET default false;
ALTER TABLE "digital_deliveries" ALTER COLUMN "automatic_delivery" TYPE boolean USING "automatic_delivery"::boolean;
ALTER TABLE "digital_deliveries" ALTER COLUMN "automatic_delivery" DROP NOT NULL;
ALTER TABLE "digital_deliveries" ALTER COLUMN "automatic_delivery" SET default false;
DROP INDEX IF EXISTS "drivers_drivers_uuid_unique";
DROP INDEX IF EXISTS "email_lists_email_lists_slug_unique";
DROP INDEX IF EXISTS "email_lists_email_lists_uuid_unique";
DROP INDEX IF EXISTS "email_list_subscribers_email_list_subscribers_uuid_unique";
DROP INDEX IF EXISTS "gift_cards_gift_cards_code_unique";
DROP INDEX IF EXISTS "gift_cards_gift_cards_uuid_unique";
ALTER TABLE "gift_cards" ALTER COLUMN "is_active" TYPE boolean USING "is_active"::boolean;
ALTER TABLE "gift_cards" ALTER COLUMN "is_active" DROP NOT NULL;
ALTER TABLE "gift_cards" ALTER COLUMN "is_active" SET default true;
DROP INDEX IF EXISTS "gpg_keys_gpg_keys_key_id_index";
DROP INDEX IF EXISTS "gpg_keys_gpg_keys_key_id_unique";
DROP INDEX IF EXISTS "issues_issues_repo_number_index";
DROP INDEX IF EXISTS "issues_issues_repo_state_index";
DROP INDEX IF EXISTS "issues_issues_uuid_unique";
ALTER TABLE "issues" ALTER COLUMN "locked" TYPE boolean USING "locked"::boolean;
ALTER TABLE "issues" ALTER COLUMN "locked" DROP NOT NULL;
ALTER TABLE "issues" ALTER COLUMN "locked" SET default false;
ALTER TABLE "issues" ALTER COLUMN "is_pull_request" TYPE boolean USING "is_pull_request"::boolean;
ALTER TABLE "issues" ALTER COLUMN "is_pull_request" DROP NOT NULL;
ALTER TABLE "issues" ALTER COLUMN "is_pull_request" SET default false;
DROP INDEX IF EXISTS "issue_assignees_issue_assignees_issue_index";
DROP INDEX IF EXISTS "issue_comments_issue_comments_subject_index";
DROP INDEX IF EXISTS "issue_comments_issue_comments_uuid_unique";
DROP INDEX IF EXISTS "issue_labels_issue_labels_issue_index";
DROP INDEX IF EXISTS "labels_labels_uuid_unique";
DROP INDEX IF EXISTS "license_keys_license_keys_key_unique";
DROP INDEX IF EXISTS "license_keys_license_keys_uuid_unique";
DROP INDEX IF EXISTS "loyalty_points_loyalty_points_uuid_unique";
DROP INDEX IF EXISTS "loyalty_rewards_loyalty_rewards_uuid_unique";
DROP INDEX IF EXISTS "mail_preferences_mail_preferences_mailbox_unique";
ALTER TABLE "mail_preferences" ALTER COLUMN "send_and_archive" TYPE boolean USING "send_and_archive"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "send_and_archive" SET NOT NULL;
ALTER TABLE "mail_preferences" ALTER COLUMN "send_and_archive" SET default true;
ALTER TABLE "mail_preferences" ALTER COLUMN "desktop_notifications" TYPE boolean USING "desktop_notifications"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "desktop_notifications" SET NOT NULL;
ALTER TABLE "mail_preferences" ALTER COLUMN "desktop_notifications" SET default true;
ALTER TABLE "mail_preferences" ALTER COLUMN "notification_preview" TYPE boolean USING "notification_preview"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "notification_preview" SET NOT NULL;
ALTER TABLE "mail_preferences" ALTER COLUMN "notification_preview" SET default true;
ALTER TABLE "mail_preferences" ALTER COLUMN "load_remote_images" TYPE boolean USING "load_remote_images"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "load_remote_images" SET NOT NULL;
ALTER TABLE "mail_preferences" ALTER COLUMN "load_remote_images" SET default false;
ALTER TABLE "mail_preferences" ALTER COLUMN "show_external_content" TYPE boolean USING "show_external_content"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "show_external_content" SET NOT NULL;
ALTER TABLE "mail_preferences" ALTER COLUMN "show_external_content" SET default false;
ALTER TABLE "mail_preferences" ALTER COLUMN "vacation_enabled" TYPE boolean USING "vacation_enabled"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "vacation_enabled" SET NOT NULL;
ALTER TABLE "mail_preferences" ALTER COLUMN "vacation_enabled" SET default false;
DROP INDEX IF EXISTS "manufacturers_manufacturers_manufacturer_unique";
DROP INDEX IF EXISTS "manufacturers_manufacturers_uuid_unique";
DROP INDEX IF EXISTS "milestones_milestones_repo_index";
DROP INDEX IF EXISTS "notifications_idx_notifications_user";
DROP INDEX IF EXISTS "notifications_notifications_uuid_unique";
ALTER TABLE "notifications" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER TABLE "notifications" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "notifications" ALTER COLUMN "data" TYPE varchar(255) USING "data"::varchar(255);
ALTER TABLE "notifications" ALTER COLUMN "data" SET NOT NULL;
ALTER TABLE "notifications" ALTER COLUMN "data" DROP DEFAULT;
ALTER TABLE "notifications" ALTER COLUMN "user_id" TYPE bigint USING "user_id"::bigint;
ALTER TABLE "notifications" ALTER COLUMN "user_id" DROP NOT NULL;
ALTER TABLE "notifications" ALTER COLUMN "user_id" DROP DEFAULT;
ALTER TABLE "notifications" ALTER COLUMN "created_at" TYPE timestamp USING "created_at"::timestamp;
ALTER TABLE "notifications" ALTER COLUMN "created_at" SET NOT NULL;
ALTER TABLE "notifications" ALTER COLUMN "created_at" SET default CURRENT_TIMESTAMP;
ALTER TABLE "notification_deliveries" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER TABLE "notification_deliveries" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "notification_deliveries" ALTER COLUMN "channel" TYPE "notification_deliveries_channel_type" USING "channel"::"notification_deliveries_channel_type";
ALTER TABLE "notification_deliveries" ALTER COLUMN "channel" SET NOT NULL;
ALTER TABLE "notification_deliveries" ALTER COLUMN "channel" DROP DEFAULT;
ALTER TABLE "notification_deliveries" ALTER COLUMN "recipient" TYPE text USING "recipient"::text;
ALTER TABLE "notification_deliveries" ALTER COLUMN "recipient" SET NOT NULL;
ALTER TABLE "notification_deliveries" ALTER COLUMN "recipient" DROP DEFAULT;
ALTER TABLE "notification_deliveries" ALTER COLUMN "status" TYPE "notification_deliveries_status_type" USING "status"::"notification_deliveries_status_type";
ALTER TABLE "notification_deliveries" ALTER COLUMN "status" SET NOT NULL;
ALTER TABLE "notification_deliveries" ALTER COLUMN "status" SET default 'pending';
ALTER TABLE "notification_deliveries" ALTER COLUMN "metadata" TYPE varchar(255) USING "metadata"::varchar(255);
ALTER TABLE "notification_deliveries" ALTER COLUMN "metadata" DROP NOT NULL;
ALTER TABLE "notification_deliveries" ALTER COLUMN "metadata" DROP DEFAULT;
ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" TYPE timestamp USING "created_at"::timestamp;
ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" SET NOT NULL;
ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" SET default CURRENT_TIMESTAMP;
DROP INDEX IF EXISTS "notification_subscriptions_notification_subscriptions_subject_i";
DROP INDEX IF EXISTS "notification_subscriptions_notification_subscriptions_user_inde";
ALTER TABLE "notification_subscriptions" ALTER COLUMN "unsubscribed" TYPE boolean USING "unsubscribed"::boolean;
ALTER TABLE "notification_subscriptions" ALTER COLUMN "unsubscribed" DROP NOT NULL;
ALTER TABLE "notification_subscriptions" ALTER COLUMN "unsubscribed" SET default false;
DROP INDEX IF EXISTS "orders_orders_uuid_unique";
DROP INDEX IF EXISTS "order_idempotency_order_idempotency_idempotency_key_unique";
DROP INDEX IF EXISTS "organizations_organizations_handle_index";
DROP INDEX IF EXISTS "organizations_organizations_handle_unique";
DROP INDEX IF EXISTS "organizations_organizations_uuid_unique";
DROP INDEX IF EXISTS "org_members_org_members_org_user_index";
DROP INDEX IF EXISTS "pages_pages_uuid_unique";
DROP INDEX IF EXISTS "payments_payments_transaction_id_unique";
DROP INDEX IF EXISTS "payments_payments_uuid_unique";
DROP INDEX IF EXISTS "payment_methods_payment_methods_uuid_unique";
DROP INDEX IF EXISTS "payment_products_payment_products_uuid_unique";
DROP INDEX IF EXISTS "payment_transactions_payment_transactions_uuid_unique";
DROP INDEX IF EXISTS "print_devices_print_devices_uuid_unique";
DROP INDEX IF EXISTS "products_products_uuid_unique";
DROP INDEX IF EXISTS "product_units_product_units_uuid_unique";
DROP INDEX IF EXISTS "product_variants_product_variants_uuid_unique";
DROP INDEX IF EXISTS "protected_branches_protected_branches_repo_index";
ALTER TABLE "protected_branches" ALTER COLUMN "dismiss_stale_reviews" TYPE boolean USING "dismiss_stale_reviews"::boolean;
ALTER TABLE "protected_branches" ALTER COLUMN "dismiss_stale_reviews" DROP NOT NULL;
ALTER TABLE "protected_branches" ALTER COLUMN "dismiss_stale_reviews" SET default false;
ALTER TABLE "protected_branches" ALTER COLUMN "require_conversation_resolution" TYPE boolean USING "require_conversation_resolution"::boolean;
ALTER TABLE "protected_branches" ALTER COLUMN "require_conversation_resolution" DROP NOT NULL;
ALTER TABLE "protected_branches" ALTER COLUMN "require_conversation_resolution" SET default false;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_force_push" TYPE boolean USING "allow_force_push"::boolean;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_force_push" DROP NOT NULL;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_force_push" SET default false;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_deletion" TYPE boolean USING "allow_deletion"::boolean;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_deletion" DROP NOT NULL;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_deletion" SET default false;
ALTER TABLE "protected_branches" ALTER COLUMN "require_linear_history" TYPE boolean USING "require_linear_history"::boolean;
ALTER TABLE "protected_branches" ALTER COLUMN "require_linear_history" DROP NOT NULL;
ALTER TABLE "protected_branches" ALTER COLUMN "require_linear_history" SET default false;
DROP INDEX IF EXISTS "pull_requests_pull_requests_repo_number_index";
DROP INDEX IF EXISTS "pull_requests_pull_requests_repo_state_index";
DROP INDEX IF EXISTS "pull_requests_pull_requests_stack_index";
DROP INDEX IF EXISTS "pull_requests_pull_requests_uuid_unique";
ALTER TABLE "pull_requests" ALTER COLUMN "draft" TYPE boolean USING "draft"::boolean;
ALTER TABLE "pull_requests" ALTER COLUMN "draft" DROP NOT NULL;
ALTER TABLE "pull_requests" ALTER COLUMN "draft" SET default false;
ALTER TABLE "pull_request_reviewers" ALTER COLUMN "from_code_owners" TYPE boolean USING "from_code_owners"::boolean;
ALTER TABLE "pull_request_reviewers" ALTER COLUMN "from_code_owners" DROP NOT NULL;
ALTER TABLE "pull_request_reviewers" ALTER COLUMN "from_code_owners" SET default false;
DROP INDEX IF EXISTS "query_logs_query_logs_duration_index";
DROP INDEX IF EXISTS "query_logs_query_logs_executed_at_index";
DROP INDEX IF EXISTS "query_logs_query_logs_status_index";
DROP INDEX IF EXISTS "receipts_receipts_uuid_unique";
DROP INDEX IF EXISTS "releases_releases_uuid_unique";
DROP INDEX IF EXISTS "repo_collaborators_repo_collaborators_repo_user_index";
DROP INDEX IF EXISTS "repositories_repositories_owner_name_index";
DROP INDEX IF EXISTS "repositories_repositories_pushed_at_index";
DROP INDEX IF EXISTS "repositories_repositories_uuid_unique";
ALTER TABLE "repositories" ALTER COLUMN "is_fork" TYPE boolean USING "is_fork"::boolean;
ALTER TABLE "repositories" ALTER COLUMN "is_fork" DROP NOT NULL;
ALTER TABLE "repositories" ALTER COLUMN "is_fork" SET default false;
ALTER TABLE "repositories" ALTER COLUMN "is_archived" TYPE boolean USING "is_archived"::boolean;
ALTER TABLE "repositories" ALTER COLUMN "is_archived" DROP NOT NULL;
ALTER TABLE "repositories" ALTER COLUMN "is_archived" SET default false;
ALTER TABLE "repositories" ALTER COLUMN "is_template" TYPE boolean USING "is_template"::boolean;
ALTER TABLE "repositories" ALTER COLUMN "is_template" DROP NOT NULL;
ALTER TABLE "repositories" ALTER COLUMN "is_template" SET default false;
DROP INDEX IF EXISTS "repository_labels_repository_labels_repository_name_index";
DROP INDEX IF EXISTS "repository_labels_repository_labels_uuid_unique";
ALTER TABLE "repository_labels" ALTER COLUMN "is_default" TYPE boolean USING "is_default"::boolean;
ALTER TABLE "repository_labels" ALTER COLUMN "is_default" DROP NOT NULL;
ALTER TABLE "repository_labels" ALTER COLUMN "is_default" SET default false;
DROP INDEX IF EXISTS "repository_mirrors_repository_mirrors_due_index";
DROP INDEX IF EXISTS "repository_mirrors_repository_mirrors_repository_index";
DROP INDEX IF EXISTS "repository_mirrors_repository_mirrors_uuid_unique";
ALTER TABLE "repository_mirrors" ALTER COLUMN "enabled" TYPE boolean USING "enabled"::boolean;
ALTER TABLE "repository_mirrors" ALTER COLUMN "enabled" DROP NOT NULL;
ALTER TABLE "repository_mirrors" ALTER COLUMN "enabled" SET default true;
ALTER TABLE "repository_mirrors" ALTER COLUMN "sync_metadata" TYPE boolean USING "sync_metadata"::boolean;
ALTER TABLE "repository_mirrors" ALTER COLUMN "sync_metadata" DROP NOT NULL;
ALTER TABLE "repository_mirrors" ALTER COLUMN "sync_metadata" SET default false;
DROP INDEX IF EXISTS "reviews_reviews_uuid_unique";
DROP INDEX IF EXISTS "review_comments_review_comments_thread_index";
DROP INDEX IF EXISTS "review_comments_review_comments_uuid_unique";
DROP INDEX IF EXISTS "review_threads_review_threads_path_index";
DROP INDEX IF EXISTS "review_threads_review_threads_pr_index";
ALTER TABLE "review_threads" ALTER COLUMN "resolved" TYPE boolean USING "resolved"::boolean;
ALTER TABLE "review_threads" ALTER COLUMN "resolved" DROP NOT NULL;
ALTER TABLE "review_threads" ALTER COLUMN "resolved" SET default false;
ALTER TABLE "review_threads" ALTER COLUMN "outdated" TYPE boolean USING "outdated"::boolean;
ALTER TABLE "review_threads" ALTER COLUMN "outdated" DROP NOT NULL;
ALTER TABLE "review_threads" ALTER COLUMN "outdated" SET default false;
DROP INDEX IF EXISTS "shipping_methods_shipping_methods_uuid_unique";
DROP INDEX IF EXISTS "shipping_rates_shipping_rates_uuid_unique";
DROP INDEX IF EXISTS "shipping_zones_shipping_zones_uuid_unique";
DROP INDEX IF EXISTS "social_posts_social_posts_uuid_unique";
DROP INDEX IF EXISTS "ssh_keys_ssh_keys_fingerprint_index";
DROP INDEX IF EXISTS "ssh_keys_ssh_keys_fingerprint_unique";
DROP INDEX IF EXISTS "stars_stars_repo_user_index";
DROP INDEX IF EXISTS "subscribers_subscribers_email_unique";
DROP INDEX IF EXISTS "subscribers_subscribers_uuid_unique";
DROP INDEX IF EXISTS "subscriber_emails_subscriber_emails_uuid_unique";
DROP INDEX IF EXISTS "subscriptions_subscriptions_provider_id_unique";
DROP INDEX IF EXISTS "subscriptions_subscriptions_uuid_unique";
DROP INDEX IF EXISTS "tags_tags_name_unique";
DROP INDEX IF EXISTS "tags_tags_slug_unique";
DROP INDEX IF EXISTS "tags_tags_uuid_unique";
DROP INDEX IF EXISTS "tax_rates_tax_rates_uuid_unique";
ALTER TABLE "tax_rates" ALTER COLUMN "is_default" TYPE boolean USING "is_default"::boolean;
ALTER TABLE "tax_rates" ALTER COLUMN "is_default" DROP NOT NULL;
ALTER TABLE "tax_rates" ALTER COLUMN "is_default" SET default false;
DROP INDEX IF EXISTS "teams_teams_org_slug_index";
DROP INDEX IF EXISTS "teams_teams_uuid_unique";
DROP INDEX IF EXISTS "team_members_team_members_team_user_index";
DROP INDEX IF EXISTS "transactions_transactions_uuid_unique";
DROP INDEX IF EXISTS "users_users_email_unique";
DROP INDEX IF EXISTS "users_users_handle_index";
DROP INDEX IF EXISTS "users_users_handle_unique";
DROP INDEX IF EXISTS "users_users_uuid_unique";
ALTER TABLE "users" ALTER COLUMN "is_admin" TYPE boolean USING "is_admin"::boolean;
ALTER TABLE "users" ALTER COLUMN "is_admin" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "is_admin" SET default false;
DROP INDEX IF EXISTS "waitlist_products_waitlist_products_uuid_unique";
DROP INDEX IF EXISTS "waitlist_restaurants_waitlist_restaurants_uuid_unique";
DROP INDEX IF EXISTS "watches_watches_repo_user_index";
DROP INDEX IF EXISTS "webhooks_webhooks_repository_index";
DROP INDEX IF EXISTS "webhooks_webhooks_uuid_unique";
ALTER TABLE "webhooks" ALTER COLUMN "active" TYPE boolean USING "active"::boolean;
ALTER TABLE "webhooks" ALTER COLUMN "active" DROP NOT NULL;
ALTER TABLE "webhooks" ALTER COLUMN "active" SET default true;
DROP INDEX IF EXISTS "webhook_deliveries_webhook_deliveries_uuid_unique";
DROP INDEX IF EXISTS "webhook_deliveries_webhook_deliveries_webhook_index";
