-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "parallel_index" integer;
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "parallel_total" integer;
