-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "access_tokens" ADD COLUMN IF NOT EXISTS "limit_pull_requests_per_hour" integer;
ALTER TABLE "access_tokens" ADD COLUMN IF NOT EXISTS "limit_comments_per_hour" integer;
ALTER TABLE "access_tokens" ADD COLUMN IF NOT EXISTS "limit_reviews_per_hour" integer;
