-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "commit_statuses" DROP CONSTRAINT IF EXISTS "commit_statuses_repository_id_fk";
ALTER TABLE "commit_statuses" DROP CONSTRAINT IF EXISTS "commit_statuses_repository_id_fkey";
ALTER TABLE "commit_statuses" ADD CONSTRAINT "commit_statuses_repository_id_fk" FOREIGN KEY ("repository_id") REFERENCES "repositories"("id") ON DELETE CASCADE;
