-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "protected_branches" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "pattern" varchar(255) not null,
  "required_approvals" integer default 0,
  "dismiss_stale_reviews" boolean default false,
  "require_conversation_resolution" boolean default false,
  "required_checks" text,
  "allow_force_push" boolean default false,
  "allow_deletion" boolean default false,
  "require_linear_history" boolean default false,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "protected_branches_repo_index" ON "protected_branches" ("repository_id");
