-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "kind" "workflow_version_jobs_kind_type" default 'command';
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "settings" text;
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "group_label" varchar(200);
