-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "uses" varchar(500);
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "call_with" text;
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "call_secrets" text;
