CREATE TABLE IF NOT EXISTS "campaigns" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(255) not null,
  "description" text,
  "type" "campaigns_type_type" not null,
  "status" "campaigns_status_type" not null default 'draft',
  "subject" varchar(255),
  "template" varchar(255),
  "text" varchar(255),
  "from_name" varchar(100),
  "from_address" varchar(255),
  "email_list_id" integer REFERENCES "email_lists"("id"),
  "scheduled_at" timestamp,
  "sent_at" timestamp,
  "audience_size" integer default 0,
  "sent_count" integer default 0,
  "open_rate" integer,
  "click_rate" integer,
  "conversion_rate" integer,
  "budget" integer,
  "spent" integer default 0,
  "currency" varchar(3) not null default 'USD',
  "start_date" timestamp,
  "end_date" timestamp,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "campaigns_uuid_unique" ON "campaigns" ("uuid");
