-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "repository_contributors" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "name" varchar(200) not null,
  "email" varchar(200) not null,
  "commits" integer not null default 0,
  "user_id" integer,
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "repository_contributors_repo_index" ON "repository_contributors" ("repository_id", "commits");
CREATE UNIQUE INDEX IF NOT EXISTS "repository_contributors_repo_email_index" ON "repository_contributors" ("repository_id", "email");
CREATE INDEX IF NOT EXISTS "repository_contributors_user_index" ON "repository_contributors" ("user_id");
