-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_job_logs_sequence_index" ON "workflow_job_logs" ("workflow_job_id", "attempt", "sequence");
