-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "deployments" DROP CONSTRAINT IF EXISTS "deployments_repository_id_fk";
ALTER TABLE "deployments" DROP CONSTRAINT IF EXISTS "deployments_repository_id_fkey";
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_repository_id_fk" FOREIGN KEY ("repository_id") REFERENCES "repositories"("id") ON DELETE CASCADE;
