-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "runners" ADD COLUMN IF NOT EXISTS "runner_queue_id" bigint;
ALTER TABLE "runners" DROP CONSTRAINT IF EXISTS "runners_runner_queue_id_fk";
ALTER TABLE "runners" DROP CONSTRAINT IF EXISTS "runners_runner_queue_id_fkey";
ALTER TABLE "runners" ADD CONSTRAINT "runners_runner_queue_id_fk" FOREIGN KEY ("runner_queue_id") REFERENCES "runner_queues"("id");
