-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "plugin_policies_scope_type_type" AS ENUM ('instance', 'user', 'organization', 'pool');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "plugin_policies_scope_type_type" ADD VALUE IF NOT EXISTS 'instance';
ALTER TYPE "plugin_policies_scope_type_type" ADD VALUE IF NOT EXISTS 'user';
ALTER TYPE "plugin_policies_scope_type_type" ADD VALUE IF NOT EXISTS 'organization';
ALTER TYPE "plugin_policies_scope_type_type" ADD VALUE IF NOT EXISTS 'pool';
