-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "check_annotations_side_type" AS ENUM ('left', 'right');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "check_annotations_side_type" ADD VALUE IF NOT EXISTS 'left';
ALTER TYPE "check_annotations_side_type" ADD VALUE IF NOT EXISTS 'right';
DO $stacks$ BEGIN CREATE TYPE "check_annotations_level_type" AS ENUM ('notice', 'warning', 'failure');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "check_annotations_level_type" ADD VALUE IF NOT EXISTS 'notice';
ALTER TYPE "check_annotations_level_type" ADD VALUE IF NOT EXISTS 'warning';
ALTER TYPE "check_annotations_level_type" ADD VALUE IF NOT EXISTS 'failure';
DO $stacks$ BEGIN CREATE TYPE "commit_statuses_state_type" AS ENUM ('pending', 'success', 'failure', 'error');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "commit_statuses_state_type" ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE "commit_statuses_state_type" ADD VALUE IF NOT EXISTS 'success';
ALTER TYPE "commit_statuses_state_type" ADD VALUE IF NOT EXISTS 'failure';
ALTER TYPE "commit_statuses_state_type" ADD VALUE IF NOT EXISTS 'error';
