-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "deployment_statuses_state_type" AS ENUM ('queued', 'in_progress', 'active', 'failed', 'inactive', 'rolled_back');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "deployment_statuses_state_type" ADD VALUE IF NOT EXISTS 'queued';
ALTER TYPE "deployment_statuses_state_type" ADD VALUE IF NOT EXISTS 'in_progress';
ALTER TYPE "deployment_statuses_state_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "deployment_statuses_state_type" ADD VALUE IF NOT EXISTS 'failed';
ALTER TYPE "deployment_statuses_state_type" ADD VALUE IF NOT EXISTS 'inactive';
ALTER TYPE "deployment_statuses_state_type" ADD VALUE IF NOT EXISTS 'rolled_back';
