-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "org_members" DROP CONSTRAINT IF EXISTS "org_members_organization_id_fk";
ALTER TABLE "org_members" DROP CONSTRAINT IF EXISTS "org_members_organization_id_fkey";
ALTER TABLE "org_members" ADD CONSTRAINT "org_members_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE;
ALTER TABLE "org_members" DROP CONSTRAINT IF EXISTS "org_members_user_id_fk";
ALTER TABLE "org_members" DROP CONSTRAINT IF EXISTS "org_members_user_id_fkey";
ALTER TABLE "org_members" ADD CONSTRAINT "org_members_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;
