-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_jobs" (
  "id" BIGSERIAL PRIMARY KEY,
  "workflow_run_id" bigint not null REFERENCES "workflow_runs"("id") ON DELETE CASCADE,
  "job_id" varchar(100) not null,
  "name" varchar(200),
  "position" integer default 0,
  "state" "workflow_jobs_state_type" default 'blocked',
  "needs" text,
  "runs_on" varchar(500),
  "runner_id" varchar(200),
  "lease_expires_at" varchar(40),
  "started_at" varchar(40),
  "finished_at" varchar(40),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "workflow_jobs_run_index" ON "workflow_jobs" ("workflow_run_id", "position");
CREATE INDEX IF NOT EXISTS "workflow_jobs_state_index" ON "workflow_jobs" ("state", "id");
CREATE INDEX IF NOT EXISTS "workflow_jobs_lease_index" ON "workflow_jobs" ("lease_expires_at");
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_jobs_uuid_unique" ON "workflow_jobs" ("uuid");
