-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "runner_queues_state_type" AS ENUM ('active', 'paused'); EXCEPTION WHEN duplicate_object THEN null; END $stacks$;
ALTER TYPE "runner_queues_state_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "runner_queues_state_type" ADD VALUE IF NOT EXISTS 'paused';
