-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "deployments" ADD COLUMN IF NOT EXISTS "stages" varchar(500);
ALTER TABLE "deployments" ADD COLUMN IF NOT EXISTS "stage_index" integer default 0;
ALTER TABLE "deployments" ADD COLUMN IF NOT EXISTS "stage_held" boolean default false;
