-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "deployments_state_type" AS ENUM ('in_progress', 'active', 'failed', 'inactive');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "deployments_state_type" ADD VALUE IF NOT EXISTS 'in_progress';
ALTER TYPE "deployments_state_type" ADD VALUE IF NOT EXISTS 'active';
ALTER TYPE "deployments_state_type" ADD VALUE IF NOT EXISTS 'failed';
ALTER TYPE "deployments_state_type" ADD VALUE IF NOT EXISTS 'inactive';
