-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "runner_pools" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(100) not null,
  "slug" varchar(100) not null,
  "description" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "runner_pools_slug_index" ON "runner_pools" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "runner_pools_uuid_unique" ON "runner_pools" ("uuid");
