-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "condition" text;
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "condition_reason" text;
