-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "access_token_repositories" DROP CONSTRAINT IF EXISTS "access_token_repositories_access_token_id_fk";
ALTER TABLE "access_token_repositories" DROP CONSTRAINT IF EXISTS "access_token_repositories_access_token_id_fkey";
ALTER TABLE "access_token_repositories" ADD CONSTRAINT "access_token_repositories_access_token_id_fk" FOREIGN KEY ("access_token_id") REFERENCES "access_tokens"("id") ON DELETE CASCADE;
