-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "review_comments" (
  "id" BIGSERIAL PRIMARY KEY,
  "review_thread_id" bigint not null REFERENCES "review_threads"("id"),
  "review_id" bigint REFERENCES "pull_request_reviews"("id"),
  "author_id" bigint REFERENCES "users"("id"),
  "body" text not null,
  "suggestion" text,
  "edited_at" varchar(255),
  "external_id" integer,
  "external_author" varchar(120),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "review_comments_thread_index" ON "review_comments" ("review_thread_id");
CREATE INDEX IF NOT EXISTS "review_comments_external_index" ON "review_comments" ("external_id");
CREATE UNIQUE INDEX IF NOT EXISTS "review_comments_uuid_unique" ON "review_comments" ("uuid");
