-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "owner_aliases" (
  "id" BIGSERIAL PRIMARY KEY,
  "handle" varchar(39) not null,
  "owner_type" "owner_aliases_owner_type_type" not null,
  "owner_id" integer not null,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "owner_aliases_handle_index" ON "owner_aliases" ("handle");
CREATE UNIQUE INDEX IF NOT EXISTS "owner_aliases_handle_unique" ON "owner_aliases" ("handle");
