-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "notification_preferences" (
  "id" BIGSERIAL PRIMARY KEY,
  "user_id" bigint not null REFERENCES "users"("id"),
  "channel" varchar(50) not null,
  "enabled" boolean not null default true,
  "category" varchar(255),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
