-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "workflow_versions_intermediate_type" AS ENUM ('run', 'skip', 'cancel');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "workflow_versions_intermediate_type" ADD VALUE IF NOT EXISTS 'run';
ALTER TYPE "workflow_versions_intermediate_type" ADD VALUE IF NOT EXISTS 'skip';
ALTER TYPE "workflow_versions_intermediate_type" ADD VALUE IF NOT EXISTS 'cancel';
