-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "queue_circuit_state" (
  "id" BIGSERIAL PRIMARY KEY,
  "queue_name" varchar(255) not null,
  "success_count" integer default 0,
  "failure_count" integer default 0,
  "window_start" varchar(32),
  "paused_at" varchar(32),
  "resume_at" varchar(32),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "queue_circuit_state_queue_index" ON "queue_circuit_state" ("queue_name");
