-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "failed_jobs" (
  "id" BIGSERIAL PRIMARY KEY,
  "connection" varchar(100),
  "queue" varchar(100),
  "payload" text,
  "exception" text,
  "failed_at" varchar(255),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "failed_jobs_queue_index" ON "failed_jobs" ("queue", "failed_at");
