-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "runners" ADD COLUMN IF NOT EXISTS "runner_registration_token_id" bigint;
ALTER TABLE "runners" DROP CONSTRAINT IF EXISTS "runners_runner_registration_token_id_fk";
ALTER TABLE "runners" DROP CONSTRAINT IF EXISTS "runners_runner_registration_token_id_fkey";
ALTER TABLE "runners" ADD CONSTRAINT "runners_runner_registration_token_id_fk" FOREIGN KEY ("runner_registration_token_id") REFERENCES "runner_registration_tokens"("id");
