-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "default_shell" varchar(200);
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "default_working_directory" varchar(500);
