-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "runner_queues" (
  "id" BIGSERIAL PRIMARY KEY,
  "runner_pool_id" bigint not null REFERENCES "runner_pools"("id") ON DELETE CASCADE,
  "name" varchar(100) not null,
  "state" "runner_queues_state_type" default 'active',
  "paused_reason" varchar(500),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "runner_queues_pool_index" ON "runner_queues" ("runner_pool_id", "state");
CREATE INDEX IF NOT EXISTS "runner_queues_name_index" ON "runner_queues" ("name");
CREATE UNIQUE INDEX IF NOT EXISTS "runner_queues_uuid_unique" ON "runner_queues" ("uuid");
