-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "workflow_jobs_kind_type" AS ENUM ('command', 'wait', 'block', 'trigger');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "workflow_jobs_kind_type" ADD VALUE IF NOT EXISTS 'command';
ALTER TYPE "workflow_jobs_kind_type" ADD VALUE IF NOT EXISTS 'wait';
ALTER TYPE "workflow_jobs_kind_type" ADD VALUE IF NOT EXISTS 'block';
ALTER TYPE "workflow_jobs_kind_type" ADD VALUE IF NOT EXISTS 'trigger';
DO $stacks$ BEGIN CREATE TYPE "workflow_version_jobs_kind_type" AS ENUM ('command', 'wait', 'block', 'trigger');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "workflow_version_jobs_kind_type" ADD VALUE IF NOT EXISTS 'command';
ALTER TYPE "workflow_version_jobs_kind_type" ADD VALUE IF NOT EXISTS 'wait';
ALTER TYPE "workflow_version_jobs_kind_type" ADD VALUE IF NOT EXISTS 'block';
ALTER TYPE "workflow_version_jobs_kind_type" ADD VALUE IF NOT EXISTS 'trigger';
