ALTER TABLE "coupons" ALTER COLUMN "is_active" DROP DEFAULT;
ALTER TABLE "coupons" ALTER COLUMN "is_active" TYPE boolean USING "is_active"::boolean;
ALTER TABLE "coupons" ALTER COLUMN "is_active" SET NOT NULL;
ALTER TABLE "coupons" ALTER COLUMN "is_active" SET default true;
ALTER TABLE "digital_deliveries" ALTER COLUMN "requires_login" DROP DEFAULT;
ALTER TABLE "digital_deliveries" ALTER COLUMN "requires_login" TYPE boolean USING "requires_login"::boolean;
ALTER TABLE "digital_deliveries" ALTER COLUMN "requires_login" DROP NOT NULL;
ALTER TABLE "digital_deliveries" ALTER COLUMN "requires_login" SET default false;
ALTER TABLE "digital_deliveries" ALTER COLUMN "automatic_delivery" DROP DEFAULT;
ALTER TABLE "digital_deliveries" ALTER COLUMN "automatic_delivery" TYPE boolean USING "automatic_delivery"::boolean;
ALTER TABLE "digital_deliveries" ALTER COLUMN "automatic_delivery" DROP NOT NULL;
ALTER TABLE "digital_deliveries" ALTER COLUMN "automatic_delivery" SET default false;
ALTER TABLE "gift_cards" ALTER COLUMN "is_active" DROP DEFAULT;
ALTER TABLE "gift_cards" ALTER COLUMN "is_active" TYPE boolean USING "is_active"::boolean;
ALTER TABLE "gift_cards" ALTER COLUMN "is_active" DROP NOT NULL;
ALTER TABLE "gift_cards" ALTER COLUMN "is_active" SET default true;
ALTER TABLE "issues" ALTER COLUMN "locked" DROP DEFAULT;
ALTER TABLE "issues" ALTER COLUMN "locked" TYPE boolean USING "locked"::boolean;
ALTER TABLE "issues" ALTER COLUMN "locked" DROP NOT NULL;
ALTER TABLE "issues" ALTER COLUMN "locked" SET default false;
ALTER TABLE "issues" ALTER COLUMN "is_pull_request" DROP DEFAULT;
ALTER TABLE "issues" ALTER COLUMN "is_pull_request" TYPE boolean USING "is_pull_request"::boolean;
ALTER TABLE "issues" ALTER COLUMN "is_pull_request" DROP NOT NULL;
ALTER TABLE "issues" ALTER COLUMN "is_pull_request" SET default false;
ALTER TABLE "mail_preferences" ALTER COLUMN "send_and_archive" DROP DEFAULT;
ALTER TABLE "mail_preferences" ALTER COLUMN "send_and_archive" TYPE boolean USING "send_and_archive"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "send_and_archive" SET NOT NULL;
ALTER TABLE "mail_preferences" ALTER COLUMN "send_and_archive" SET default true;
ALTER TABLE "mail_preferences" ALTER COLUMN "desktop_notifications" DROP DEFAULT;
ALTER TABLE "mail_preferences" ALTER COLUMN "desktop_notifications" TYPE boolean USING "desktop_notifications"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "desktop_notifications" SET NOT NULL;
ALTER TABLE "mail_preferences" ALTER COLUMN "desktop_notifications" SET default true;
ALTER TABLE "mail_preferences" ALTER COLUMN "notification_preview" DROP DEFAULT;
ALTER TABLE "mail_preferences" ALTER COLUMN "notification_preview" TYPE boolean USING "notification_preview"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "notification_preview" SET NOT NULL;
ALTER TABLE "mail_preferences" ALTER COLUMN "notification_preview" SET default true;
ALTER TABLE "mail_preferences" ALTER COLUMN "load_remote_images" DROP DEFAULT;
ALTER TABLE "mail_preferences" ALTER COLUMN "load_remote_images" TYPE boolean USING "load_remote_images"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "load_remote_images" SET NOT NULL;
ALTER TABLE "mail_preferences" ALTER COLUMN "load_remote_images" SET default false;
ALTER TABLE "mail_preferences" ALTER COLUMN "show_external_content" DROP DEFAULT;
ALTER TABLE "mail_preferences" ALTER COLUMN "show_external_content" TYPE boolean USING "show_external_content"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "show_external_content" SET NOT NULL;
ALTER TABLE "mail_preferences" ALTER COLUMN "show_external_content" SET default false;
ALTER TABLE "mail_preferences" ALTER COLUMN "vacation_enabled" DROP DEFAULT;
ALTER TABLE "mail_preferences" ALTER COLUMN "vacation_enabled" TYPE boolean USING "vacation_enabled"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "vacation_enabled" SET NOT NULL;
ALTER TABLE "mail_preferences" ALTER COLUMN "vacation_enabled" SET default false;
ALTER TABLE "notifications" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "notifications" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER TABLE "notifications" ALTER COLUMN "data" DROP DEFAULT;
ALTER TABLE "notifications" ALTER COLUMN "data" TYPE varchar(255) USING "data"::varchar(255);
ALTER TABLE "notifications" ALTER COLUMN "data" SET NOT NULL;
ALTER TABLE "notifications" ALTER COLUMN "user_id" DROP DEFAULT;
ALTER TABLE "notifications" ALTER COLUMN "user_id" TYPE bigint USING "user_id"::bigint;
ALTER TABLE "notifications" ALTER COLUMN "user_id" DROP NOT NULL;
ALTER TABLE "notifications" ALTER COLUMN "created_at" DROP DEFAULT;
ALTER TABLE "notifications" ALTER COLUMN "created_at" TYPE timestamp USING "created_at"::timestamp;
ALTER TABLE "notifications" ALTER COLUMN "created_at" SET NOT NULL;
ALTER TABLE "notifications" ALTER COLUMN "created_at" SET default CURRENT_TIMESTAMP;
ALTER TABLE "notification_deliveries" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "notification_deliveries" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER TABLE "notification_deliveries" ALTER COLUMN "channel" DROP DEFAULT;
ALTER TABLE "notification_deliveries" ALTER COLUMN "channel" TYPE "notification_deliveries_channel_type" USING "channel"::"notification_deliveries_channel_type";
ALTER TABLE "notification_deliveries" ALTER COLUMN "channel" SET NOT NULL;
ALTER TABLE "notification_deliveries" ALTER COLUMN "recipient" DROP DEFAULT;
ALTER TABLE "notification_deliveries" ALTER COLUMN "recipient" TYPE text USING "recipient"::text;
ALTER TABLE "notification_deliveries" ALTER COLUMN "recipient" SET NOT NULL;
ALTER TABLE "notification_deliveries" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "notification_deliveries" ALTER COLUMN "status" TYPE "notification_deliveries_status_type" USING "status"::"notification_deliveries_status_type";
ALTER TABLE "notification_deliveries" ALTER COLUMN "status" SET NOT NULL;
ALTER TABLE "notification_deliveries" ALTER COLUMN "status" SET default 'pending';
ALTER TABLE "notification_deliveries" ALTER COLUMN "metadata" DROP DEFAULT;
ALTER TABLE "notification_deliveries" ALTER COLUMN "metadata" TYPE varchar(255) USING "metadata"::varchar(255);
ALTER TABLE "notification_deliveries" ALTER COLUMN "metadata" DROP NOT NULL;
ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" DROP DEFAULT;
ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" TYPE timestamp USING "created_at"::timestamp;
ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" SET NOT NULL;
ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" SET default CURRENT_TIMESTAMP;
ALTER TABLE "notification_subscriptions" ALTER COLUMN "unsubscribed" DROP DEFAULT;
ALTER TABLE "notification_subscriptions" ALTER COLUMN "unsubscribed" TYPE boolean USING "unsubscribed"::boolean;
ALTER TABLE "notification_subscriptions" ALTER COLUMN "unsubscribed" DROP NOT NULL;
ALTER TABLE "notification_subscriptions" ALTER COLUMN "unsubscribed" SET default false;
ALTER TABLE "protected_branches" ALTER COLUMN "dismiss_stale_reviews" DROP DEFAULT;
ALTER TABLE "protected_branches" ALTER COLUMN "dismiss_stale_reviews" TYPE boolean USING "dismiss_stale_reviews"::boolean;
ALTER TABLE "protected_branches" ALTER COLUMN "dismiss_stale_reviews" DROP NOT NULL;
ALTER TABLE "protected_branches" ALTER COLUMN "dismiss_stale_reviews" SET default false;
ALTER TABLE "protected_branches" ALTER COLUMN "require_conversation_resolution" DROP DEFAULT;
ALTER TABLE "protected_branches" ALTER COLUMN "require_conversation_resolution" TYPE boolean USING "require_conversation_resolution"::boolean;
ALTER TABLE "protected_branches" ALTER COLUMN "require_conversation_resolution" DROP NOT NULL;
ALTER TABLE "protected_branches" ALTER COLUMN "require_conversation_resolution" SET default false;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_force_push" DROP DEFAULT;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_force_push" TYPE boolean USING "allow_force_push"::boolean;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_force_push" DROP NOT NULL;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_force_push" SET default false;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_deletion" DROP DEFAULT;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_deletion" TYPE boolean USING "allow_deletion"::boolean;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_deletion" DROP NOT NULL;
ALTER TABLE "protected_branches" ALTER COLUMN "allow_deletion" SET default false;
ALTER TABLE "protected_branches" ALTER COLUMN "require_linear_history" DROP DEFAULT;
ALTER TABLE "protected_branches" ALTER COLUMN "require_linear_history" TYPE boolean USING "require_linear_history"::boolean;
ALTER TABLE "protected_branches" ALTER COLUMN "require_linear_history" DROP NOT NULL;
ALTER TABLE "protected_branches" ALTER COLUMN "require_linear_history" SET default false;
ALTER TABLE "pull_requests" ALTER COLUMN "draft" DROP DEFAULT;
ALTER TABLE "pull_requests" ALTER COLUMN "draft" TYPE boolean USING "draft"::boolean;
ALTER TABLE "pull_requests" ALTER COLUMN "draft" DROP NOT NULL;
ALTER TABLE "pull_requests" ALTER COLUMN "draft" SET default false;
ALTER TABLE "pull_request_reviewers" ALTER COLUMN "from_code_owners" DROP DEFAULT;
ALTER TABLE "pull_request_reviewers" ALTER COLUMN "from_code_owners" TYPE boolean USING "from_code_owners"::boolean;
ALTER TABLE "pull_request_reviewers" ALTER COLUMN "from_code_owners" DROP NOT NULL;
ALTER TABLE "pull_request_reviewers" ALTER COLUMN "from_code_owners" SET default false;
ALTER TABLE "repositories" ALTER COLUMN "is_fork" DROP DEFAULT;
ALTER TABLE "repositories" ALTER COLUMN "is_fork" TYPE boolean USING "is_fork"::boolean;
ALTER TABLE "repositories" ALTER COLUMN "is_fork" DROP NOT NULL;
ALTER TABLE "repositories" ALTER COLUMN "is_fork" SET default false;
ALTER TABLE "repositories" ALTER COLUMN "is_archived" DROP DEFAULT;
ALTER TABLE "repositories" ALTER COLUMN "is_archived" TYPE boolean USING "is_archived"::boolean;
ALTER TABLE "repositories" ALTER COLUMN "is_archived" DROP NOT NULL;
ALTER TABLE "repositories" ALTER COLUMN "is_archived" SET default false;
ALTER TABLE "repositories" ALTER COLUMN "is_template" DROP DEFAULT;
ALTER TABLE "repositories" ALTER COLUMN "is_template" TYPE boolean USING "is_template"::boolean;
ALTER TABLE "repositories" ALTER COLUMN "is_template" DROP NOT NULL;
ALTER TABLE "repositories" ALTER COLUMN "is_template" SET default false;
ALTER TABLE "repository_labels" ALTER COLUMN "is_default" DROP DEFAULT;
ALTER TABLE "repository_labels" ALTER COLUMN "is_default" TYPE boolean USING "is_default"::boolean;
ALTER TABLE "repository_labels" ALTER COLUMN "is_default" DROP NOT NULL;
ALTER TABLE "repository_labels" ALTER COLUMN "is_default" SET default false;
ALTER TABLE "repository_mirrors" ALTER COLUMN "enabled" DROP DEFAULT;
ALTER TABLE "repository_mirrors" ALTER COLUMN "enabled" TYPE boolean USING "enabled"::boolean;
ALTER TABLE "repository_mirrors" ALTER COLUMN "enabled" DROP NOT NULL;
ALTER TABLE "repository_mirrors" ALTER COLUMN "enabled" SET default true;
ALTER TABLE "repository_mirrors" ALTER COLUMN "sync_metadata" DROP DEFAULT;
ALTER TABLE "repository_mirrors" ALTER COLUMN "sync_metadata" TYPE boolean USING "sync_metadata"::boolean;
ALTER TABLE "repository_mirrors" ALTER COLUMN "sync_metadata" DROP NOT NULL;
ALTER TABLE "repository_mirrors" ALTER COLUMN "sync_metadata" SET default false;
ALTER TABLE "review_threads" ALTER COLUMN "resolved" DROP DEFAULT;
ALTER TABLE "review_threads" ALTER COLUMN "resolved" TYPE boolean USING "resolved"::boolean;
ALTER TABLE "review_threads" ALTER COLUMN "resolved" DROP NOT NULL;
ALTER TABLE "review_threads" ALTER COLUMN "resolved" SET default false;
ALTER TABLE "review_threads" ALTER COLUMN "outdated" DROP DEFAULT;
ALTER TABLE "review_threads" ALTER COLUMN "outdated" TYPE boolean USING "outdated"::boolean;
ALTER TABLE "review_threads" ALTER COLUMN "outdated" DROP NOT NULL;
ALTER TABLE "review_threads" ALTER COLUMN "outdated" SET default false;
ALTER TABLE "tax_rates" ALTER COLUMN "is_default" DROP DEFAULT;
ALTER TABLE "tax_rates" ALTER COLUMN "is_default" TYPE boolean USING "is_default"::boolean;
ALTER TABLE "tax_rates" ALTER COLUMN "is_default" DROP NOT NULL;
ALTER TABLE "tax_rates" ALTER COLUMN "is_default" SET default false;
ALTER TABLE "users" ALTER COLUMN "is_admin" DROP DEFAULT;
ALTER TABLE "users" ALTER COLUMN "is_admin" TYPE boolean USING "is_admin"::boolean;
ALTER TABLE "users" ALTER COLUMN "is_admin" DROP NOT NULL;
ALTER TABLE "users" ALTER COLUMN "is_admin" SET default false;
ALTER TABLE "webhooks" ALTER COLUMN "active" DROP DEFAULT;
ALTER TABLE "webhooks" ALTER COLUMN "active" TYPE boolean USING "active"::boolean;
ALTER TABLE "webhooks" ALTER COLUMN "active" DROP NOT NULL;
ALTER TABLE "webhooks" ALTER COLUMN "active" SET default true;
