-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "atproto_auth_requests" (
  "id" BIGSERIAL PRIMARY KEY,
  "state" varchar(120) not null,
  "did" varchar(255) not null,
  "handle" varchar(253),
  "issuer" varchar(255) not null,
  "token_endpoint" varchar(500) not null,
  "verifier" varchar(255) not null,
  "sealed_key" text not null,
  "nonce" varchar(500),
  "user_id" bigint REFERENCES "users"("id"),
  "expires_at" varchar(40) not null,
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "atproto_auth_requests_state_index" ON "atproto_auth_requests" ("state");
CREATE INDEX IF NOT EXISTS "atproto_auth_requests_expiry_index" ON "atproto_auth_requests" ("expires_at");
