-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "fail_fast" boolean default true;
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "max_parallel" integer;
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "timeout_minutes" integer;
ALTER TABLE "workflow_jobs" ADD COLUMN IF NOT EXISTS "continue_on_error" boolean default false;
