-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "merge_queue_entries_state_type" AS ENUM ('queued', 'testing', 'merged', 'ejected');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "merge_queue_entries_state_type" ADD VALUE IF NOT EXISTS 'queued';
ALTER TYPE "merge_queue_entries_state_type" ADD VALUE IF NOT EXISTS 'testing';
ALTER TYPE "merge_queue_entries_state_type" ADD VALUE IF NOT EXISTS 'merged';
ALTER TYPE "merge_queue_entries_state_type" ADD VALUE IF NOT EXISTS 'ejected';
