-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "workflow_job_logs_stream_type" AS ENUM ('stdout', 'stderr');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "workflow_job_logs_stream_type" ADD VALUE IF NOT EXISTS 'stdout';
ALTER TYPE "workflow_job_logs_stream_type" ADD VALUE IF NOT EXISTS 'stderr';
