-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "test_runs" (
  "id" BIGSERIAL PRIMARY KEY,
  "test_suite_id" bigint not null REFERENCES "test_suites"("id") ON DELETE CASCADE,
  "head_sha" varchar(64) not null,
  "branch" varchar(255),
  "pull_request_id" integer,
  "workflow_run_id" integer,
  "external_key" varchar(200),
  "source" "test_runs_source_type" default 'json',
  "passed" integer default 0,
  "failed" integer default 0,
  "skipped" integer default 0,
  "muted_failures" integer default 0,
  "duration_ms" integer default 0,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "test_runs_suite_index" ON "test_runs" ("test_suite_id", "id");
CREATE INDEX IF NOT EXISTS "test_runs_commit_index" ON "test_runs" ("test_suite_id", "head_sha");
CREATE UNIQUE INDEX IF NOT EXISTS "test_runs_key_index" ON "test_runs" ("test_suite_id", "external_key");
CREATE UNIQUE INDEX IF NOT EXISTS "test_runs_uuid_unique" ON "test_runs" ("uuid");
