-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "instance_settings" (
  "id" BIGSERIAL PRIMARY KEY,
  "key" varchar(60) not null,
  "value" text,
  "updated_by_id" integer,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "instance_settings_key_unique" ON "instance_settings" ("key");
