-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "environments" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "name" varchar(120) not null,
  "wait_minutes" integer default 0,
  "branches" text default '',
  "description" varchar(500) default '',
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "environments_name_index" ON "environments" ("repository_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "environments_uuid_unique" ON "environments" ("uuid");
