-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "pages_sites" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "enabled" boolean default false,
  "source_branch" varchar(255) default '',
  "domain" varchar(255),
  "visibility" "pages_sites_visibility_type" default 'repository',
  "live_artifact_id" integer,
  "live_run_id" integer,
  "live_sha" varchar(64) default '',
  "live_at" date,
  "last_error" varchar(500) default '',
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp,
  "uuid" varchar(255)
);
