-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "workflow_jobs_state_type" AS ENUM ('blocked', 'queued', 'running', 'cancelling', 'cancelled', 'failed', 'skipped', 'succeeded', 'paused');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "workflow_jobs_state_type" ADD VALUE IF NOT EXISTS 'blocked';
ALTER TYPE "workflow_jobs_state_type" ADD VALUE IF NOT EXISTS 'queued';
ALTER TYPE "workflow_jobs_state_type" ADD VALUE IF NOT EXISTS 'running';
ALTER TYPE "workflow_jobs_state_type" ADD VALUE IF NOT EXISTS 'cancelling';
ALTER TYPE "workflow_jobs_state_type" ADD VALUE IF NOT EXISTS 'cancelled';
ALTER TYPE "workflow_jobs_state_type" ADD VALUE IF NOT EXISTS 'failed';
ALTER TYPE "workflow_jobs_state_type" ADD VALUE IF NOT EXISTS 'skipped';
ALTER TYPE "workflow_jobs_state_type" ADD VALUE IF NOT EXISTS 'succeeded';
ALTER TYPE "workflow_jobs_state_type" ADD VALUE IF NOT EXISTS 'paused';
ALTER TABLE "workflow_jobs" ALTER COLUMN "state" DROP DEFAULT;
ALTER TABLE "workflow_jobs" ALTER COLUMN "state" TYPE "workflow_jobs_state_type" USING "state"::"workflow_jobs_state_type";
ALTER TABLE "workflow_jobs" ALTER COLUMN "state" DROP NOT NULL;
ALTER TABLE "workflow_jobs" ALTER COLUMN "state" SET default 'blocked';
