-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "workflow_notification_rules" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id"),
  "user_id" bigint not null REFERENCES "users"("id"),
  "workflow" varchar(200) default '*',
  "branch" varchar(200) default '*',
  "job_key" varchar(200) default '',
  "condition" "workflow_notification_rules_condition_type" default 'failure',
  "created_by_id" integer,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "workflow_notification_rules_repository_index" ON "workflow_notification_rules" ("repository_id");
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_notification_rules_unique" ON "workflow_notification_rules" ("repository_id", "user_id", "workflow", "branch", "job_key", "condition");
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_notification_rules_uuid_unique" ON "workflow_notification_rules" ("uuid");
