-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "pages_sites_visibility_type" AS ENUM ('public', 'repository');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "pages_sites_visibility_type" ADD VALUE IF NOT EXISTS 'public';
ALTER TYPE "pages_sites_visibility_type" ADD VALUE IF NOT EXISTS 'repository';
CREATE TABLE IF NOT EXISTS "pages_sites" (
  "id" BIGSERIAL PRIMARY KEY,
  "repository_id" bigint not null REFERENCES "repositories"("id") ON DELETE CASCADE,
  "enabled" boolean default false,
  "source_branch" varchar(255) default '',
  "domain" varchar(255),
  "visibility" "pages_sites_visibility_type" default 'repository',
  "live_artifact_id" bigint REFERENCES "workflow_artifacts"("id") ON DELETE SET NULL,
  "live_run_id" bigint REFERENCES "workflow_runs"("id") ON DELETE SET NULL,
  "live_sha" varchar(64) default '',
  "live_at" timestamp,
  "last_error" varchar(500) default '',
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "pages_sites_repository_index" ON "pages_sites" ("repository_id");
CREATE UNIQUE INDEX IF NOT EXISTS "pages_sites_domain_index" ON "pages_sites" ("domain");
CREATE UNIQUE INDEX IF NOT EXISTS "pages_sites_uuid_unique" ON "pages_sites" ("uuid");
