-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "outputs" text;
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "queued_ms" integer;
ALTER TABLE "workflow_steps" ADD COLUMN IF NOT EXISTS "active_ms" integer;
