-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "atproto_identities" (
  "id" BIGSERIAL PRIMARY KEY,
  "user_id" bigint not null REFERENCES "users"("id"),
  "did" varchar(255) not null,
  "handle" varchar(253),
  "pds" varchar(255),
  "last_verified_at" varchar(40),
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "atproto_identities_did_index" ON "atproto_identities" ("did");
CREATE INDEX IF NOT EXISTS "atproto_identities_user_index" ON "atproto_identities" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "atproto_identities_uuid_unique" ON "atproto_identities" ("uuid");
