-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "concurrency_group" varchar(500);
ALTER TABLE "workflow_versions" ADD COLUMN IF NOT EXISTS "cancel_in_progress" boolean default false;
