-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "token_usage_windows" (
  "id" BIGSERIAL PRIMARY KEY,
  "access_token_id" bigint not null REFERENCES "access_tokens"("id") ON DELETE CASCADE,
  "action" varchar(40) not null,
  "window_started_at" varchar(40) not null,
  "used" integer default 0,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "token_usage_windows_token_action_unique" ON "token_usage_windows" ("access_token_id", "action");
