-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "notification_event_preferences_channel_type" AS ENUM ('in_app', 'email', 'push');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "notification_event_preferences_channel_type" ADD VALUE IF NOT EXISTS 'in_app';
ALTER TYPE "notification_event_preferences_channel_type" ADD VALUE IF NOT EXISTS 'email';
ALTER TYPE "notification_event_preferences_channel_type" ADD VALUE IF NOT EXISTS 'push';
DO $stacks$ BEGIN CREATE TYPE "notification_event_preferences_delivery_type" AS ENUM ('off', 'immediate', 'digest');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "notification_event_preferences_delivery_type" ADD VALUE IF NOT EXISTS 'off';
ALTER TYPE "notification_event_preferences_delivery_type" ADD VALUE IF NOT EXISTS 'immediate';
ALTER TYPE "notification_event_preferences_delivery_type" ADD VALUE IF NOT EXISTS 'digest';
