-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "teams" DROP CONSTRAINT IF EXISTS "teams_organization_id_fk";
ALTER TABLE "teams" DROP CONSTRAINT IF EXISTS "teams_organization_id_fkey";
ALTER TABLE "teams" ADD CONSTRAINT "teams_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE;
