-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "operations" (
  "id" BIGSERIAL PRIMARY KEY,
  "kind" varchar(60) not null,
  "status" "operations_status_type" default 'queued',
  "subject_type" varchar(40),
  "subject_id" integer,
  "actor_id" integer,
  "access_token_id" bigint REFERENCES "access_tokens"("id"),
  "idempotency_scope" varchar(120),
  "idempotency_key" varchar(120),
  "started_at" varchar(40),
  "finished_at" varchar(40),
  "result" text,
  "error" text,
  "cancel_requested_at" varchar(40),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "operations_subject_index" ON "operations" ("subject_type", "subject_id", "created_at");
CREATE INDEX IF NOT EXISTS "operations_token_index" ON "operations" ("access_token_id", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "operations_idempotency_index" ON "operations" ("idempotency_scope", "idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "operations_uuid_unique" ON "operations" ("uuid");
