-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "git_wal_entries_status_type" AS ENUM ('pending', 'committed', 'void');
EXCEPTION WHEN duplicate_object THEN null;
END $stacks$;
ALTER TYPE "git_wal_entries_status_type" ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE "git_wal_entries_status_type" ADD VALUE IF NOT EXISTS 'committed';
ALTER TYPE "git_wal_entries_status_type" ADD VALUE IF NOT EXISTS 'void';
