-- @generated by `buddy migrate:regenerate` — edits will be overwritten
DO $stacks$ BEGIN CREATE TYPE "workflow_notification_rules_condition_type" AS ENUM ('failure', 'success', 'recovery', 'always'); EXCEPTION WHEN duplicate_object THEN null; END $stacks$;
ALTER TYPE "workflow_notification_rules_condition_type" ADD VALUE IF NOT EXISTS 'failure';
ALTER TYPE "workflow_notification_rules_condition_type" ADD VALUE IF NOT EXISTS 'success';
ALTER TYPE "workflow_notification_rules_condition_type" ADD VALUE IF NOT EXISTS 'recovery';
ALTER TYPE "workflow_notification_rules_condition_type" ADD VALUE IF NOT EXISTS 'always';
