-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "check_runs" ADD COLUMN IF NOT EXISTS "reporter_id" integer;
ALTER TABLE "check_runs" ADD COLUMN IF NOT EXISTS "provider" varchar(100);
ALTER TABLE "check_runs" ADD COLUMN IF NOT EXISTS "external_id" varchar(255);
ALTER TABLE "check_runs" ADD COLUMN IF NOT EXISTS "idempotency_key" varchar(255);
ALTER TABLE "check_runs" ADD COLUMN IF NOT EXISTS "output_title" varchar(255);
ALTER TABLE "check_runs" ADD COLUMN IF NOT EXISTS "output_text" text;
ALTER TABLE "check_runs" ADD COLUMN IF NOT EXISTS "attempt" integer default 1;
