ALTER TABLE "coupons" ALTER COLUMN "is_active" TYPE boolean USING "is_active"::boolean;
ALTER TABLE "digital_deliveries" ALTER COLUMN "requires_login" TYPE boolean USING "requires_login"::boolean;
ALTER TABLE "digital_deliveries" ALTER COLUMN "automatic_delivery" TYPE boolean USING "automatic_delivery"::boolean;
ALTER TABLE "gift_cards" ALTER COLUMN "is_active" TYPE boolean USING "is_active"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "send_and_archive" TYPE boolean USING "send_and_archive"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "desktop_notifications" TYPE boolean USING "desktop_notifications"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "notification_preview" TYPE boolean USING "notification_preview"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "load_remote_images" TYPE boolean USING "load_remote_images"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "show_external_content" TYPE boolean USING "show_external_content"::boolean;
ALTER TABLE "mail_preferences" ALTER COLUMN "vacation_enabled" TYPE boolean USING "vacation_enabled"::boolean;
DROP INDEX IF EXISTS "notification_deliveries_idx_notification_deliveries_channel";
DROP INDEX IF EXISTS "notification_deliveries_idx_notification_deliveries_status";
ALTER TABLE "notification_deliveries" ALTER COLUMN "created_at" TYPE timestamp USING "created_at"::timestamp;
ALTER TABLE "tax_rates" ALTER COLUMN "is_default" TYPE boolean USING "is_default"::boolean;
DROP INDEX IF EXISTS "categorizable_models_categorizable_models_category_id_categoriz";
DROP INDEX IF EXISTS "taggable_models_taggable_models_tag_id_taggable_id_taggable_typ";
