-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "concurrency_group" varchar(500);
ALTER TABLE "workflow_version_jobs" ADD COLUMN IF NOT EXISTS "job_cancel_in_progress" boolean default false;
