// The generated reference pages, and the check that the committed copies are
// the ones the code would produce.
//
// The drift check is the point of the whole unit. A reference generated by a
// command nobody runs is a hand-written reference with extra steps: the file
// stops matching the API, and it looks authoritative right up until somebody
// trusts it.

import { describe, expect, test } from 'bun:test'
import { countDeclared, declaredRoutes, groupPaths, pathsOf, renderApiReference, renderWebhookReference, titleFor } from '../../app/Docs/reference'
import { WEBHOOK_EVENTS } from '../../app/Webhooks/payloads'

const DOCUMENT = {
  paths: {
    '/api/repos/workflow-runs': {
      get: {
        summary: 'List workflow runs',
        parameters: [
          { name: 'owner', in: 'query', required: true, schema: { type: 'string' } },
          { name: 'status', in: 'query', required: false, schema: { type: 'string' } },
        ],
        responses: {
          200: { description: 'The runs, newest first' },
          404: { description: 'No such repository, or none this token can see' },
        },
      },
      post: {
        requestBody: {
          content: {
            'application/json': {
              schema: { properties: { name: { type: 'string' }, sha: { type: 'string' } }, required: ['name'] },
            },
          },
        },
        responses: { 201: { description: 'Created' } },
      },
    },
    '/api/checks': { get: { responses: { 200: { description: 'ok' } } } },
    '/api/campaigns': { get: { responses: { 200: { description: 'a framework default' } } } },
    '/health': { get: { responses: { 200: { description: 'not part of the API' } } } },
  },
} as any

describe('what belongs in the reference', () => {
  test('only what this application declares, not every route in the process', () => {
    // The document carries the framework's defaults too, and a git forge's
    // reference listing `Campaigns` is 550 entries in which the hundred
    // somebody wants cannot be found.
    const routes = declaredRoutes([
      { prefix: '/api', source: `route.get('/repos/workflow-runs', 'X'); route.post('/repos/workflow-runs', 'Y'); route.get('/checks', 'Z')` },
    ])

    expect([...groupPaths(DOCUMENT, pathsOf(routes)).keys()]).toEqual(['checks', 'repos'])
  })

  test('and nothing outside /api, which is not a surface a client is offered', () => {
    expect([...groupPaths(DOCUMENT).keys()]).not.toContain('health')
  })

  test('a route carries the action that answers it, not only its path', () => {
    // The value is what an endpoint that documents nothing can be traced to,
    // which is the difference between a useless entry and a lead.
    const routes = declaredRoutes([{ prefix: '/api', source: `route.post('/repos', 'Actions/Repo/CreateRepositoryAction').middleware('auth')` }])

    expect(routes.get('post /api/repos')).toBe('Actions/Repo/CreateRepositoryAction')
  })

  test('groups are the noun a reader has in mind, sorted', () => {
    const routes = declaredRoutes([{ prefix: '/api', source: `route.get('/checks', 'A'); route.get('/repos/workflow-runs', 'B')` }])

    expect([...groupPaths(DOCUMENT, pathsOf(routes)).keys()]).toEqual(['checks', 'repos'])
    expect(titleFor('workflow-runs')).toBe('Workflow runs')
  })
})

describe('the API page', () => {
  const routes = declaredRoutes([
    { prefix: '/api', source: `route.get('/repos/workflow-runs', 'A'); route.post('/repos/workflow-runs', 'B')` },
  ])

  const page = renderApiReference(DOCUMENT, 'from OpenAPI 1.0.0', routes)

  test('lists every method of a path, not just the first', () => {
    expect(page).toContain('### `GET /api/repos/workflow-runs`')
    expect(page).toContain('### `POST /api/repos/workflow-runs`')
  })

  test('says what a call takes, from the query and the body alike', () => {
    expect(page).toContain('| `owner` | query | required | string |')
    expect(page).toContain('| `status` | query | optional | string |')
    expect(page).toContain('| `name` | body | required | string |')
    expect(page).toContain('| `sha` | body | optional | string |')
  })

  test('and what it answers, in the words the action itself used', () => {
    // The point of `responses` living on the action: the sentence a reader
    // gets is the sentence the person who wrote the endpoint wrote.
    expect(page).toContain('| `404` | No such repository, or none this token can see |')
  })

  /*
   * An endpoint described on purpose is taken at its word. `POST
   * /api/runner/claim` takes a credential in a header and nothing else;
   * sending a reader to an action that has nothing more to say is worse than
   * saying so plainly.
   */
  test('an endpoint that documented its answers is taken at its word about its inputs', () => {
    const described = renderApiReference(
      { paths: { '/api/runner/claim': { post: { responses: { 401: { description: 'No credential, or one this instance does not recognise.' } } } } } } as any,
      'from OpenAPI 1.0.0',
      declaredRoutes([{ prefix: '/api', source: `route.post('/runner/claim', 'Actions/Runner/ClaimJobAction')` }]),
    )

    expect(described).toContain('_Takes no parameters._')
    expect(described).not.toContain('Inputs are not declared')
  })

  /*
   * And one that said nothing at all gets the honest answer. "Takes no
   * parameters" would be a lie for most of the surface: the document only
   * knows what an action declares in `validations`, so an endpoint that
   * plainly requires a name would be published as taking nothing.
   */
  test('an endpoint that declares nothing names its action rather than claiming it takes nothing', () => {
    const bare = renderApiReference(
      { paths: { '/api/repos': { post: { responses: {} } } } } as any,
      'from OpenAPI 1.0.0',
      declaredRoutes([{ prefix: '/api', source: `route.post('/repos', 'Actions/Repo/CreateRepositoryAction')` }]),
    )

    expect(bare).toContain('_Inputs are not declared on `Actions/Repo/CreateRepositoryAction`')
    expect(bare).not.toContain('_Takes no parameters._')
    expect(bare).not.toContain('| Status | Means |')
  })

  test('the count in the opening line is the number of paths below it', () => {
    // A sentence that says "550 of them" over a page listing 136 is the kind
    // of wrong that survives for years because nobody counts. Paths, not
    // operations: two methods of one endpoint are one entry in the list.
    const paths = new Set([...page.matchAll(/^### `[A-Z]+ (\S+)`$/gm)].map(match => match[1]))

    expect(paths.size).toBe(1)
    expect(page).toContain(`declares under \`/api\`, ${paths.size} of them`)
  })
})

describe('the webhook page', () => {
  const page = renderWebhookReference('from OpenAPI 1.0.0')

  test('lists every event this instance can send, and only those', () => {
    for (const event of WEBHOOK_EVENTS)
      expect(page).toContain(`| \`${event}\` |`)

    const listed = (page.match(/^\| `[a-z_]+:[a-z_]+` \|/gm) ?? []).length

    expect(listed).toBe(WEBHOOK_EVENTS.length)
  })

  test('every event has a sentence rather than a placeholder', () => {
    expect(page).not.toContain('see the payload module')
  })

  test('describes the envelope once, because it is the same for all of them', () => {
    expect(page).toContain('"delivered_at"')
    expect(page).toContain('`sender` is null when nothing did it')
  })
})

describe('the committed pages', () => {
  /*
   * The drift check. `buddy docs:reference --check` is the same comparison in
   * a form a person can run, and a failure here names it.
   */
  test('are what the generator produces today', async () => {
    const spec = await Bun.file('storage/framework/api/openapi.json').json()

    const routes = declaredRoutes([
      { prefix: '/api', source: await Bun.file('routes/api.ts').text() },
      { prefix: '/api', source: await Bun.file('routes/v1.ts').text().catch(() => '') },
      { prefix: '/api', source: await Bun.file('routes/users.ts').text().catch(() => '') },
      { prefix: '/api', source: await Bun.file('routes/notifications.ts').text().catch(() => '') },
      { prefix: '/api', source: await Bun.file('routes/attachments.ts').text().catch(() => '') },
    ])

    const at = `from OpenAPI ${spec.info?.version ?? '1.0.0'}`

    expect(await Bun.file('docs/api.md').text()).toBe(renderApiReference(spec, at, routes))
    expect(await Bun.file('docs/webhooks.md').text()).toBe(renderWebhookReference(at))
  })

  /*
   * A ratchet, not a target.
   *
   * Most of the surface validates by hand inside the handler, so the document
   * has nothing to publish for it and the page says so. Declaring those inputs
   * is real work spread over many actions; what this test buys is that the
   * number only moves one way. Lower the ceiling when you declare some.
   *
   * It went **up** once, by one, and the exception is worth stating rather than
   * hiding: the cache save takes a tar as its body and its inputs as headers,
   * so it has no fields to declare and there was no way to declare a header.
   * The framework gained `requestHeaders` for exactly that (Stacks 511aa3c3),
   * and this comes back to 109 when that release reaches this app. An endpoint
   * that could have declared something and did not is still a failure here.
   */
  test('and the count of endpoints that document nothing only goes down', async () => {
    const spec = await Bun.file('storage/framework/api/openapi.json').json()

    const routes = declaredRoutes([{ prefix: '/api', source: await Bun.file('routes/api.ts').text() }])
    const { declared, operations } = countDeclared(spec, groupPaths(spec, pathsOf(routes)))

    expect(operations - declared).toBeLessThanOrEqual(110)
  })

  /*
   * Every page, not two named ones.
   *
   * Four pages had already been written and shipped with nothing linking to
   * them - the extension surface, the conformance table, the autoscaler
   * contract and test intelligence - which is the same as not having written
   * them. A test that names its pages one at a time only catches the pages
   * somebody remembered to add to it.
   */
  test('and every documentation page is linked from the sidebar, or nobody finds it', async () => {
    const config = await Bun.file('config/docs.ts').text()
    const pages = (await Array.fromAsync(new Bun.Glob('*.md').scan({ cwd: 'docs' })))
      .map(name => name.replace(/\.md$/, ''))
      // The index is the landing page; the roadmap has its own section below.
      .filter(name => name !== 'index')
      .sort()

    const missing = pages.filter(page => !config.includes(`link: '/${page}'`))

    expect(missing).toEqual([])
  })
})
