import { describe, expect, it } from 'bun:test'
import { looksLikeSvg, MAX_MEDIA_BYTES, mediaHeaders, sniffImageType } from '../../app/Actions/Git/media'

/**
 * The one place this forge serves a repository's bytes as their own type, and
 * the rules that make that safe: the type comes from the bytes, off a closed
 * list, and everything else is refused.
 */

function bytes(...values: number[]): Uint8Array {
  return new Uint8Array(values)
}

function text(value: string): Uint8Array {
  return new TextEncoder().encode(value)
}

const PNG = bytes(0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0, 0, 0, 13)
const JPEG = bytes(0xFF, 0xD8, 0xFF, 0xE0, 0, 0x10, 0x4A, 0x46)
const GIF = text('GIF89a\x01\x00')
const BMP = text('BM\x36\x00')
const ICO = bytes(0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x10, 0x10)

function riff(payload: string): Uint8Array {
  return text(`RIFF\x00\x00\x00\x00${payload}`)
}

function isoMedia(brand: string): Uint8Array {
  return text(`\x00\x00\x00\x18ftyp${brand}`)
}

describe('sniffImageType', () => {
  it.each([
    ['png', PNG, 'image/png'],
    ['jpeg', JPEG, 'image/jpeg'],
    ['gif', GIF, 'image/gif'],
    ['bmp', BMP, 'image/bmp'],
    ['ico', ICO, 'image/x-icon'],
  ])('recognises %s', (_name, input, expected) => {
    expect(sniffImageType(input as Uint8Array)).toBe(expected as any)
  })

  it('recognises webp by its payload rather than by the RIFF header alone', () => {
    expect(sniffImageType(riff('WEBPVP8 '))).toBe('image/webp')
    // A WAV is also RIFF, and is not an image.
    expect(sniffImageType(riff('WAVEfmt '))).toBeNull()
  })

  it('accepts the still-image ISO brands and refuses video in the same container', () => {
    expect(sniffImageType(isoMedia('avif'))).toBe('image/avif')
    expect(sniffImageType(isoMedia('avis'))).toBe('image/avif')
    // MP4 arrives in exactly the same box. Serving it as an image would be
    // serving a type nobody asked this endpoint for.
    expect(sniffImageType(isoMedia('isom'))).toBeNull()
    expect(sniffImageType(isoMedia('mp42'))).toBeNull()
  })

  it('refuses HTML however it is named', () => {
    // The whole reason the type is decided here rather than from the filename:
    // `logo.png` holding a page is one push away, and served as HTML it would
    // run script on this origin.
    expect(sniffImageType(text('<!DOCTYPE html><html><body>hi'))).toBeNull()
    expect(sniffImageType(text('<script>alert(1)</script>'))).toBeNull()
  })

  it('refuses a PDF, a zip and plain text', () => {
    expect(sniffImageType(text('%PDF-1.7'))).toBeNull()
    expect(sniffImageType(text('PK\x03\x04'))).toBeNull()
    expect(sniffImageType(text('just some notes'))).toBeNull()
  })

  it('refuses an empty file and a file too short to say anything', () => {
    expect(sniffImageType(bytes())).toBeNull()
    expect(sniffImageType(bytes(0x89, 0x50))).toBeNull()
  })

  it('is not fooled by a signature that starts one byte late', () => {
    expect(sniffImageType(bytes(0x00, 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A))).toBeNull()
  })
})

describe('looksLikeSvg', () => {
  it('recognises a bare svg', () => {
    expect(looksLikeSvg(text('<svg xmlns="http://www.w3.org/2000/svg"></svg>'))).toBe(true)
  })

  it('scans past what a drawing tool puts in front of the tag', () => {
    const exported = '﻿<?xml version="1.0"?>\n<!-- Generated by a tool -->\n'
      + '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "x.dtd">\n<svg width="10"></svg>'

    expect(looksLikeSvg(text(exported))).toBe(true)
  })

  it('does not accept a tag that merely starts with the letters', () => {
    expect(looksLikeSvg(text('<svgnot></svgnot>'))).toBe(false)
  })

  it('does not accept an HTML document that mentions svg later', () => {
    expect(looksLikeSvg(text('<html><body><svg></svg></body></html>'))).toBe(false)
  })

  it('does not hang on an unterminated comment', () => {
    expect(looksLikeSvg(text('<!-- never closed <svg>'))).toBe(false)
  })
})

describe('mediaHeaders', () => {
  it('makes the response inert whatever the type is', () => {
    // Applied to every type rather than only to SVG: a policy with an exception
    // is a policy somebody extends the exception of.
    for (const type of ['image/png', 'image/svg+xml'] as const) {
      const headers = mediaHeaders(type)

      expect(headers.contentType).toBe(type)
      expect(headers.contentSecurityPolicy).toContain('default-src \'none\'')
      expect(headers.contentSecurityPolicy).toContain('sandbox')
    }
  })

  it('serves inline, which is the only reason this endpoint exists', () => {
    expect(mediaHeaders('image/png').disposition).toBe('inline')
  })
})

describe('MAX_MEDIA_BYTES', () => {
  it('is far past a diagram and far short of anything worth buffering', () => {
    expect(MAX_MEDIA_BYTES).toBeGreaterThan(1024 * 1024)
    expect(MAX_MEDIA_BYTES).toBeLessThanOrEqual(16 * 1024 * 1024)
  })
})
