import { describe, expect, it } from 'bun:test'
import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Every migration comes from a model.
 *
 * The models are the schema. `buddy migrate:regenerate` rebuilds
 * `database/migrations/` from them, so a hand-written file in there is a change
 * the next regeneration silently deletes - and worse, a rule the models do not
 * know about, which means the schema and the source of truth disagree with
 * nothing reporting it.
 *
 * This got written after a hand-written migration was needed to drop foreign
 * keys the models had superseded. It was a real repair, and it was also a sign
 * the *models* were wrong rather than the generator: once every relation was
 * declared, the whole corpus regenerated with the constraints inline and the
 * repair had nothing left to do.
 *
 * Two of those relations were missing entirely. `issues.milestone_id` and
 * `access_tokens.organization_id` were declared as plain attributes, so no
 * constraint was generated and nothing stopped a row pointing at a milestone or
 * an organization that had been deleted.
 */

const MIGRATIONS = 'database/migrations'
const MODELS = 'app/Models'

const files = readdirSync(MIGRATIONS).filter(name => name.endsWith('.sql'))
const corpus = files.map(name => readFileSync(join(MIGRATIONS, name), 'utf8')).join('\n')

function snake(value: string): string {
  return value
    .replace(/([a-z\d])([A-Z])/g, '$1_$2')
    .toLowerCase()
}

describe('the migration corpus', () => {
  it('has migrations at all, so a passing run means something', () => {
    expect(files.length).toBeGreaterThan(50)
  })

  /**
   * The generator writes `<number>-<verb>-<subject>.sql` and nothing else. A
   * name it would not produce is a file it did not produce.
   */
  it('contains only files the generator names', () => {
    const strange = files.filter(name => !/^\d{10}-(?:create|alter|drop|auto-misc)/.test(name))

    expect(strange).toEqual([])
  })

  /**
   * The generator emits no commentary. A comment is a person explaining
   * something to the next person, which is worth doing - in the model, where it
   * survives a regeneration.
   */
  it('contains no hand-written commentary', () => {
    // The generator stamps its own header - `-- qb:generated` and
    // `-- @generated by ...` - which is the opposite of the thing this forbids:
    // it is the file saying it is disposable. Exempted by matching the markers
    // rather than by allowing the first lines, so a hand-written comment under
    // a generated header is still caught.
    const generatedHeader = /^--\s*(?:@generated\b|qb:generated\s*$).*$/gm

    const annotated = files.filter((name) => {
      const body = readFileSync(join(MIGRATIONS, name), 'utf8').replace(generatedHeader, '')
      return /^\s*--/m.test(body)
    })

    expect(annotated).toEqual([])
  })
})

describe('what the models declare reaches the SQL', () => {
  const modelFiles = readdirSync(MODELS).filter(name => name.endsWith('.ts'))

  /**
   * A table nobody describes.
   *
   * The other checks here all start from the models and look for their effect
   * in the SQL. This one goes the other way, and it is the direction that was
   * missing: a table can be created by a migration with no model behind it at
   * all, and then nothing in this file notices. The generator does not notice
   * either - it emits what the models say, so a table they do not mention is
   * simply outside its world.
   *
   * `password_resets` sat in exactly that blind spot. The framework's auth step
   * creates it, the framework's own `sendEmail` writes an `expires_at` the
   * table did not have, and the repair was a hand-written `ALTER` describing a
   * column no model knew about. Every reset link this forge sent was invalid,
   * for as long as the schema had been built from models, and every test in
   * the password-reset suite passed - because a request that writes a token
   * and a request that writes nothing answer identically on purpose.
   *
   * Framework tables are the point rather than an exception to it. Overriding
   * one is a file in `app/Models/`, which is cheap; the cost of not having it
   * is a column the schema owns and the models cannot see.
   */
  it('has a model for every table the corpus touches', () => {
    const declared = new Set(
      modelFiles.flatMap((name) => {
        const source = readFileSync(join(MODELS, name), 'utf8')
        const table = /\btable:\s*'([^']+)'/.exec(source)?.[1]

        return table ? [table] : []
      }),
    )

    /*
     * Framework-owned tables this application does not describe and has no
     * reason to. Each one is a deliberate decision rather than a backlog: the
     * application never reads or writes them, so a model would be a
     * description with no reader. Anything the application *touches* belongs
     * in `app/Models/` instead of on this list.
     */
    const frameworkOwned = new Set([
      'migrations',
      'passkeys',
      'sessions',
      'personal_access_tokens',
    ])

    /*
     * `ALTER` as well as `CREATE`, and that is the whole point.
     *
     * Matching only `CREATE TABLE` misses precisely the case this was written
     * for: `password_resets` is created by the framework's auth step, not by
     * any migration here, so the corpus never names it except in the one
     * hand-written `ALTER` that added the missing column. A check that reads
     * only creations looks straight past a table this repository is actively
     * patching - which is the strongest possible signal that it owns it and
     * ought to describe it.
     */
    const touched = [
      ...[...corpus.matchAll(/CREATE TABLE(?: IF NOT EXISTS)? "([^"]+)"/g)].map(match => match[1]),
      ...[...corpus.matchAll(/ALTER TABLE "([^"]+)"/g)].map(match => match[1]),
    ]

    const undescribed = [...new Set(touched)]
      .filter(table => !declared.has(table) && !frameworkOwned.has(table))
      .sort()

    expect(undescribed).toEqual([])
  })


  it('reads the models', () => {
    expect(modelFiles.length).toBeGreaterThan(10)
  })

  /**
   * An `onDelete` that never reaches a constraint is worse than none: the model
   * says the database will clean up, the database does nothing, and the rows
   * that outlive their parent are found by whoever hits the orphan.
   *
   * Read from source rather than by importing the models - a model file pulls
   * in framework globals, and this needs to run in a bare `bun test`.
   */
  it('emits a constraint for every relation that declares an onDelete', () => {
    const missing: string[] = []

    for (const name of modelFiles) {
      const source = readFileSync(join(MODELS, name), 'utf8')
      const table = source.match(/\btable:\s*'([^']+)'/)?.[1]
      if (!table)
        continue

      // `{ model: 'X', foreignKey?: 'y_id', onDelete: 'cascade' }`, in any
      // order - the field order in a model is the author's choice.
      for (const entry of source.matchAll(/\{[^{}]*\bmodel:\s*'(\w+)'[^{}]*\bonDelete:\s*'([^']+)'[^{}]*\}/g)) {
        const [whole, model, action] = entry
        const column = whole.match(/foreignKey:\s*'([^']+)'/)?.[1] ?? `${snake(model!)}_id`
        const expected = new RegExp(
          `"${column}"[^,\\n]*REFERENCES[^,\\n]*ON DELETE ${action!.toUpperCase()}`,
          'i',
        )

        if (!expected.test(corpus))
          missing.push(`${table}.${column} -> ${model} ON DELETE ${action!.toUpperCase()}`)
      }
    }

    expect(missing).toEqual([])
  })

  /**
   * The two that were missing, named. The rule above would catch them again,
   * but only once somebody had already declared the relation - and the bug was
   * that nobody had.
   */
  it('constrains the foreign keys that were only ever attributes', () => {
    expect(corpus).toMatch(/"milestone_id"[^,\n]*REFERENCES "milestones"\("id"\) ON DELETE SET NULL/)
    expect(corpus).toMatch(/"organization_id"[^,\n]*REFERENCES "organizations"\("id"\) ON DELETE CASCADE/)
  })
})
