/**
 * Every route is in the OpenAPI document, and the document is generated.
 *
 * **The bar this phase sets is that the API is discoverable without reading the
 * source.** A route that exists and is undocumented fails that quietly: it
 * works, nothing errors, and the only people who know about it are the ones who
 * grepped `routes/`. The generated client will not have it either, because the
 * client is generated from this document.
 *
 * So this walks the route table and fails on anything missing. It is a
 * *coverage* test rather than a schema test - it does not check that the
 * documented parameters are right, only that the endpoint is there at all,
 * because the generator derives the rest from the action and cannot drift from
 * it the way a hand-written document can.
 *
 * The document is regenerated by `./buddy generate:openapi`, so a failure here
 * usually means somebody added a route and did not re-run it. That is the point:
 * the failure is a reminder rather than an investigation.
 *
 * **The route table is read in a child process, and that is not incidental.**
 * `route.routes` is shared by everything in the process, and `route.serve()`
 * adds the 65 file-based views to it. Read in place, this test passed on its own
 * and failed under the full suite naming `GET /`, `GET /features` and
 * `GET /{owner}/{repository}` as undocumented API - a verdict that depended on
 * whether an e2e file had booted a server first. A parity rule that answers
 * differently by execution order is not proving anything. See
 * `tests/helpers/declaredRoutes.ts` for why the table cannot simply be reset.
 */

import { describe, expect, test } from 'bun:test'
import { declaredRoutes } from '../helpers/declaredRoutes'

/**
 * Routes that are deliberately absent from the public document.
 *
 * Each one is here because publishing it would be actively wrong, not because
 * documenting it was inconvenient. Anything not on this list and not in the
 * document is a bug.
 */
const NOT_PUBLIC = [
  // The git wire protocol. Not a JSON API at all - it speaks pkt-line over
  // HTTP, and describing it in OpenAPI would produce a client nobody could use
  // and imply the endpoints are a supported surface for anything but `git`.
  /^\/[^/]+\/[^/]+\.git(\/|$)/,
  // The pre-receive gate and post-receive hook, called by scripts this server
  // wrote into the repository. Reachable only from the hook, and documenting
  // them would invite somebody to call them.
  /^\/internal\//,
  // The framework's own development surfaces: the route dump, the storage
  // browser, and the document itself. Development affordances rather than
  // product, and documenting the document is a circle.
  /^\/_stacks\//,
  /^\/__/,
]

function isPublic(path: string): boolean {
  return !NOT_PUBLIC.some(pattern => pattern.test(path))
}

/**
 * One spelling for a path parameter.
 *
 * The route table reports `/queries/:id` and the document says
 * `/queries/{id}` - the same endpoint, written the two ways their respective
 * conventions write it. Comparing them verbatim finds a "missing" route for
 * every parameterised path, and there are 173 of them, so the comparison would
 * either be permanently red or - far worse - get the parameterised paths
 * excluded to make it green, which silently stops testing a quarter of the API.
 */
function normalize(path: string): string {
  return path.replace(/\{(\w+)\}/g, ':$1')
}

describe('the OpenAPI document', () => {
  test('has an operation for every registered route', async () => {
    const spec = await Bun.file('storage/framework/api/openapi.json').json()
    const documented = new Set(Object.keys(spec.paths ?? {}).map(normalize))

    const registered: Array<{ method: string, path: string }> = (await declaredRoutes())
      .filter(entry => isPublic(entry.path))

    // Something is very wrong if the table is empty - and an empty table would
    // make this test pass by describing nothing.
    expect(registered.length).toBeGreaterThan(50)

    const missing = registered
      .filter(entry => !documented.has(normalize(entry.path)))
      .map(entry => `${entry.method} ${entry.path}`)

    /*
     * Reported as a list rather than a count. "3 routes are undocumented" sends
     * somebody to diff two sets by hand; the names send them to the generator.
     */
    expect(missing).toEqual([])
  })

  test('and documents the method each route actually answers on', async () => {
    /*
     * A path in the document with the wrong verb is worse than a missing one: a
     * generated client calls it, gets a 404 or a 405, and the document says it
     * should have worked.
     */
    const spec = await Bun.file('storage/framework/api/openapi.json').json()

    const wrong: string[] = []

    for (const entry of await declaredRoutes()) {
      const path = String(entry.path)
      if (!isPublic(path))
        continue

      const operations = spec.paths?.[path] ?? spec.paths?.[path.replace(/:(\w+)/g, '{$1}')]
      if (!operations)
        continue

      const verb = String(entry.method).toLowerCase()
      if (!(verb in operations))
        wrong.push(`${entry.method} ${path}`)
    }

    expect(wrong).toEqual([])
  })
})

describe('the generated client', () => {
  test('matches the document it was generated from', async () => {
    /*
     * A generated client that nothing verifies is a hand-maintained client with
     * extra steps. It stops matching the day somebody regenerates the document
     * alone, and the mismatch shows up in a consumer's project as a missing
     * method rather than here as a failure.
     *
     * Compared byte for byte against a fresh render, which is only meaningful
     * because the renderer is deterministic: the document's paths are already
     * sorted for exactly this reason.
     */
    const { renderApiClient } = await import('@stacksjs/api')

    const spec = await Bun.file('storage/framework/api/openapi.json').json()
    const checkedIn = await Bun.file('storage/framework/api/client.ts').text()

    expect(checkedIn).toBe(renderApiClient(spec, { name: spec.info?.title }))
  })

  test('has a method for every operation in it', async () => {
    const spec = await Bun.file('storage/framework/api/openapi.json').json()
    const client = await Bun.file('storage/framework/api/client.ts').text()

    const operations = Object.values(spec.paths ?? {})
      .flatMap((item: any) => Object.keys(item))
      .length

    // One `name(input` line per operation. Counting rather than naming: the
    // names are the generator's business and are tested where it lives. What
    // matters here is that none of them were dropped.
    const methods = client.match(/^ {2}\w+\(/gm)?.length ?? 0

    expect(methods).toBe(operations)
  })
})
