/**
 * Every route is in the OpenAPI document, and the document is generated.
 *
 * **The bar this phase sets is that the API is discoverable without reading the
 * source.** A route that exists and is undocumented fails that quietly: it
 * works, nothing errors, and the only people who know about it are the ones who
 * grepped `routes/`. The generated client will not have it either, because the
 * client is generated from this document.
 *
 * So this walks the route table and fails on anything missing. It is a
 * *coverage* test rather than a schema test - it does not check that the
 * documented parameters are right, only that the endpoint is there at all,
 * because the generator derives the rest from the action and cannot drift from
 * it the way a hand-written document can.
 *
 * The document is regenerated by `./buddy generate:openapi`, so a failure here
 * usually means somebody added a route and did not re-run it. That is the point:
 * the failure is a reminder rather than an investigation.
 */

import { describe, expect, test } from 'bun:test'

/**
 * Routes that are deliberately absent from the public document.
 *
 * Each one is here because publishing it would be actively wrong, not because
 * documenting it was inconvenient. Anything not on this list and not in the
 * document is a bug.
 */
const NOT_PUBLIC = [
  // The git wire protocol. Not a JSON API at all - it speaks pkt-line over
  // HTTP, and describing it in OpenAPI would produce a client nobody could use
  // and imply the endpoints are a supported surface for anything but `git`.
  /^\/[^/]+\/[^/]+\.git(\/|$)/,
  // The pre-receive gate and post-receive hook, called by scripts this server
  // wrote into the repository. Reachable only from the hook, and documenting
  // them would invite somebody to call them.
  /^\/internal\//,
  // The framework's own development surfaces: the route dump, the storage
  // browser, and the document itself. Development affordances rather than
  // product, and documenting the document is a circle.
  /^\/_stacks\//,
  /^\/__/,
]

function isPublic(path: string): boolean {
  return !NOT_PUBLIC.some(pattern => pattern.test(path))
}

/**
 * One spelling for a path parameter.
 *
 * The route table reports `/queries/:id` and the document says
 * `/queries/{id}` - the same endpoint, written the two ways their respective
 * conventions write it. Comparing them verbatim finds a "missing" route for
 * every parameterised path, and there are 173 of them, so the comparison would
 * either be permanently red or - far worse - get the parameterised paths
 * excluded to make it green, which silently stops testing a quarter of the API.
 */
function normalize(path: string): string {
  return path.replace(/\{(\w+)\}/g, ':$1')
}

describe('the OpenAPI document', () => {
  test('has an operation for every registered route', async () => {
    const { route } = await import('@stacksjs/router')
    await route.importRoutes()

    const spec = await Bun.file('storage/framework/api/openapi.json').json()
    const documented = new Set(Object.keys(spec.paths ?? {}).map(normalize))

    const registered: Array<{ method: string, path: string }> = (route.routes ?? [])
      .map((entry: any) => ({ method: String(entry.method), path: String(entry.path) }))
      .filter((entry: { path: string }) => isPublic(entry.path))

    // Something is very wrong if the table is empty - and an empty table would
    // make this test pass by describing nothing.
    expect(registered.length).toBeGreaterThan(50)

    const missing = registered
      .filter(entry => !documented.has(normalize(entry.path)))
      .map(entry => `${entry.method} ${entry.path}`)

    /*
     * Reported as a list rather than a count. "3 routes are undocumented" sends
     * somebody to diff two sets by hand; the names send them to the generator.
     */
    expect(missing).toEqual([])
  })

  test('and documents the method each route actually answers on', async () => {
    /*
     * A path in the document with the wrong verb is worse than a missing one: a
     * generated client calls it, gets a 404 or a 405, and the document says it
     * should have worked.
     */
    const { route } = await import('@stacksjs/router')
    await route.importRoutes()

    const spec = await Bun.file('storage/framework/api/openapi.json').json()

    const wrong: string[] = []

    for (const entry of (route.routes ?? []) as any[]) {
      const path = String(entry.path)
      if (!isPublic(path))
        continue

      const operations = spec.paths?.[path] ?? spec.paths?.[path.replace(/:(\w+)/g, '{$1}')]
      if (!operations)
        continue

      const verb = String(entry.method).toLowerCase()
      if (!(verb in operations))
        wrong.push(`${entry.method} ${path}`)
    }

    expect(wrong).toEqual([])
  })
})
